package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.links.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11IntroducedComponentsTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    boolean accepts(String skill,String passive,String... selected){
        return new CompatibilityService().assess(f.bundle.catalog().skill(new SkillId(skill)).orElseThrow(),
                f.bundle.catalog().passive(new PassiveId(passive)).orElseThrow(),Arrays.stream(selected)
                        .map(id->f.bundle.catalog().passive(new PassiveId(id)).orElseThrow()).toList()).accepted();
    }
    HitProcRuntime.Hit hit(double amount,double unit){return new HitProcRuntime.Hit(UUID.randomUUID(),"native", "COLD",true,true,true,false,false,false,true,false,10,0,0,amount,1,unit);}
    @Test void repulsionIntroducesImpactButVacuumDoesNot(){assertTrue(accepts("frost_nova","impact_force","repulsion"));assertFalse(accepts("frost_nova","impact_force","vacuum"));assertFalse(accepts("fire_bolt","impact_force","repulsion"));}
    @Test void invalidIntroducerCannotGrantCapability(){assertFalse(accepts("minor_heal","impact_force","repulsion","shatter"));assertFalse(accepts("arcane_bolt","lingering","hemorrhage"));assertFalse(accepts("fire_bolt","expanded_radius","shatter"));}
    @Test void bleedAddsOnlyItsOwnFiniteDuration(){assertFalse(f.accepts("quick_slash","lingering"));assertTrue(accepts("quick_slash","lingering","hemorrhage"));assertFalse(accepts("quick_slash","combustion","hemorrhage"));assertFalse(accepts("quick_slash","virulence","hemorrhage"));assertFalse(accepts("quick_slash","proliferation","hemorrhage"));}
    @Test void bleedDurationFivePointSixWithoutChangingInstantStrike(){var h=new Stage11HitProcTest.H("quick_slash","hemorrhage","lingering");var p=new Stage11HitProcTest.P();new HitProcRuntime(()->0).observed(h.last(),new Stage11HitProcTest.B().hit(),0,p);assertEquals(5.6,p.duration,1e-9);assertEquals(2.4,p.dps,1e-9);assertEquals(f.profiles.require("quick_slash").strike(),h.last().profile().strike());assertEquals(1.15,h.last().compiledPlan().kernelModifiers().resourceCostMultiplier());}
    @Test void nativeFiniteDurationAndIntroducedBleedEachScaleOnce(){var plain=f.profiles.require("quick_shot");var effective=f.effective("quick_shot","hemorrhage","lingering");assertEquals(plain.projectile().maximumLifetimeSeconds(),effective.projectile().maximumLifetimeSeconds());assertEquals(plain.projectile().statusSeconds(),effective.projectile().statusSeconds());}
    @Test void shatterIntroducesRadiusNotCarrierCollision(){var p=f.plan("frost_bolt","shatter","expanded_radius");assertTrue(p.radiusOnlyOnSecondary());assertEquals(3.75,HitProcRuntime.shatterRadius(p));assertFalse(p.finalTags().contains("HAS_RADIUS"));var actual=f.resolver.resolve(f.profiles.require("frost_bolt"),p);assertEquals(f.profiles.require("frost_bolt").projectile(),actual.projectile());assertEquals(90,HitProcRuntime.shatterAmount(p,hit(200,200)),1e-9);}
    @Test void concentrationIsAdditiveOnSecondaryNotAnotherMultiplier(){var p=f.plan("frost_bolt","shatter","potency","concentration");assertTrue(p.concentrationOnlyOnSecondary());assertEquals(.15,p.kernelModifiers().scalablePayloadIncreased());assertEquals(2.1,HitProcRuntime.shatterRadius(p),1e-9);assertEquals(145,HitProcRuntime.shatterAmount(p,hit(230,200)),1e-9);assertEquals(f.profiles.require("frost_bolt").projectile(),f.resolver.resolve(f.profiles.require("frost_bolt"),p).projectile());}
    @Test void missingResolvedAdditiveUnitFailsClosed(){var p=f.plan("frost_bolt","shatter","concentration");assertThrows(IllegalArgumentException.class,()->HitProcRuntime.shatterAmount(p,hit(200,Double.NaN)));}
    @Test void primaryAreaMagnitudeAlreadyContainsItsModifiers(){var p=f.plan("frost_nova","shatter","expanded_radius","concentration","repulsion");assertFalse(p.radiusOnlyOnSecondary());assertFalse(p.concentrationOnlyOnSecondary());assertFalse(p.positionOnlyOnSecondary());assertEquals(2.625,HitProcRuntime.shatterRadius(p),1e-9);assertEquals(100,HitProcRuntime.shatterAmount(p,hit(200,Double.NaN)));}
    @Test void allSixLinksRemainScopedToIntroducedShatter(){var p=f.plan("frost_bolt","shatter","repulsion","impact_force","expanded_radius","concentration","potency");assertTrue(p.impactOnlyOnSecondary());assertTrue(p.positionOnlyOnSecondary());assertEquals(.15,p.kernelModifiers().scalablePayloadIncreased());assertEquals(.5*(230+60)*.9*.9*.9,HitProcRuntime.shatterAmount(p,hit(230,200)),1e-9);assertEquals(4.375,p.positions().distance(p.geometry().impactForce()));assertEquals(f.profiles.require("frost_bolt").projectile(),f.resolver.resolve(f.profiles.require("frost_bolt"),p).projectile());}
    @Test void primaryRepulsionGetsImpactPenaltyOnce(){var p=f.effective("frost_nova","repulsion","impact_force");assertEquals(f.profiles.require("frost_nova").area().coefficient()*.9,p.area().coefficient(),1e-9);assertEquals(f.profiles.require("frost_nova").area().statusSeconds(),p.area().statusSeconds());}
    @Test void secondaryCleaveGetsImpactPenaltyWithoutChangingPrimary(){var p=f.plan("shield_bash","cleaving_edge","repulsion","impact_force");assertFalse(p.impactOnlyOnSecondary(),"Shield Bash already has native Stagger");assertEquals(f.profiles.require("shield_bash").strike().coefficient()*.9,f.resolver.resolve(f.profiles.require("shield_bash"),p).strike().coefficient(),1e-9);}
    @Test void shrapnelAlsoIntroducesConcentration(){var p=f.plan("fire_bolt","shrapnel","concentration","repulsion","impact_force","expanded_radius");assertTrue(p.concentrationOnlyOnSecondary());assertTrue(p.impactOnlyOnSecondary());assertTrue(p.radiusOnlyOnSecondary());assertEquals(f.profiles.require("fire_bolt").projectile(),f.resolver.resolve(f.profiles.require("fire_bolt"),p).projectile());}
    @Test void conversionStillRemovesShrapnelInsteadOfReaddingCarrierTags(){assertFalse(accepts("fire_bolt","shrapnel","orbit","shrapnel"));assertFalse(accepts("fire_bolt","fork","orbit","shrapnel"));}
    @Test void convertedOrbitRetainsIntroducedPushImpact(){var p=f.effective("frost_bolt","orbit","repulsion","impact_force");assertEquals(com.inigmasgames.hytalerpg.execution.connection.ConnectionProfile.Kind.ORBIT,p.connection().kind());assertEquals(f.profiles.require("frost_bolt").projectile().coefficient()*.9,p.connection().coefficient(),1e-9);}
    @Test void removingIntroducerRollsBackRatherThanSilentlyDisabling(){var actor=UUID.randomUUID();var b=f.bundle;b.service().equipSkill(actor,SkillSlot.SKILL01,new SkillId("frost_bolt"));b.service().equipPassive(actor,PassiveSlot.PASSIVE01,new PassiveId("shatter"));b.service().equipPassive(actor,PassiveSlot.PASSIVE02,new PassiveId("concentration"));assertTrue(b.service().link(actor,LinkNodeId.PASSIVE01,LinkNodeId.SKILL01).success());assertTrue(b.service().link(actor,LinkNodeId.PASSIVE02,LinkNodeId.SKILL01).success());var state=b.service().getPresentationView(actor).state();assertFalse(b.service().unlink(actor,state.linkEdges().getFirst().edgeId()).success());assertEquals(state.linkEdges(),b.service().getPresentationView(actor).state().linkEdges());}
    @Test void simultaneousIntroducersDoNotMultiplySecondaryPenaltyTwice(){var p=f.plan("frost_bolt","shatter","shrapnel","expanded_radius");assertEquals(90,HitProcRuntime.shatterAmount(p,hit(200,200)));assertTrue(p.radiusOnlyOnShrapnel());assertEquals(3.75,HitProcRuntime.shatterRadius(p));}
    @Test void sourceProfileNeverMutatesAcrossCachedVariants(){var authored=f.profiles.require("frost_bolt");var p=f.plan("frost_bolt","shatter","concentration");var q=f.plan("frost_bolt","orbit","concentration");var first=f.resolver.resolve(authored,p);var second=f.resolver.resolve(authored,q);assertEquals(authored.projectile(),first.projectile());assertNotNull(second.connection());assertSame(first,f.resolver.resolve(authored,p));assertNull(authored.connection());}
}
