package com.inigmasgames.hytalerpg;
import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.strike.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static com.inigmasgames.hytalerpg.Stage11StrikeSecondaryTest.target;

class Stage11AreaPositionIntegrationTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    final Stage11ShockwaveTest o=new Stage11ShockwaveTest();
    @Test void canonicalAreaAcceptsAndNonAreaHealRejects(){assertTrue(f.accepts("frost_nova","vacuum"));assertTrue(f.accepts("ground_slam","repulsion"));assertFalse(f.accepts("snipe","vacuum"));assertFalse(f.accepts("minor_heal","repulsion"));}
    @Test void damagingAndChillingAurasQualifyButSupportOnlyAurasDoNot(){assertTrue(f.accepts("chilling_aura","vacuum"));assertTrue(f.accepts("reaping_storm","repulsion"));assertFalse(f.accepts("emanatism","vacuum"));assertFalse(f.accepts("thorns_aura","repulsion"));}
    @Test void targetLockedConnectionsDoNotGainAreaPosition(){assertFalse(f.accepts("root_lash","vacuum"));assertFalse(f.accepts("life_drain","repulsion"));}
    @Test void modesConflictAndFailedLinkRollsBack(){var h=o.h("quick_slash","vacuum");var before=h.b.service().getPresentationView(h.actor).state().linkEdges();h.b.service().equipPassive(h.actor,PassiveSlot.PASSIVE02,new PassiveId("repulsion"));var r=h.b.service().link(h.actor,LinkNodeId.PASSIVE02,LinkNodeId.SKILL01);assertFalse(r.success());assertEquals(before,h.b.service().getPresentationView(h.actor).state().linkEdges());}
    @Test void exactlyOneDamagePenaltyPreservesCostAndCooldown(){var a=o.h("quick_slash");var b=o.h("quick_slash","vacuum");assertEquals(.9,b.last().snapshot().modifiers().factor(),1e-9);assertEquals(a.last().snapshot().resourceCost().amount(),b.last().snapshot().resourceCost().amount());assertEquals(a.last().snapshot().cooldownSeconds(),b.last().snapshot().cooldownSeconds());assertEquals(1,b.cooldownSaves);}
    @Test void originalSingleTargetAndPhantomAreNotAffectedByIntroducedAreaPosition(){var h=o.h("shield_bash","shockwave","phantom_reach","repulsion");assertTrue(h.last().compiledPlan().positionOnlyOnSecondary());assertEquals(1,h.last().snapshot().modifiers().factor());var p=new Stage11ShockwaveTest.P();p.candidates=List.of(target("other",0,0,2));o.n.run(h.last(),o.hit(100,100),p);assertEquals(60,p.delivered.stream().filter(d->d.child().secondaryKind().equals("phantom_reach")).findFirst().orElseThrow().resolved());assertEquals(36,p.delivered.stream().filter(d->d.child().secondaryKind().equals("shockwave")).findFirst().orElseThrow().resolved(),1e-9);}
    @Test void introducedCleaveDamagePenaltyIsLocal(){var h=o.h("shield_bash","cleaving_edge","vacuum");var p=new Stage11ShockwaveTest.P();p.candidates=List.of(target("other",0,0,2));o.n.run(h.last(),o.hit(100,100),p);assertEquals(1,h.last().snapshot().modifiers().factor());assertEquals(.6*.9,p.delivered.getFirst().child().snapshot().modifiers().factor(),1e-9);}
    @Test void originalAreaPenaltyIsNotAppliedTwiceToShockwave(){var h=o.h("quick_slash","shockwave","vacuum");assertFalse(h.last().compiledPlan().positionOnlyOnSecondary());assertEquals(.9,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(36,StrikeSecondaryRuntime.shockwaveAmount(h.last().compiledPlan(),o.hit(90,90).getFirst()),1e-9);}
    @Test void projectileCarrierOnlyAcceptsPositionThroughShrapnelComponent(){assertFalse(f.accepts("fire_bolt","vacuum"));var p=f.plan("fire_bolt","shrapnel","vacuum");assertTrue(p.positionOnlyOnSecondary());assertEquals("PROJECTILE",p.finalFamily());assertFalse(p.finalTags().contains("CAN_AFFECT_ENEMY_POSITION"));}
    @Test void rootLedgerIsSharedAcrossRepeatAndSecondaryWithoutChargingAgain(){var h=o.h("quick_slash","multistrike","shockwave","vacuum");var root=h.last();assertSame(root.effects().displacement(),root.multistrikeCopy(1).effects().displacement());assertSame(root.effects().displacement(),root.secondaryCopy("shockwave",1,.4).effects().displacement());assertEquals("PASS",root.effects().displacement().claim("target",1));assertEquals("ROOT_TARGET_DISPLACEMENT_ICD",root.multistrikeCopy(1).effects().displacement().claim("target",1.25));assertEquals(1,h.cooldownSaves);}
    @Test void secondaryPortsReceiveActualCleaveAndShockwaveCenters(){var h=o.h("quick_slash","cleaving_edge","shockwave","vacuum");var centers=new HashMap<String,Vec3>();var p=new Stage11ShockwaveTest.P(){@Override public void damage(SkillExecutionContext c,StrikeGeometryService.Candidate<String> t,Double amount,Vec3 center){centers.put(c.secondaryKind(),center);super.damage(c,t,amount);}};p.candidates=List.of(target("other",0,0,2));o.n.run(h.last(),o.hit(100,100),p);assertEquals(Vec3.ZERO,centers.get("cleaving_edge"));assertEquals(new Vec3(0,0,1),centers.get("shockwave"));}
    @Test void impactAmplifiesOnlyPushNotPull(){assertEquals(2,new PositionModifiers(true,false).distance(true));assertEquals(4.375,new PositionModifiers(false,true).distance(true));assertThrows(IllegalArgumentException.class,()->new PositionModifiers(true,true));}
    @Test void sourceComponentRemovalCannotLeaveSilentlyInertPositionPassive(){var h=o.h("shield_bash","shockwave","vacuum");var edges=h.b.service().getPresentationView(h.actor).state().linkEdges();var id=edges.stream().filter(e->e.sourceNodeId()==LinkNodeId.PASSIVE01).findFirst().orElseThrow().edgeId();assertFalse(h.b.service().unlink(h.actor,id).success());assertEquals(edges,h.b.service().getPresentationView(h.actor).state().linkEdges());}
}
