package com.inigmasgames.hytalerpg;

import com.google.gson.*;
import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.progress.*;
import com.inigmasgames.hytalerpg.links.*;
import java.util.*;
import java.nio.file.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

class Stage11InactivePassiveRecoveryTest {
    @TempDir Path temporary;
    final Stage01BTestSupport.InMemoryRepository repo=new Stage01BTestSupport.InMemoryRepository();
    RpgPlayerState state(String skill,String... passives){
        var s=RpgPlayerState.create(UUID.randomUUID());s.skill(SkillSlot.SKILL01,new SkillId(skill));s.learnedSkills.add(skill);
        var edges=new ArrayList<LinkEdge>();for(int i=0;i<passives.length;i++){
            var slot=PassiveSlot.values()[i];s.passive(slot,new PassiveId(passives[i]));s.ownedPassives.merge(passives[i],1,Integer::sum);
            edges.add(LinkEdge.create(LinkNodeId.valueOf(slot.name()),LinkNodeId.SKILL01));
        }
        s.linkEdges(edges);s.level=12;s.currentXp=4567;s.skillMastery.put(skill,55L);return s;
    }
    Stage01BTestSupport.Bundle bundle(RpgPlayerState s){repo.states.put(s.playerUuid(),s.copy());return reopen();}
    Stage01BTestSupport.Bundle reopen(){return Stage01BTestSupport.bundle(repo,new Stage01BTestSupport.RecordingTracer());}
    @Test void invalidForkPreservesGraphOwnedCopiesAndProgress(){var s=state("quick_slash","fork","potency");var b=bundle(s);var v=b.service().getLoadout(s.playerUuid());assertEquals(s.linkEdges(),v.state().linkEdges());assertEquals(s.ownedPassives,v.state().ownedPassives);assertEquals(s.skillMastery,v.state().skillMastery);assertEquals(4567,v.state().currentXp);assertEquals(12,v.state().level);assertTrue(v.state().inactive(PassiveSlot.PASSIVE01));assertFalse(v.state().inactive(PassiveSlot.PASSIVE02));assertEquals(List.of(new PassiveId("potency")),v.plans().get(SkillSlot.SKILL01).passiveOrder());assertTrue(v.format(b.catalog()).contains("[INACTIVE:"));assertTrue(v.warnings().stream().anyMatch(w->w.startsWith("INACTIVE passive01:")));}
    @Test void validForkAndUnrelatedSlotRemainActive(){var s=state("fire_bolt","fork","potency");var b=bundle(s);var v=b.service().getPresentationView(s.playerUuid());assertTrue(v.state().inactivePassives.isEmpty());assertEquals(2,v.plans().get(SkillSlot.SKILL01).passiveOrder().size());assertEquals(0,repo.saves);}
    @Test void recoveryIsIdempotentAcrossRestart(){var s=state("quick_slash","fork","potency");bundle(s).service().getLoadout(s.playerUuid());int saves=repo.saves;long revision=repo.states.get(s.playerUuid()).revision;var again=reopen().service().getLoadout(s.playerUuid());assertEquals(saves,repo.saves);assertEquals(revision,again.state().revision);assertEquals(1,again.state().inactivePassives.size());}
    @Test void maximalSubsetRetainsIntroducedDependencyTogether(){var s=state("frost_bolt","concentration","expanded_radius","shatter","hemorrhage","potency");var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals(Set.of("passive04"),v.state().inactivePassives.keySet());assertEquals(4,v.plans().get(SkillSlot.SKILL01).passiveOrder().size());assertTrue(v.plans().get(SkillSlot.SKILL01).concentrationOnlyOnSecondary());}
    @Test void repeatConflictKeepsFirstSlotAndMarksSecond(){var s=state("fire_bolt","echo","barrage","potency");var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals(Set.of("passive02"),v.state().inactivePassives.keySet());assertTrue(v.state().inactivePassives.get("passive02").startsWith("CONFLICTING_MODIFIER:"));assertEquals(s.linkEdges(),v.state().linkEdges());}
    @Test void duplicateCopiesRemainOwnedButOnlyOneContributes(){var s=state("fire_bolt","potency","potency");var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals(2,v.state().ownedPassives.get("potency"));assertEquals(Set.of("passive02"),v.state().inactivePassives.keySet());assertEquals(.15,v.plans().get(SkillSlot.SKILL01).kernelModifiers().scalablePayloadIncreased());}
    @Test void missingPassiveDefinitionBecomesInactiveWithoutDeletion(){var s=state("fire_bolt","missing_future_passive","potency");var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals("missing_future_passive",v.state().equippedPassives[0]);assertTrue(v.state().inactivePassives.get("passive01").startsWith("UNKNOWN_PASSIVE:"));assertEquals(s.linkEdges(),v.state().linkEdges());assertEquals(1,v.plans().get(SkillSlot.SKILL01).passiveOrder().size());}
    @Test void missingUnlinkedDefinitionIsStillVisibleAndOwned(){var s=state("fire_bolt","missing_future_passive");s.linkEdges(List.of());var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals("UNKNOWN_PASSIVE",v.state().inactivePassives.get("passive01"));assertEquals(1,v.state().ownedPassives.get("missing_future_passive"));}
    @Test void missingSkillGetsDegradedPlanNotInventedExecution(){var s=state("missing_future_skill","potency");var v=bundle(s).service().getLoadout(s.playerUuid());assertTrue(v.plans().get(SkillSlot.SKILL01).degraded());assertTrue(v.state().inactivePassives.get("passive01").startsWith("UNKNOWN_SKILL:"));assertEquals(s.linkEdges(),v.state().linkEdges());}
    @Test void unchangedInactiveNodeDoesNotBlockUnrelatedEdit(){var s=state("quick_slash","fork","potency");var b=bundle(s);b.service().getLoadout(s.playerUuid());assertTrue(b.service().equipSkill(s.playerUuid(),SkillSlot.SKILL02,new SkillId("fire_bolt")).success());assertTrue(b.service().getLoadout(s.playerUuid()).state().inactive(PassiveSlot.PASSIVE01));}
    @Test void explicitRelinkMustValidateAndCannotKeepInactiveBypass(){var s=state("quick_slash","fork");var b=bundle(s);var before=b.service().getLoadout(s.playerUuid()).state();var result=b.service().link(s.playerUuid(),LinkNodeId.PASSIVE01,LinkNodeId.SKILL01);assertFalse(result.success());assertEquals(before.revision,b.service().getLoadout(s.playerUuid()).state().revision);assertEquals(before.linkEdges(),b.service().getLoadout(s.playerUuid()).state().linkEdges());}
    @Test void explicitValidRelinkReactivatesNode(){var s=state("quick_slash","fork");s.skill(SkillSlot.SKILL02,new SkillId("fire_bolt"));var b=bundle(s);b.service().getLoadout(s.playerUuid());assertTrue(b.service().link(s.playerUuid(),LinkNodeId.PASSIVE01,LinkNodeId.SKILL02).success());var v=b.service().getLoadout(s.playerUuid());assertTrue(v.state().inactivePassives.isEmpty());assertEquals(1,v.plans().get(SkillSlot.SKILL02).projectileModifiers().fork());}
    @Test void newInvalidLinkAlwaysRollsBackNotAutoInactivated(){var s=state("quick_slash","potency");var b=bundle(s);assertTrue(b.service().equipPassive(s.playerUuid(),PassiveSlot.PASSIVE02,new PassiveId("fork")).success());long before=b.service().getLoadout(s.playerUuid()).state().revision;assertFalse(b.service().link(s.playerUuid(),LinkNodeId.PASSIVE02,LinkNodeId.SKILL01).success());var v=b.service().getLoadout(s.playerUuid());assertEquals(before,v.state().revision);assertTrue(v.state().inactivePassives.isEmpty());}
    @Test void explicitReplacementReactivatesAndValidates(){var s=state("quick_slash","fork");var b=bundle(s);b.service().getLoadout(s.playerUuid());assertTrue(b.service().equipPassive(s.playerUuid(),PassiveSlot.PASSIVE01,new PassiveId("potency")).success());assertTrue(b.service().getLoadout(s.playerUuid()).state().inactivePassives.isEmpty());}
    @Test void changingDestinationSkillRevalidatesInactiveRoute(){var s=state("quick_slash","fork");var b=bundle(s);b.service().getLoadout(s.playerUuid());assertTrue(b.service().equipSkill(s.playerUuid(),SkillSlot.SKILL01,new SkillId("fire_bolt")).success());assertTrue(b.service().getLoadout(s.playerUuid()).state().inactivePassives.isEmpty());}
    @Test void unlinkDoesNotDeleteOwnedOrEquippedPassive(){var s=state("quick_slash","fork");var b=bundle(s);b.service().getLoadout(s.playerUuid());assertTrue(b.service().unlinkSource(s.playerUuid(),LinkNodeId.PASSIVE01).success());var v=b.service().getLoadout(s.playerUuid());assertEquals("fork",v.state().equippedPassives[0]);assertEquals(1,v.state().ownedPassives.get("fork"));assertTrue(v.state().inactivePassives.isEmpty());}
    @Test void recoveryFailureDoesNotPublishHalfRecoveredMemory(){var s=state("quick_slash","fork");var b=bundle(s);repo.failSave=true;assertThrows(IllegalStateException.class,()->b.service().getLoadout(s.playerUuid()));assertTrue(repo.states.get(s.playerUuid()).inactivePassives.isEmpty());repo.failSave=false;assertTrue(b.service().getLoadout(s.playerUuid()).state().inactive(PassiveSlot.PASSIVE01));}
    @Test void staleInactiveFlagsReconcileAgainstCurrentCatalog(){var s=state("fire_bolt","fork");s.inactivePassives.put("passive01","OLD_UNSUPPORTED_BUILD");var v=bundle(s).service().getLoadout(s.playerUuid());assertTrue(v.state().inactivePassives.isEmpty());assertEquals(1,v.plans().get(SkillSlot.SKILL01).projectileModifiers().fork());}
    @Test void readModelCannotMutateAuthoritativeFlags(){var s=state("quick_slash","fork");var b=bundle(s);var v=b.service().getLoadout(s.playerUuid());v.state().inactivePassives.clear();assertTrue(b.service().getLoadout(s.playerUuid()).state().inactive(PassiveSlot.PASSIVE01));}
    @Test void structuralCycleStillUsesExistingBackupRecovery(){var s=state("fire_bolt","potency");s.linkEdges(List.of(LinkEdge.create(LinkNodeId.PASSIVE01,LinkNodeId.JOINT01),LinkEdge.create(LinkNodeId.JOINT01,LinkNodeId.JOINT02),LinkEdge.create(LinkNodeId.JOINT02,LinkNodeId.JOINT01)));var v=bundle(s).service().getLoadout(s.playerUuid());assertTrue(v.state().linkEdges().isEmpty());assertEquals(s.ownedPassives,v.state().ownedPassives);assertTrue(v.warnings().stream().anyMatch(w->w.contains("GRAPH_RECOVERED")));}
    @Test void sixNodeRecoveryPreservesMostValidRatherThanGreedyFirst(){var s=state("fire_bolt","orbit","fork","chain","return","homing","potency");var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals(Set.of("passive01"),v.state().inactivePassives.keySet());assertEquals(5,v.plans().get(SkillSlot.SKILL01).passiveOrder().size());}
    @Test void jointRoutingPreservedWithOneInactiveInput(){var s=state("quick_slash","fork","potency");s.linkEdges(List.of(LinkEdge.create(LinkNodeId.PASSIVE01,LinkNodeId.JOINT01),LinkEdge.create(LinkNodeId.PASSIVE02,LinkNodeId.JOINT01),LinkEdge.create(LinkNodeId.JOINT01,LinkNodeId.SKILL01)));var v=bundle(s).service().getLoadout(s.playerUuid());assertEquals(s.linkEdges(),v.state().linkEdges());assertEquals(List.of(LinkNodeId.JOINT01,LinkNodeId.SKILL01),v.routes().get(PassiveSlot.PASSIVE01));assertEquals(1,v.plans().get(SkillSlot.SKILL01).passiveOrder().size());}
    @Test void schemaSixMigrationPreservesCooldownAndAllGraphData(){var s=state("fire_bolt","fork");var g=new Gson();var old=g.toJsonTree(s).getAsJsonObject();old.addProperty("schemaVersion",6);old.remove("inactivePassives");var next=new RpgStateMigrator().migrate(old);assertEquals(7,next.targetVersion());assertEquals(old.get("graphEdges"),next.state().get("graphEdges"));assertEquals(old.get("cooldowns"),next.state().get("cooldowns"));assertTrue(next.state().getAsJsonObject("inactivePassives").isEmpty());assertFalse(old.has("inactivePassives"));}
    @Test void migrationCheckpointSurvivesLaterContentSave()throws Exception{var s=state("quick_slash","fork");var g=new Gson();var old=g.toJsonTree(s).getAsJsonObject();old.addProperty("schemaVersion",6);old.remove("inactivePassives");var repository=new FileRpgPlayerStateRepository(temporary);String raw=g.toJson(old);Files.writeString(repository.path(s.playerUuid()),raw);var loaded=repository.load(s.playerUuid());var b=Stage01BTestSupport.bundle();new InactivePassiveRecovery(b.catalog(),b.compiler(),b.graph()).reconcile(loaded.state());repository.save(loaded.state());Path checkpoint=temporary.resolve(s.playerUuid()+".json.schema-v6.bak");assertEquals(raw,Files.readString(checkpoint));assertTrue(repository.load(s.playerUuid()).state().inactive(PassiveSlot.PASSIVE01));}
    @Test void malformedInactiveStateFailsClosed(){var s=state("fire_bolt");s.inactivePassives.put("passive99","bad");assertThrows(RuntimeException.class,s::normalizeShape);s.inactivePassives.clear();s.inactivePassives.put("passive01","");assertThrows(IllegalStateException.class,s::normalizeShape);}
}
