package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.strike.*;
import com.inigmasgames.hytalerpg.combat.attribute.RpgAttribute;
import com.inigmasgames.hytalerpg.combat.resource.ResourceType;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

/** Deterministic RPG structure/cadence fixtures, not native input, animation or action-lock proof. */
class Stage11StrikeCadenceTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    Stage11ResourcePassivesTest.H h(String... passives){var h=new Stage11ResourcePassivesTest.H("quick_slash");for(int i=0;i<passives.length;i++)h.link(passives[i],PassiveSlot.values()[i]);return h;}
    @Test void multistrikePositiveAndAuthoredSequenceReactionNegativeGates(){assertTrue(f.accepts("quick_slash","multistrike"));for(String s:List.of("dagger_flurry","whirlwind","riposte","fire_bolt","managuard"))assertFalse(f.accepts(s,"multistrike"),s);}
    @Test void ruthlessPositiveAndTwoNegativeGates(){assertTrue(f.accepts("heavy_swing","ruthless"));assertTrue(f.accepts("shield_bash","ruthless"));assertFalse(f.accepts("managuard","ruthless"));assertFalse(f.accepts("fire_bolt","ruthless"));assertFalse(f.accepts("riposte","ruthless"));}
    @Test void singleRepeatControllerAndCopyLimitsStillApply(){var h=h("multistrike");h.b.service().equipPassive(h.actor,PassiveSlot.PASSIVE02,new PassiveId("multistrike"));assertFalse(h.b.service().link(h.actor,LinkNodeId.PASSIVE02,LinkNodeId.SKILL01).success());}
    @Test void profileUsesThreeHitsAndQuarterSecondCadenceWithoutChangingCanonical(){var p=f.effective("quick_slash","multistrike");assertEquals(3,p.strike().repeats());assertEquals(.25,p.strike().repeatIntervalSeconds());assertEquals(.85,p.strike().coefficient());assertEquals(1,f.profiles.require("quick_slash").strike().repeats());assertEquals(.8,p.cooldownSeconds());assertEquals(5,p.resourceCost());}
    @Test void resolverCacheDoesNotCrossContaminateOtherPlans(){var p=f.plan("quick_slash","multistrike");var a=f.resolver.resolve(f.profiles.require("quick_slash"),p);assertSame(a,f.resolver.resolve(f.profiles.require("quick_slash"),p));assertEquals(1,f.effective("quick_slash").strike().repeats());assertNotEquals(p.planHash(),f.plan("quick_slash","ruthless").planHash());}
    @Test void committedPrimaryFullAndExactlyTwoDerivedChildrenAtSixtyFivePercent(){var h=h("multistrike");assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());var c=h.last();assertEquals(1,c.snapshot().modifiers().factor(),1e-9);for(int i=1;i<=2;i++){var child=c.multistrikeCopy(i);assertEquals(.65,child.snapshot().modifiers().factor(),1e-9);assertEquals(c.rootCastId(),child.rootCastId());assertEquals(c.request().correlationId(),child.request().correlationId());assertNotEquals(c.skillInstanceId(),child.skillInstanceId());assertEquals(child.skillInstanceId(),child.snapshot().skillInstanceId());assertTrue(child.derivedRelease());assertEquals(i,child.multistrikeIndex());assertSame(c.leechBudget(),child.leechBudget());assertSame(c.target(),child.target());}}
    @Test void repeatsCannotRecursivelyRepeatEchoOrBarrage(){var h=h("multistrike");h.cast();var child=h.last().multistrikeCopy(1);assertThrows(IllegalStateException.class,()->child.multistrikeCopy(2));assertThrows(IllegalStateException.class,child::echoCopy);assertThrows(IllegalStateException.class,()->child.barrageCopy(1));assertThrows(IllegalStateException.class,()->h.last().multistrikeCopy(0));assertThrows(IllegalStateException.class,()->h.last().multistrikeCopy(3));}
    @Test void unlinkedContextCannotCreateMultistrikeChildren(){var h=h();h.cast();assertThrows(IllegalStateException.class,()->h.last().multistrikeCopy(1));}
    @Test void snapshotCopyPreservesRepeatIdentityAndSharedLeechCap(){var h=h("multistrike","leeching");h.cast();var child=h.last().multistrikeCopy(2);var copied=child.withSnapshot(child.snapshot().withMagnitudeFactor(.5));assertEquals(2,copied.multistrikeIndex());assertEquals(.325,copied.snapshot().modifiers().factor(),1e-9);assertSame(child.leechBudget(),copied.leechBudget());}
    @Test void cadenceIsAtQuarterAndHalfSecondWithNoDuplicateClaim(){var s=new StrikeRepeatSchedule(3,.25,0);assertTrue(s.claimDue(249_999_999).isEmpty());assertEquals(1,s.claimDue(250_000_000).orElseThrow());assertTrue(s.claimDue(250_000_000).isEmpty());assertFalse(s.complete());assertEquals(2,s.claimDue(500_000_000).orElseThrow());assertTrue(s.complete());assertTrue(s.claimDue(999_999_999).isEmpty());}
    @Test void finiteSequenceLateWorldTickGuardAndMonotonicOrigin(){var s=new StrikeRepeatSchedule(3,.25,20_000_000_000L);assertFalse(s.exceededMaximumAge(21_000_000_000L,1));assertTrue(s.exceededMaximumAge(21_000_000_001L,1));assertTrue(s.claimDue(19_000_000_000L).isEmpty());assertThrows(IllegalArgumentException.class,()->new StrikeRepeatSchedule(0,.25,0));}
    @Test void rootActionLockRejectsOtherCastUntilExplicitFinalTermination(){var h=h("multistrike");h.b.service().equipSkill(h.actor,SkillSlot.SKILL02,new SkillId("quick_slash"));h.cast();assertEquals(95,h.current(ResourceType.STAMINA));h.kernel.cooldowns().clear(h.actor,"quick_slash");assertEquals("INCOMPATIBLE_ACTIVE_STATE",h.cast(SkillSlot.SKILL02,SkillExecutionRequest.Origin.MANUAL).code());assertEquals(95,h.current(ResourceType.STAMINA));h.service.terminate(h.last(),"FIXTURE_LAST_REPEAT");assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(90,h.current(ResourceType.STAMINA));}
    @Test void derivedChildrenNeverChargeResourcesOrStartAnotherCooldown(){var h=h("multistrike");h.cast();double cd=h.kernel.cooldowns().remaining(h.actor,"quick_slash");h.last().multistrikeCopy(1);h.last().multistrikeCopy(2);assertEquals(95,h.current(ResourceType.STAMINA));assertTrue(h.kernel.cooldowns().remaining(h.actor,"quick_slash")<=cd);assertEquals(1,h.cooldownSaves);assertEquals(1,h.contexts.size());}
    @Test void repeatedHitLedgersAreIndependentAndCannotDoubleClaim(){var ledger=new SkillHitLedger();assertTrue(ledger.accept("root",0,"victim"));assertFalse(ledger.accept("root",0,"victim"));assertTrue(ledger.accept("root/multistrike-1",0,"victim"));assertTrue(ledger.accept("root/multistrike-2",0,"victim"));ledger.clear("root/multistrike-1");}
    @Test void everyThirdManualRootCommitIncludingMissIsEmpowered(){var h=h("ruthless");for(int i=1;i<=9;i++){assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(i%3==0?1.6:1,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(i%3==2,h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.ready();}}
    @Test void increasedDamageAddsToPotencyNotAnotherSixtyPercentMore(){var h=h("ruthless","potency");for(int i=0;i<3;i++){h.cast();if(i<2)h.ready();}assertEquals(1.75,h.last().snapshot().modifiers().factor(),1e-9);}
    @Test void thirdMultistrikeChildrenInheritEmpowermentWithoutAdvancingCadence(){var h=h("ruthless","multistrike");for(int i=0;i<3;i++){h.cast();if(i<2)h.ready();}assertEquals(1.6,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(1.04,h.last().multistrikeCopy(1).snapshot().modifiers().factor(),1e-9);assertEquals(1.04,h.last().multistrikeCopy(2).snapshot().modifiers().factor(),1e-9);assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));assertEquals(85,h.current(ResourceType.STAMINA));}
    @Test void empoweredStaggerScalesExistingPayloadBeforeCapsWithoutInventingOne(){var p=f.effective("shield_bash","ruthless");assertEquals(.9,CompiledProfileResolver.ruthless(p,true).strike().statusSeconds(),1e-9);assertSame(p,CompiledProfileResolver.ruthless(p,false));var blank=f.effective("heavy_swing","ruthless");assertSame(blank,CompiledProfileResolver.ruthless(blank,true));assertEquals(0,blank.strike().statusSeconds());}
    @Test void impactAndRuthlessScaleAuthoredStaggerOnceEach(){var p=f.effective("shield_bash","ruthless","impact_force");assertEquals(.6*1.75*1.5,CompiledProfileResolver.ruthless(p,true).strike().statusSeconds(),1e-9);assertEquals(.7*.9,p.strike().coefficient(),1e-9);}
    @Test void cooldownAndResourceFailuresDoNotAdvanceRuthless(){var h=h("ruthless");h.cast();assertEquals("COOLDOWN_ACTIVE",h.cast().code());assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.ready();h.current.put(ResourceType.STAMINA,0d);assertEquals("INSUFFICIENT_RESOURCE",h.cast().code());assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));}
    @Test void failedCooldownPersistenceDoesNotConsumeThirdUse(){var h=h("ruthless");for(int i=0;i<2;i++){h.cast();h.ready();}h.failCooldown=true;assertEquals(SkillExecutionResult.Status.REJECTED,h.cast().status());assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));assertEquals(90,h.current(ResourceType.STAMINA));}
    @Test void paidHealthDispatchFailureStillConsumesEmpoweredCommittedUse(){var h=h("ruthless","lifeblood");for(int i=0;i<2;i++){h.cast();h.ready();}h.failDispatch=true;assertEquals(SkillExecutionResult.Status.TERMINATED,h.cast().status());assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));assertEquals(76,h.current(ResourceType.HEALTH));}
    @Test void paidNormalDispatchFailureConsumesEmpoweredCommittedUse(){var h=h("ruthless");for(int i=0;i<2;i++){h.cast();h.ready();}h.failDispatch=true;assertEquals(SkillExecutionResult.Status.TERMINATED,h.cast().status());assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));assertEquals(85,h.current(ResourceType.STAMINA));assertEquals("COOLDOWN_ACTIVE",h.cast().code());}
    @Test void triggeredRootNeitherConsumesNorReceivesThirdManualUse(){var h=h("ruthless");for(int i=0;i<2;i++){h.cast();h.ready();}h.cast(SkillSlot.SKILL01,SkillExecutionRequest.Origin.TRIGGERED);assertEquals(1,h.last().snapshot().modifiers().factor(),1e-9);assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.ready();h.cast();assertEquals(1.6,h.last().snapshot().modifiers().factor(),1e-9);}
    @Test void noExpiryButLoadoutChangeResetsCadence(){var h=h("ruthless");for(int i=0;i<2;i++){h.cast();h.ready();}h.time=10000;assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.b.service().setDevelopmentAttribute(h.actor,RpgAttribute.STR,20);assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.b.service().equipSkill(h.actor,SkillSlot.SKILL02,new SkillId("heavy_swing"));assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));}
    @Test void failedLoadoutSaveAndOrdinaryInterruptDoNotClearPriorCommits(){var h=h("ruthless");for(int i=0;i<2;i++){h.cast();h.ready();}h.service.cancel(h.actor,"FIXTURE_INTERRUPT");assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.b.repository().failSave=true;assertFalse(h.b.service().unequipSkill(h.actor,SkillSlot.SKILL01).success());assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));h.service.forgetPassiveState(h.actor);assertFalse(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));}
    @Test void windupInterruptedBeforeCommitDoesNotAdvanceCounter(){var h=new Stage11ResourcePassivesTest.H("heavy_swing");h.link("ruthless",PassiveSlot.PASSIVE01);for(int i=0;i<2;i++){assertEquals(SkillExecutionResult.Status.PENDING,h.cast().status());h.service.completeWindup(h.actor,h);h.ready();}h.cast();h.service.cancel(h.actor,"FIXTURE_DAMAGE_INTERRUPT");assertTrue(h.service.nextRuthless(h.actor,SkillSlot.SKILL01));assertEquals(2,h.contexts.size());}
    @Test void ledgerSeparatesActorsSlotsAndDeduplicatesLatestRoot(){var l=new RuthlessLedger();var actor=UUID.randomUUID();var k=new RuthlessLedger.Key(actor,SkillSlot.SKILL01);l.committed(k,"a");l.committed(k,"a");assertFalse(l.nextEmpowered(k));l.committed(k,"b");assertTrue(l.nextEmpowered(k));assertFalse(l.nextEmpowered(new RuthlessLedger.Key(actor,SkillSlot.SKILL02)));assertFalse(l.nextEmpowered(new RuthlessLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01)));l.committed(k,"c");assertFalse(l.nextEmpowered(k));}
    @Test void staleRollbackCannotEraseNewCommitOrRestoreClearedOwner(){var l=new RuthlessLedger();var k=new RuthlessLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);var first=l.committed(k,"a");l.committed(k,"b");l.rollback(first);assertTrue(l.nextEmpowered(k));var last=l.committed(k,"c");l.forget(k.actor());l.rollback(last);assertEquals(0,l.size());}
    @Test void ledgerBoundIsExplicitAndOwnerCleanupReleasesCapacity(){var l=new RuthlessLedger();RuthlessLedger.Key first=null;for(int i=0;i<4096;i++){var k=new RuthlessLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);if(first==null)first=k;l.committed(k,"root");}var extra=new RuthlessLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);assertFalse(l.hasCapacity(extra));assertThrows(IllegalStateException.class,()->l.committed(extra,"root"));l.forget(first.actor());assertTrue(l.hasCapacity(extra));assertThrows(IllegalArgumentException.class,()->l.committed(extra," "));}
}
