package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.combat.*;
import com.inigmasgames.hytalerpg.combat.attribute.RpgAttribute;
import com.inigmasgames.hytalerpg.combat.cooldown.*;
import com.inigmasgames.hytalerpg.combat.power.ItemPowerDescriptor;
import com.inigmasgames.hytalerpg.combat.resource.*;
import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11ResourcePassivesTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    static class H implements SkillExecutionPort,NativeResourcePort {
        final UUID actor=UUID.randomUUID(); final Stage01BTestSupport.Bundle b=Stage01BTestSupport.bundle();
        final RpgCombatKernel kernel=RpgCombatKernel.createProduction();
        final SkillExecutionService service; final EnumMap<ResourceType,Double> current=new EnumMap<>(ResourceType.class);
        final List<SkillExecutionContext> contexts=new ArrayList<>();double time;String weapon="LONGSWORD";int sequence,healthWrites,cooldownSaves;boolean failDispatch,failCooldown,alive=true;
        H(String skill){
            current.put(ResourceType.HEALTH,100d);current.put(ResourceType.MANA,100d);current.put(ResourceType.STAMINA,100d);
            assertTrue(b.service().equipSkill(actor,SkillSlot.SKILL01,new SkillId(skill)).success());
            kernel.cooldowns().bindPersistence(new RpgCooldownService.Persistence(){
                public Map<String,SavedCooldown> load(UUID id){return Map.of();}
                public void save(UUID id,Map<String,SavedCooldown> values){if(failCooldown)throw new IllegalStateException("fixture cooldown save failure");cooldownSaves++;}
            });
            service=new SkillExecutionService(b.service(),Stage04SkillProfiles.loadCanonical(b.catalog()),kernel,SkillExecutorRegistry.stage04(),new SkillInstanceLifecycle(),b.tracer(),()->(long)(time*1e9));
        }
        void link(String id,PassiveSlot slot){assertTrue(b.service().equipPassive(actor,slot,new PassiveId(id)).success());var r=b.service().link(actor,LinkNodeId.valueOf(slot.name()),LinkNodeId.SKILL01);assertTrue(r.success(),r.toString());}
        SkillExecutionResult cast(){return cast(SkillSlot.SKILL01,SkillExecutionRequest.Origin.MANUAL);}
        SkillExecutionResult cast(SkillSlot slot,SkillExecutionRequest.Origin origin){return service.request(new SkillExecutionRequest(actor,slot,"Ability2",++sequence,"resource-passive-"+sequence,Vec3.FORWARD,origin),this);}
        SkillExecutionContext last(){return contexts.getLast();}
        void ready(){if(!contexts.isEmpty())service.terminate(last(),"FIXTURE_COMPLETE");kernel.cooldowns().clear(actor,last().profile().skillId());time+=.5;}
        public boolean actorAliveAndUsable(){return alive;}
        public Equipment equipment(){return new Equipment(new Item("fixture",weapon,new ItemPowerDescriptor("fixture",Set.of(weapon),20d,20d)),null);}
        public NativeResourcePort resources(){return this;}
        public Validation familyPrerequisites(Stage04SkillProfile p,CompiledSkillPlan plan){return Validation.pass();}
        public CommittedTarget captureTarget(Stage04SkillProfile p,CompiledSkillPlan plan,SkillExecutionRequest r){return new CommittedTarget(actor,Vec3.ZERO,Vec3.ZERO,Vec3.FORWARD,actor);}
        public Validation validateRelease(SkillExecutionContext c){return Validation.pass();}
        SkillExecutionResult dispatch(SkillExecutionContext c){contexts.add(c);if(failDispatch)throw new IllegalStateException("fixture dispatch failure");return SkillExecutionResult.committed("FIXTURE_MISS",0,0);}
        public SkillExecutionResult executeStrike(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeMovement(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeReaction(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeProjectile(SkillExecutionContext c){return dispatch(c);}
        public double current(ResourceType type){return current.getOrDefault(type,0d);}
        public double maximum(ResourceType type){return 100;}
        public void setCurrent(ResourceType type,double value){if(type==ResourceType.HEALTH)healthWrites++;current.put(type,value);}
    }
    @Test void lifebloodPositiveAndTwoNegativeGates(){assertTrue(f.accepts("quick_slash","lifeblood"));assertFalse(f.accepts("void_beam","lifeblood"));assertFalse(f.accepts("riposte","lifeblood"));assertFalse(f.accepts("managuard","lifeblood"));}
    @Test void attunementPositiveAndTwoNegativeGates(){assertTrue(f.accepts("quick_slash","attunement"));assertFalse(f.accepts("managuard","attunement"));assertFalse(f.accepts("void_beam","attunement"));}
    @Test void healthCostCeilsOnlyAtFinalBoundary(){var resources=RpgCombatKernel.createProduction().resources();var p=f.plan("quick_slash","lifeblood","efficiency");assertEquals(new ResourceCost(ResourceType.HEALTH,7),resources.evaluateActivation(new ResourceCost(ResourceType.STAMINA,5),p,0));assertEquals(.1,p.kernelModifiers().scalablePayloadIncreased());}
    @Test void attunementStacksAreAdditiveAndComposeWithOtherCostFactors(){var r=RpgCombatKernel.createProduction().resources();var p=f.plan("quick_slash","attunement","efficiency","overcharge");assertEquals(87,r.evaluateActivation(new ResourceCost(ResourceType.STAMINA,100),p,5).amount());assertEquals(1-.03*5,.85,1e-9);}
    @Test void noZeroOrMixedHealthUpkeepAndNoHealthRegeneration(){var h=new H("quick_slash");var p=f.plan("quick_slash","lifeblood");assertThrows(IllegalArgumentException.class,()->h.kernel.resources().evaluateActivation(ResourceCost.NONE,p,0));assertThrows(IllegalArgumentException.class,()->h.kernel.resources().evaluateUpkeep(new ResourceCost(ResourceType.HEALTH,1),p.kernelModifiers()));assertEquals(0,h.kernel.resources().regenerate(h.actor,ResourceType.HEALTH,100,h));assertEquals(0,h.healthWrites);}
    @Test void actualSharedQuickSlashCommitSpendsOnlyHealthOnce(){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(92,h.current(ResourceType.HEALTH));assertEquals(100,h.current(ResourceType.STAMINA));assertEquals(100,h.current(ResourceType.MANA));assertEquals(1,h.healthWrites);assertEquals(1.1,h.last().snapshot().modifiers().factor(),1e-9);assertEquals("COOLDOWN_ACTIVE",h.cast().code());assertEquals(1,h.healthWrites);}
    @Test void exactOneHealthRemainingAllowed(){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);h.current.put(ResourceType.HEALTH,9d);assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(1,h.current(ResourceType.HEALTH));}
    @Test void lethalAndFractionalBelowOneCasesRejectWithoutMutation(){for(double hp:new double[]{0,1,7,8,8.1,8.9999,Double.NaN,Double.POSITIVE_INFINITY}){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);h.current.put(ResourceType.HEALTH,hp);assertEquals("INSUFFICIENT_RESOURCE",h.cast().code(),"HP="+hp);assertEquals(0,h.healthWrites);assertTrue(h.contexts.isEmpty());assertEquals(0,h.kernel.cooldowns().remaining(h.actor,"quick_slash"));}}
    @Test void changeBetweenReservationAndCommitRechecksHealth(){var h=new H("quick_slash");var r=h.kernel.resources();var token=r.reserveCost(h.actor,new ResourceCost(ResourceType.HEALTH,8),h);h.current.put(ResourceType.HEALTH,8.5);assertThrows(IllegalStateException.class,()->r.commitCost(token,h));assertEquals(0,h.healthWrites);assertTrue(r.refundIfUncommitted(token));}
    @Test void pendingHealthCostsCannotTogetherBecomeLethal(){var h=new H("quick_slash");h.current.put(ResourceType.HEALTH,16d);var r=h.kernel.resources();var t=r.reserveCost(h.actor,new ResourceCost(ResourceType.HEALTH,8),h);assertFalse(r.canAfford(h.actor,new ResourceCost(ResourceType.HEALTH,8),h));r.commitCost(t,h);assertEquals(8,h.current(ResourceType.HEALTH));r.finish(t);}
    @Test void failedCooldownSaveRollsBackHealthBeforeAnyExecutor(){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);h.link("attunement",PassiveSlot.PASSIVE02);h.failCooldown=true;assertEquals(SkillExecutionResult.Status.REJECTED,h.cast().status());assertEquals(100,h.current(ResourceType.HEALTH));assertTrue(h.contexts.isEmpty());assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void lateHealthDispatchErrorKeepsCostAndCooldownBecauseHitCannotBeRuledOut(){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);h.link("attunement",PassiveSlot.PASSIVE02);h.failDispatch=true;assertEquals(SkillExecutionResult.Status.TERMINATED,h.cast().status());assertEquals(92,h.current(ResourceType.HEALTH));assertTrue(h.kernel.cooldowns().remaining(h.actor,"quick_slash")>0);assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void incompatibleLeechingLinkRollsBackGraphAndRetainsOwnedCopy(){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);assertTrue(h.b.service().equipPassive(h.actor,PassiveSlot.PASSIVE02,new PassiveId("leeching")).success());var before=h.b.service().getPresentationView(h.actor);var r=h.b.service().link(h.actor,LinkNodeId.PASSIVE02,LinkNodeId.SKILL01);assertFalse(r.success());assertEquals(before.state().linkEdges(),h.b.service().getPresentationView(h.actor).state().linkEdges());assertEquals("leeching",h.b.service().getPresentationView(h.actor).state().passive(PassiveSlot.PASSIVE02).orElseThrow().value());}
    @Test void lifebloodTriggeredRootIsRejectedBeforeResourceCheck(){var h=new H("quick_slash");h.link("lifeblood",PassiveSlot.PASSIVE01);assertEquals("LIFEBLOOD_MANUAL_UPFRONT_ONLY",h.cast(SkillSlot.SKILL01,SkillExecutionRequest.Origin.TRIGGERED).code());assertEquals(0,h.healthWrites);}
    @Test void nativeFloatPaymentGuardRejectsInvisibleAndLethalSubtractions(){assertThrows(IllegalStateException.class,()->RpgResourceService.nativeHealthTarget(1e10f,(double)1e10f-8));assertThrows(IllegalStateException.class,()->RpgResourceService.nativeHealthTarget(8,.5));assertEquals(1,RpgResourceService.nativeHealthTarget(9,1));}
    @Test void firstCommitUsesZeroThenSecondUsesOneStack(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(1,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));h.ready();h.cast();assertEquals(1.03,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(2,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void sixManualCommitsCapAtFiveAndSixthUsesFifteenPercent(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);for(int i=0;i<6;i++){assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(1+.03*Math.min(i,5),h.last().snapshot().modifiers().factor(),1e-9);h.ready();}assertEquals(5,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void exactFourSecondsWithoutCommitExpiresStacks(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);h.cast();h.time=3.999;assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));h.time=4;assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void failedCooldownAndResourceAttemptsDoNotBuildOrExtendStacks(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);h.cast();h.time=3;assertEquals("COOLDOWN_ACTIVE",h.cast().code());h.kernel.cooldowns().clear(h.actor,"quick_slash");h.current.put(ResourceType.STAMINA,0d);assertEquals("INSUFFICIENT_RESOURCE",h.cast().code());h.time=4;assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void anotherSkillDoesNotClearExistingStacks(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);assertTrue(h.b.service().equipSkill(h.actor,SkillSlot.SKILL02,new SkillId("heavy_swing")).success());h.cast();assertEquals(SkillExecutionResult.Status.PENDING,h.cast(SkillSlot.SKILL02,SkillExecutionRequest.Origin.MANUAL).status());assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void actualLoadoutMutationClearsAllSlotsButAttributeMutationDoesNot(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);h.cast();assertTrue(h.b.service().setDevelopmentAttribute(h.actor,RpgAttribute.STR,20).success());assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));assertTrue(h.b.service().equipSkill(h.actor,SkillSlot.SKILL02,new SkillId("heavy_swing")).success());assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void failedLoadoutSaveDoesNotClearStacks(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);h.cast();h.b.repository().failSave=true;assertFalse(h.b.service().unequipSkill(h.actor,SkillSlot.SKILL01).success());assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void triggeredCommitDoesNotBuildStacks(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast(SkillSlot.SKILL01,SkillExecutionRequest.Origin.TRIGGERED).status());assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void windupUsesCommitTimeStacksAfterExpiry(){var h=new H("heavy_swing");h.link("attunement",PassiveSlot.PASSIVE01);h.cast();assertEquals(SkillExecutionResult.Status.COMMITTED,h.service.completeWindup(h.actor,h).status());h.ready();h.time=3.9;h.cast();h.time=4.4;assertEquals(SkillExecutionResult.Status.COMMITTED,h.service.completeWindup(h.actor,h).status());assertEquals(1,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void windupInterruptRetainsPreviousStackButTerminalCleanupClearsIt(){var h=new H("heavy_swing");h.link("attunement",PassiveSlot.PASSIVE01);h.cast();h.service.completeWindup(h.actor,h);h.ready();h.cast();h.service.cancel(h.actor,"NATIVE_DAMAGE_INTERRUPT");assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));h.service.forgetPassiveState(h.actor);assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void echoInheritsSnapshotAndNeverBuildsAnExtraStackOrSpendsHealth(){var h=new H("fire_bolt");h.weapon="STAFF";h.link("attunement",PassiveSlot.PASSIVE01);h.link("lifeblood",PassiveSlot.PASSIVE02);h.link("echo",PassiveSlot.PASSIVE03);h.cast();h.time=.45;h.service.tickScheduled(h.actor,h);assertEquals(2,h.contexts.size());assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));assertEquals(1,h.healthWrites);assertEquals(h.contexts.getFirst().rootCastId(),h.last().rootCastId());}
    @Test void paidNormalDispatchFailureKeepsAttunementCommit(){var h=new H("quick_slash");h.link("attunement",PassiveSlot.PASSIVE01);h.failDispatch=true;assertEquals(SkillExecutionResult.Status.TERMINATED,h.cast().status());assertEquals(95,h.current(ResourceType.STAMINA));assertEquals(1,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));assertEquals("COOLDOWN_ACTIVE",h.cast().code());}
    @Test void ledgerSeparatesActorsSlotsAndDuplicateCommit(){var l=new AttunementLedger();var actor=UUID.randomUUID();var key=new AttunementLedger.Key(actor,SkillSlot.SKILL01);l.committed(key,"a",0);l.committed(key,"a",1);assertEquals(1,l.stacks(key,1));assertEquals(0,l.stacks(new AttunementLedger.Key(actor,SkillSlot.SKILL02),1));assertEquals(0,l.stacks(new AttunementLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01),1));assertEquals(0,l.stacks(key,4));}
    @Test void ledgerCapacityExpiryAndOwnerRemovalAreBounded(){var l=new AttunementLedger();AttunementLedger.Key first=null;for(int i=0;i<4096;i++){var k=new AttunementLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);if(first==null)first=k;l.committed(k,"root",0);}var extra=new AttunementLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);assertFalse(l.hasCapacity(extra,1));assertThrows(IllegalStateException.class,()->l.committed(extra,"root",1));l.forget(first.actor());assertTrue(l.hasCapacity(extra,1));assertEquals(0,l.size(4));}
    @Test void transactionRollbackCannotResurrectClearedStateOrEraseNewCommit(){var l=new AttunementLedger();var key=new AttunementLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);var old=l.committed(key,"a",0);l.committed(key,"b",1);l.rollback(old);assertEquals(2,l.stacks(key,1));var newest=l.committed(key,"c",2);l.forget(key.actor());l.rollback(newest);assertEquals(0,l.stacks(key,2));}
    @Test void malformedStacksAndLedgerTimeFailClosed(){var l=new AttunementLedger();var key=new AttunementLedger.Key(UUID.randomUUID(),SkillSlot.SKILL01);assertThrows(IllegalArgumentException.class,()->l.committed(key,"",0));assertThrows(IllegalArgumentException.class,()->l.stacks(key,Double.NaN));var r=RpgCombatKernel.createProduction().resources();var p=f.plan("quick_slash","attunement");assertThrows(IllegalArgumentException.class,()->r.evaluateActivation(new ResourceCost(ResourceType.STAMINA,5),p,6));}
}
