package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import com.inigmasgames.hytalerpg.execution.summon.*;
import com.inigmasgames.hytalerpg.links.CompatibilityService;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class Stage10BatchSummonTest {
    @Test void crawlersUseOneCostAndCooldownForThreeActors(){var h=new Stage10SummonTest.Harness("summon_void_crawlers");assertTrue(h.cast().committed());assertEquals(72,h.mana);assertEquals(3,h.leases.size());assertFalse(h.kernel.cooldowns().canActivate(h.actor,"summon_void_crawlers"));for(var lease:h.leases){assertEquals(35,lease.maximumHealth());assertEquals(.4,lease.coefficient());assertEquals(18,lease.expires());assertEquals("RPG_Summon_Crawler",lease.roleId());assertSame(h.context,lease.context());}}
    @Test void broodUsesInnateTwentyAndNoWeaponRequirement(){var h=new Stage10SummonTest.Harness("brood_call"){@Override public Equipment equipment(){return new Equipment(null,null);}};assertTrue(h.cast().committed());assertEquals(74,h.mana);assertEquals(4,h.leases.size());assertEquals(20,h.context.snapshot().basePower());for(var lease:h.leases){assertEquals(25,lease.maximumHealth());assertEquals(.35,lease.coefficient());assertEquals(16,lease.expires());assertEquals("RPG_Summon_Broodling",lease.roleId());}}
    @Test void swarmAddsOneWolfAndReducesEveryMember(){var h=new Stage10SummonTest.Harness();h.link("swarm",PassiveSlot.PASSIVE01);assertTrue(h.cast().committed());assertEquals(2,h.leases.size());assertEquals(80,h.mana);for(var lease:h.leases){assertEquals(45,lease.maximumHealth());assertEquals(.55*.75,lease.coefficient(),1e-9);assertEquals(20,lease.expires());}}
    @Test void swarmCrawlerBatchContainsFour(){var h=new Stage10SummonTest.Harness("summon_void_crawlers");h.link("swarm",PassiveSlot.PASSIVE01);h.cast();assertEquals(4,h.leases.size());for(var lease:h.leases)assertEquals(26.25,lease.maximumHealth());assertEquals(72,h.mana);}
    @Test void swarmBroodBatchContainsFive(){var h=new Stage10SummonTest.Harness("brood_call");h.link("swarm",PassiveSlot.PASSIVE01);h.cast();assertEquals(5,h.leases.size());for(var lease:h.leases)assertEquals(18.75,lease.maximumHealth());assertEquals(74,h.mana);}
    @Test void empowermentMultipliesSummonNotCaster(){var h=new Stage10SummonTest.Harness();h.link("minion_empowerment",PassiveSlot.PASSIVE01);h.cast();var lease=h.leases.getFirst();assertEquals(78,lease.maximumHealth());assertEquals(.715,lease.coefficient(),1e-9);assertEquals(15,lease.expires());assertEquals(100,h.context.snapshot().derivedStats().maxHealth());assertEquals(80,h.mana);}
    @Test void swarmAndEmpowermentMultiplyInEitherPassiveOrder(){var first=new Stage10SummonTest.Harness();first.link("swarm",PassiveSlot.PASSIVE01);first.link("minion_empowerment",PassiveSlot.PASSIVE02);first.cast();var second=new Stage10SummonTest.Harness();second.link("minion_empowerment",PassiveSlot.PASSIVE01);second.link("swarm",PassiveSlot.PASSIVE02);second.cast();assertEquals(first.context.compiledPlan().summonModifiers(),second.context.compiledPlan().summonModifiers());assertEquals(2,first.leases.size());for(var lease:first.leases){assertEquals(58.5,lease.maximumHealth(),1e-9);assertEquals(.55*.975,lease.coefficient(),1e-9);assertEquals(15,lease.expires());}}
    @Test void duplicatePassiveIdsDoNotStackTypedOperator(){var ids=List.of(new PassiveId("swarm"),new PassiveId("swarm"),new PassiveId("minion_empowerment"));var modifier=SummonModifiers.from(ids);assertEquals(2,modifier.count(1));assertEquals(.975,modifier.healthAndPowerFactor(),1e-9);assertEquals(.75,modifier.lifetimeFactor());}
    @Test void swarmCannotDuplicateReviveClaim(){var h=new Stage10SummonTest.Harness("revive_fallen");assertTrue(h.bundle.service().equipPassive(h.actor,PassiveSlot.PASSIVE01,new PassiveId("swarm")).success());assertFalse(h.bundle.service().link(h.actor,LinkNodeId.PASSIVE01,LinkNodeId.SKILL01).success());}
    @Test void incompatibleDecoyAndConversionSwarmAreRejected(){var catalog=Stage01BTestSupport.bundle().catalog();var compatibility=new CompatibilityService();for(var id:List.of("simulacrum","dominate"))assertFalse(compatibility.assess(catalog.skill(new SkillId(id)).orElseThrow(),catalog.passive(new PassiveId("swarm")).orElseThrow()).accepted(),id);}
    @Test void empowermentDoesNotApplyToConversion(){var catalog=Stage01BTestSupport.bundle().catalog();assertFalse(new CompatibilityService().assess(catalog.skill(new SkillId("dominate")).orElseThrow(),catalog.passive(new PassiveId("minion_empowerment")).orElseThrow()).accepted());}
    @Test void rejectedLinkRollsBackWithoutChangingExistingPlan(){var h=new Stage10SummonTest.Harness();h.cast();var plan=h.context.compiledPlan().planHash();assertTrue(h.bundle.service().equipPassive(h.actor,PassiveSlot.PASSIVE01,new PassiveId("fork")).success());assertFalse(h.bundle.service().link(h.actor,LinkNodeId.PASSIVE01,LinkNodeId.SKILL01).success());h.kernel.cooldowns().clear(h.actor,"wolf_summon");h.now=30;h.mana=100;assertTrue(h.cast().committed());assertEquals(plan,h.context.compiledPlan().planHash());}
    @Test void formationHasAtLeastOneMetreBetweenAllActors(){for(int count=1;count<=8;count++){var points=SummonFormation.points(Vec3.ZERO,count);assertEquals(count,points.size());for(int i=0;i<count;i++)for(int j=0;j<i;j++)assertTrue(points.get(i).subtract(points.get(j)).length()>=1);}}
    @Test void formationIsCentredDeterministicAndCompact(){var centre=new Vec3(10,20,30);for(int count=1;count<=8;count++){var points=SummonFormation.points(centre,count);assertEquals(points,SummonFormation.points(centre,count));var sum=Vec3.ZERO;for(var point:points){sum=sum.add(point);assertEquals(20,point.y());assertTrue(point.subtract(centre).length()<=1.4);}assertTrue(sum.multiply(1d/count).subtract(centre).length()<1e-9);}}
    @Test void formationRejectsUnboundedCount(){for(int count:new int[]{0,-1,9,Integer.MAX_VALUE})assertThrows(IllegalArgumentException.class,()->SummonFormation.points(Vec3.ZERO,count));}
    // Clear only the fixture's real-clock cooldown to isolate admission; no production expiry is asserted here.
    @Test void wholeBatchRejectsBeforePaymentAtOwnerCap(){var h=new Stage10SummonTest.Harness("brood_call");h.link("swarm",PassiveSlot.PASSIVE01);assertTrue(h.cast().committed());h.kernel.cooldowns().clear(h.actor,"brood_call");h.now=30;h.mana=100;assertFalse(h.cast().committed());assertEquals(100,h.mana);assertEquals(5,h.summons.size());}
    @Test void twoUnmodifiedBroodBatchesReachExactlyEight(){var h=new Stage10SummonTest.Harness("brood_call");var first=h.cast();assertEquals(com.inigmasgames.hytalerpg.execution.SkillExecutionResult.Status.COMMITTED,first.status(),first.toString());h.kernel.cooldowns().clear(h.actor,"brood_call");h.now=30;h.mana=100;var second=h.cast();assertEquals(com.inigmasgames.hytalerpg.execution.SkillExecutionResult.Status.COMMITTED,second.status(),second.toString());assertEquals(8,h.summons.size());h.kernel.cooldowns().clear(h.actor,"brood_call");h.now=60;h.mana=100;assertFalse(h.cast().committed());assertEquals(100,h.mana);}
    @Test void eachActorClaimsItsOwnIntervalOnlyOnce(){var h=new Stage10SummonTest.Harness("summon_void_crawlers");h.cast();for(var lease:h.leases){h.summons.activate(lease,UUID.randomUUID(),0);assertEquals(1,h.summons.claimAttack(lease.token(),1));assertEquals(0,h.summons.claimAttack(lease.token(),1));}assertEquals(3,h.summons.size());}
    @Test void delayedBatchStartsReducedLifetimeAtRelease(){var h=new Stage10SummonTest.Harness("brood_call");h.link("minion_empowerment",PassiveSlot.PASSIVE01);h.link("skill_delay",PassiveSlot.PASSIVE02);h.cast();assertEquals(0,h.summons.size());h.now=2;h.execution.tickScheduled(h.actor,h);assertEquals(4,h.summons.size());for(var lease:h.leases)assertEquals(14,lease.expires());assertEquals(74,h.mana);}
    @Test void existingPotencyIsNotAppliedTwiceBySummonModifier(){var h=new Stage10SummonTest.Harness();h.link("potency",PassiveSlot.PASSIVE01);h.link("minion_empowerment",PassiveSlot.PASSIVE02);h.cast();assertEquals(.55*1.3,h.leases.getFirst().coefficient(),1e-9);assertEquals(1.15,h.context.snapshot().modifiers().factor(),1e-9);}
}
