package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.execution.math.Vec3;
import com.inigmasgames.hytalerpg.progress.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class Stage12EncounterTest {
    @org.junit.jupiter.api.io.TempDir java.nio.file.Path temporary;
    private final UUID world=UUID.randomUUID(),enemy=UUID.randomUUID(),a=UUID.randomUUID(),b=UUID.randomUUID();
    private final EnemyRewardRegistry registry=EnemyRewardRegistry.load();
    private final EncounterContributions ledger=new EncounterContributions();
    private EnemyRewardRegistry.Spawn spawn(){return registry.classify(world,enemy,"Wolf_Black","Default/Zone1_Tier1/Forest_Birch",EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,0).orElseThrow();}
    private void begin(){assertTrue(ledger.begin(spawn()));}
    private void hit(UUID player,long now){assertTrue(ledger.damage(world,enemy,player,100,90,100,true,now));}
    private EncounterContributions.Participant participant(UUID player,int level,String party){return new EncounterContributions.Participant(player,world,Vec3.ZERO,level,true,party);}
    @Test void auditedPilotsHaveAuthoredBandsNotVanillaLevels(){assertEquals(3,registry.roles().size());assertEquals(4,registry.biomes().size());registry.validateBands(ProgressionProfiles.load());assertEquals(5,spawn().level());assertEquals(ProgressionMath.Rank.COMMON,spawn().rank());}
    @Test void unknownRoleVariantOrBiomeCannotEarn(){assertTrue(registry.classify(world,enemy,"Wolf_Unknown","Default/Zone1_Tier1/Forest_Birch",EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,0).isEmpty());assertTrue(registry.classify(world,enemy,"Trork_Warrior_Patrol","Default/Zone1_Tier1/Forest_Birch",EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,0).isEmpty());assertTrue(registry.classify(world,enemy,"Wolf_Black","made-up",EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,0).isEmpty());}
    @ParameterizedTest @EnumSource(value=EnemyRewardRegistry.Origin.class,names="WILD_WORLD_SPAWN",mode=EnumSource.Mode.EXCLUDE)
    void nonWildProvenanceAlwaysExcluded(EnemyRewardRegistry.Origin origin){assertTrue(registry.classify(world,enemy,"Wolf_Black","Default/Zone1_Tier1/Forest_Birch",origin,0).isEmpty());}
    @Test void spawnClassificationCannotBeChangedByDraggingAcrossBiomes(){begin();var moved=registry.classify(world,enemy,"Wolf_Black","Default/Zone3_Tier1/Forest_Fir",EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,1).orElseThrow();assertThrows(IllegalStateException.class,()->ledger.begin(moved));hit(a,1);var death=ledger.death(world,enemy,new Vec3(10000,0,0),2,List.of(new EncounterContributions.Participant(a,world,new Vec3(10000,0,0),5,true,null)));assertEquals(5,death.spawn().level());assertEquals(131,death.shares().getFirst().xp());}
    @Test void actualHealthLossGivesCreditWithoutLastHit(){begin();hit(a,0);hit(b,100);var death=ledger.death(world,enemy,Vec3.ZERO,200,List.of(participant(a,5,null),participant(b,5,null)));assertEquals(2,death.shares().size());assertTrue(death.shares().stream().allMatch(s->s.xp()==131&&s.insight()==1));}
    @Test void invalidCancelledNonHostileAndNonLossInputsDoNotCredit(){begin();assertFalse(ledger.damage(world,enemy,a,100,100,100,true,0));assertFalse(ledger.damage(world,enemy,a,100,90,100,false,0));assertFalse(ledger.damage(world,enemy,a,Double.NaN,90,100,true,0));assertFalse(ledger.damage(world,enemy,a,100,-1,100,true,0));assertFalse(ledger.damage(world,enemy,a,101,90,100,true,0));assertTrue(ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,null))).shares().isEmpty());}
    @Test void cannotSelfCreditAnEnemy(){begin();assertFalse(ledger.damage(world,enemy,enemy,100,90,100,true,0));}
    @Test void twentySecondBoundaryIsInclusive(){begin();hit(a,0);assertEquals(1,ledger.death(world,enemy,Vec3.ZERO,20000,List.of(participant(a,5,null))).shares().size());}
    @Test void expiredContributionCannotEarn(){begin();hit(a,0);assertTrue(ledger.death(world,enemy,Vec3.ZERO,20001,List.of(participant(a,5,null))).shares().isEmpty());}
    @Test void sixtyFourMeterBoundaryIsThreeDimensionalAndInclusive(){begin();hit(a,0);hit(b,0);var exact=new EncounterContributions.Participant(a,world,new Vec3(0,64,0),5,true,null);var outside=new EncounterContributions.Participant(b,world,new Vec3(64.001,0,0),5,true,null);var shares=ledger.death(world,enemy,Vec3.ZERO,1,List.of(exact,outside)).shares();assertEquals(1,shares.size());assertEquals(a,shares.getFirst().player());}
    @Test void unloadedAndDifferentWorldParticipantsCannotEarn(){begin();hit(a,0);hit(b,0);assertTrue(ledger.death(world,enemy,Vec3.ZERO,1,List.of(new EncounterContributions.Participant(a,world,Vec3.ZERO,5,false,null),new EncounterContributions.Participant(b,UUID.randomUUID(),Vec3.ZERO,5,true,null))).shares().isEmpty());}
    @Test void partyUsesOneEqualPotWithoutBonusAndInsightEach(){begin();hit(a,0);hit(b,0);var shares=ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,"party"),participant(b,5,"party"))).shares();assertEquals(2,shares.size());assertTrue(shares.stream().allMatch(s->s.xp()==65&&s.insight()==1&&s.eligiblePartyMembers()==2));}
    @Test void mixedLevelPartyUsesHighestEligibleLevelForSingleConservativePot(){begin();hit(a,0);hit(b,0);var shares=ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,"party"),participant(b,20,"party"))).shares();assertTrue(shares.stream().allMatch(s->s.xp()==6&&s.commonPotPlayerLevel()==20));}
    @Test void ineligibleHighLevelPartyMemberDoesNotReduceEligiblePot(){begin();hit(a,0);var shares=ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,"party"),participant(b,99,"party"))).shares();assertEquals(131,shares.getFirst().xp());assertEquals(1,shares.getFirst().eligiblePartyMembers());}
    @Test void actualHealingContributorCreatesSupportCredit(){begin();hit(a,0);assertEquals(1,ledger.heal(world,b,a,10,true,100));assertEquals(2,ledger.death(world,enemy,Vec3.ZERO,101,List.of(participant(a,5,"p"),participant(b,5,"p"))).shares().size());}
    @Test void overhealUnknownRecipientAndDisallowedAllyDoNotCredit(){begin();assertEquals(0,ledger.heal(world,b,a,10,true,0));hit(a,0);assertEquals(0,ledger.heal(world,b,a,0,true,0));assertEquals(0,ledger.heal(world,b,a,10,false,0));assertEquals(0,ledger.heal(world,b,a,Double.NaN,true,0));assertEquals(1,ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,null),participant(b,5,null))).shares().size());}
    @Test void healerCannotRefreshAnExpiredContribution(){begin();hit(a,0);assertEquals(0,ledger.heal(world,b,a,10,true,20001));}
    @Test void absorbAndEffectiveControlQualifyWithoutDamage(){begin();assertTrue(ledger.absorb(world,enemy,a,5,true,0));assertTrue(ledger.control(world,enemy,b,true,false,true,0));assertEquals(2,ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,"p"),participant(b,5,"p"))).shares().size());}
    @Test void ineffectiveControlAndUnconsumedShieldNeverQualify(){begin();assertFalse(ledger.absorb(world,enemy,a,0,true,0));assertFalse(ledger.absorb(world,enemy,a,10,false,0));assertFalse(ledger.control(world,enemy,a,false,false,true,0));assertFalse(ledger.control(world,enemy,a,true,true,false,0));assertTrue(ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,null))).shares().isEmpty());}
    @Test void successfulTauntCanQualify(){begin();assertTrue(ledger.control(world,enemy,a,true,true,true,0));assertEquals(1,ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,null))).shares().size());}
    @Test void conversionInvalidationSurvivesRepeatedBegin(){begin();hit(a,0);ledger.disqualify(world,enemy);assertFalse(ledger.begin(spawn()));assertFalse(ledger.damage(world,enemy,a,90,80,100,true,1));assertTrue(ledger.death(world,enemy,Vec3.ZERO,2,List.of(participant(a,5,null))).shares().isEmpty());}
    @Test void frozenDeathPlanIsIndependentOfRetryPositionMembershipAndLevel(){begin();hit(a,0);var first=ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,null)));assertSame(first,ledger.death(world,enemy,new Vec3(1000,0,0),100000,List.of()));assertFalse(ledger.damage(world,enemy,a,90,80,100,true,2));var grant=first.reward(first.shares().getFirst());assertEquals(spawn().eventId(),grant.eventId());assertEquals(131,grant.characterXp());}
    @Test void duplicateParticipantListCannotDoubleShare(){begin();hit(a,0);assertThrows(IllegalArgumentException.class,()->ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,5,null),participant(a,5,null))));}
    @Test void clockReversalCannotRefreshCreditOrFreezeAReward(){begin();hit(a,100);assertFalse(ledger.control(world,enemy,b,true,true,true,99));assertThrows(IllegalStateException.class,()->ledger.death(world,enemy,Vec3.ZERO,99,List.of(participant(a,5,null))));}
    @Test void masteryRequiresRecentContributionAndNotElevenLevelsBelow(){begin();hit(a,0);assertTrue(ledger.masteryEligible(world,enemy,a,15,1));assertFalse(ledger.masteryEligible(world,enemy,a,16,1));assertFalse(ledger.masteryEligible(world,enemy,b,5,1));assertFalse(ledger.masteryEligible(world,enemy,a,5,20001));}
    @Test void repeatedCaptiveHealDamageStopsMasteryUntilGenuineNewHealthLow(){begin();hit(a,0);hit(a,60001);assertFalse(ledger.masteryEligible(world,enemy,a,5,60001));assertTrue(ledger.damage(world,enemy,a,100,89,100,true,60002));assertTrue(ledger.masteryEligible(world,enemy,a,5,60002));}
    @Test void supportOnlyUnchangedEncounterHasSixtySecondMasteryLimit(){begin();assertTrue(ledger.absorb(world,enemy,a,1,true,0));assertTrue(ledger.absorb(world,enemy,a,1,true,60000));assertTrue(ledger.masteryEligible(world,enemy,a,5,60000));assertTrue(ledger.absorb(world,enemy,a,1,true,60001));assertFalse(ledger.masteryEligible(world,enemy,a,5,60001));}
    @Test void removingAndUnloadingEncounterCleansSupportIndex(){begin();hit(a,0);ledger.remove(world,enemy);assertEquals(0,ledger.size());assertEquals(0,ledger.heal(world,b,a,10,true,1));begin();hit(a,0);ledger.unload(world);assertEquals(0,ledger.size());assertEquals(0,ledger.heal(world,b,a,10,true,1));}
    @Test void contributorLimitAndPerActorEncounterIndexAreBounded(){begin();for(int i=0;i<256;i++)assertTrue(ledger.absorb(world,enemy,UUID.randomUUID(),1,true,0));assertFalse(ledger.absorb(world,enemy,a,1,true,0));ledger.unload(world);for(int i=0;i<64;i++){UUID target=UUID.randomUUID();var context=registry.classify(world,target,"Wolf_Black",spawn().biomeKey(),EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,0).orElseThrow();assertTrue(ledger.begin(context));assertTrue(ledger.damage(world,target,a,100,90,100,true,0));}assertEquals(64,ledger.heal(world,b,a,10,true,0));begin();assertFalse(ledger.damage(world,enemy,a,100,90,100,true,0));}
    @Test void encounterBudgetFailsClosedWithoutEvictingEarlierEligibleActor(){for(int i=0;i<4096;i++)assertTrue(ledger.begin(registry.classify(world,UUID.randomUUID(),"Wolf_Black",spawn().biomeKey(),EnemyRewardRegistry.Origin.WILD_WORLD_SPAWN,0).orElseThrow()));assertFalse(ledger.begin(spawn()));assertEquals(4096,ledger.size());ledger.unload(world);assertTrue(ledger.begin(spawn()));}
    @Test void unregisteredTargetCannotGenerateCreditOrDeath(){assertFalse(ledger.damage(world,enemy,a,100,90,100,true,0));assertThrows(IllegalStateException.class,()->ledger.death(world,enemy,Vec3.ZERO,0,List.of()));}
    @Test void frozenBackendDeathDrivesExistingDurablePlayerXpAndProjectionExactlyOnce(){
        begin();hit(a,0);var plan=ledger.death(world,enemy,Vec3.ZERO,1,List.of(participant(a,1,null)));
        var bundle=Stage01BTestSupport.bundle();bundle.service().configureEarnedRewards(new FileEarnedRewardStore(temporary));
        for(var share:plan.shares()){bundle.service().awardEarned(share.player(),plan.reward(share));bundle.service().awardEarned(share.player(),plan.reward(share));}
        var state=bundle.service().getPresentationView(a).state();assertEquals(131,state.currentXp);assertEquals(2,state.level);
        assertEquals(5,state.unspentAttributePoints);assertEquals(5,state.pendingLevelUpPoints);assertEquals(1,state.rewards.insight());
        var xp=new com.inigmasgames.hytalerpg.ui.CharacterXpProjectionService().project(state.currentXp);assertEquals(2,xp.level());assertEquals(31,xp.xpIntoLevel());
    }
}
