package com.inigmasgames.hytalerpg;
import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.area.AreaGeometry;
import com.inigmasgames.hytalerpg.execution.connection.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11OrbitConversionTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    Stage08ConnectionTest.Harness h(String skill,String...extra){var ids=new ArrayList<String>();ids.add("orbit");ids.addAll(List.of(extra));return new Stage08ConnectionTest.Harness(skill,ids.toArray(String[]::new));}
    void cast(Stage08ConnectionTest.Harness h){var r=h.cast();if(r.status()==SkillExecutionResult.Status.PENDING)r=h.service.completeWindup(h.owner,h);assertEquals(SkillExecutionResult.Status.COMMITTED,r.status());}
    SkillExecutionContext c(Stage08ConnectionTest.Harness h){return h.contexts.getFirst();}
    void cover(Stage08ConnectionTest.Harness h){h.targets.add(new ConnectionWorldPort.Target("target",new AreaGeometry.Bounds(new Vec3(-5,0,-5),new Vec3(5,3,5))));}
    void to(Stage08ConnectionTest.Harness h,double end){double t=h.clock.get()/1e9;while(t<end-1e-8){t=Math.min(end,t+.05);h.advance(t);}}
    @Test void exactApprovedConfigIsDataDrivenAndBounded(){var d=OrbitConversionProfiles.CONFIG;assertEquals(4,d.durationSeconds());assertEquals(.7,d.magnitudeFactor());assertEquals(2.5,d.radius());assertEquals(1.3,d.originHeight());assertEquals(120,d.degreesPerSecond());assertEquals(.75,d.targetIntervalSeconds());assertEquals(3,d.maxOrbs());assertThrows(IllegalArgumentException.class,()->new OrbitConversionProfiles.Config(4,.7,2.5,1.3,120,.01,.75,4));}
    @Test void projectileAndOrbConvertWhileStrikeAuraAndChannelReject(){for(String id:List.of("fire_bolt","frost_bolt","stone_bolt","quick_shot","ball_lightning","orbiting_shadow_blades"))assertTrue(f.accepts(id,"orbit"),id);for(String id:List.of("quick_slash","managuard","void_beam","wolf_summon"))assertFalse(f.accepts(id,"orbit"),id);}
    @Test void convertedProfileDispatchesConnectionNotNativeProjectile(){var h=h("fire_bolt");cast(h);assertEquals(Stage04SkillProfile.Family.ORBIT,c(h).profile().family());assertEquals(ConnectionProfile.Kind.ORBIT,c(h).profile().connection().kind());assertEquals(1,h.runtime.size());assertEquals(1,h.contexts.size());}
    @Test void originalPayloadAndEquipmentMetadataRemainImmutable(){var h=h("fire_bolt");cast(h);assertNotNull(c(h).profile().projectile());assertEquals("BURN",c(h).profile().projectile().statusId());assertEquals(h.profile.projectile(),c(h).profile().projectile());assertEquals(h.profile.allowedMainHandKinds(),c(h).profile().allowedMainHandKinds());assertNull(h.profile.connection());assertEquals(Stage04SkillProfile.Family.PROJECTILE,h.profile.family());}
    @Test void fourSecondOneOrbSeventyPercentNoExtraPayment(){var h=h("fire_bolt");cover(h);cast(h);assertEquals(.7,c(h).snapshot().modifiers().factor(),1e-9);assertEquals(4,c(h).profile().connection().lifetimeSeconds());assertEquals(1,c(h).profile().connection().details().bladeCount());assertEquals(1,h.resourceWrites);to(h,4);assertEquals(6,h.hits.size());assertEquals(0,h.runtime.size());assertEquals(0,h.capacity.size());assertEquals(1,h.resourceWrites);}
    @Test void contactRadiusIsPayloadGeometryNotAnInventedArtCollider(){var h=h("fire_bolt");cast(h);assertEquals(h.profile.projectile().radius(),c(h).profile().connection().radius());assertEquals(2.5,c(h).profile().connection().range());assertEquals(1.3,c(h).profile().connection().originHeight());assertEquals(h.profile.projectile().coefficient(),c(h).profile().connection().coefficient());}
    @Test void projectileContinuationsAreRejectedAfterConversionInEitherOrder(){for(String id:List.of("piercing","fork","chain","return","ricochet","homing","accelerant","ballistics","shrapnel","splinterburst","long_reach")){var h=h("fire_bolt");assertFalse(h.link(id),id);}var h=new Stage08ConnectionTest.Harness("fire_bolt","fork");assertFalse(h.link("orbit"));}
    @Test void finalPlanRemovesCarrierCapabilitiesAndIntroducesActualOrbitArea(){var p=f.plan("fire_bolt","orbit");assertEquals("ORBIT",p.finalFamily());assertFalse(p.finalTags().contains("PROJECTILE"));assertFalse(p.finalTags().contains("CAN_FORK"));assertTrue(p.finalTags().containsAll(Set.of("ORBIT","HAS_AREA_GEOMETRY","HAS_RADIUS","PERSISTENT_FINITE_EFFECT")));}
    @Test void convertedGeometryAcceptsRadiusAndConcentrationLocally(){var h=h("fire_bolt","expanded_radius","concentration");cast(h);assertFalse(c(h).compiledPlan().concentrationOnlyOnSecondary());assertEquals(2.5*.7,c(h).profile().connection().range(),1e-9);assertEquals(1.3*.9*.7,c(h).snapshot().modifiers().factor(),1e-9);var end=h.shapes.getFirst().end();assertEquals(2.5*.7*1.25,end.horizontalLength(),1e-9);}
    @Test void introducedPositionAffectsConvertedPrimaryNotAnUnusedSecondary(){var h=h("frost_bolt","vacuum");cast(h);assertFalse(c(h).compiledPlan().positionOnlyOnSecondary());assertEquals(.7*.9,c(h).snapshot().modifiers().factor(),1e-9);assertTrue(ProfileComponentPolicy.enemyPosition(c(h).profile()));}
    @Test void lingeringModifiesFiniteOrbitAndExistingDotSeparatelyOnce(){var h=h("fire_bolt","lingering");cast(h);assertEquals(5.6,c(h).profile().connection().lifetimeSeconds(),1e-9);assertEquals(h.profile.projectile().statusSeconds()*1.4,c(h).profile().projectile().statusSeconds(),1e-9);}
    @Test void inheritedDirectDamagePenaltiesReachConvertedContactCoefficient(){var h=h("fire_bolt","combustion");cast(h);assertEquals(h.profile.projectile().coefficient()*.85,c(h).profile().connection().coefficient(),1e-9);var cold=h("frost_bolt","deep_freeze");cast(cold);assertEquals(cold.profile.projectile().coefficient()*.9,c(cold).profile().connection().coefficient(),1e-9);}
    @Test void volleyMakesThreeOrbsWithOneSharedVictimInterval(){var h=h("fire_bolt","volley");cover(h);cast(h);assertEquals(3,h.shapes.size());assertEquals(1,h.hits.size());to(h,4);assertEquals(6,h.hits.size());assertEquals(3,c(h).effects().spawned());assertEquals(.7*.75,c(h).snapshot().modifiers().factor(),1e-9);assertEquals(1,h.resourceWrites);}
    @Test void volleyCannotCombineWithEchoOrBarrageToExceedThree(){for(String extra:List.of("echo","barrage")){var h=h("fire_bolt","volley");assertFalse(h.link(extra));}}
    @Test void alreadyMultiOrbPayloadCannotDoubleItsThreeOrbCap(){var h=h("orbiting_shadow_blades");assertFalse(h.link("echo"));cast(h);assertEquals(3,c(h).profile().connection().details().bladeCount());}
    @Test void nativeUnconvertedOrbitingShadowBladesStillHaveFourBlades(){var h=new Stage08ConnectionTest.Harness("orbiting_shadow_blades");cast(h);assertEquals(4,c(h).profile().connection().details().bladeCount());assertEquals(10,c(h).profile().connection().lifetimeSeconds());}
    @Test void barrageUsesDistinctFiniteInstancesAndOneRootInterval(){var h=h("fire_bolt","barrage");cover(h);cast(h);to(h,.4);assertEquals(3,h.runtime.size());assertEquals(3,h.contexts.stream().map(SkillExecutionContext::skillInstanceId).distinct().count());assertEquals(1,h.contexts.stream().map(SkillExecutionContext::rootCastId).distinct().count());assertEquals(1,h.hits.size());assertEquals(3,c(h).effects().spawned());to(h,4.4);assertEquals(0,h.runtime.size());assertEquals(1,h.resourceWrites);}
    @Test void echoSharesContactIntervalAndCannotAddAnImmediateExtraHit(){var h=h("fire_bolt","echo");cover(h);cast(h);to(h,.5);assertEquals(2,h.runtime.size());assertEquals(1,h.hits.size());assertSame(c(h).effects(),h.contexts.getLast().effects());to(h,4.5);assertEquals(0,h.runtime.size());assertEquals(1,h.resourceWrites);}
    @Test void threeLiveConvertedOrbsRejectFourthBeforeRuntimeAllocation(){var h=h("fire_bolt","volley");cast(h);var root=c(h);assertEquals("CONVERTED_ORBIT_LIVE_CAP",h.runtime.admission(h.owner,root.profile(),root.compiledPlan()));assertEquals(1,h.capacity.size());}
    @Test void convertedOrbitDoesNotTurnContactSamplingIntoRapidPulse(){var h=h("ball_lightning");assertFalse(h.link("rapid_pulse"));}
    @Test void ownerMovementKeepsOrbitAttachmentAndNoStaleWorldTrail(){var h=h("fire_bolt");cast(h);h.feet=new Vec3(5,0,0);h.advance(.05);assertTrue(h.shapes.getLast().end().x()>7);assertEquals(1.3,h.shapes.getLast().end().y());h.validation="OWNER_WORLD_CHANGED";h.advance(.1);assertEquals(0,h.runtime.size());}
    @Test void invalidAndDuplicateRootContactCannotBypassInterval(){var b=new RootEffectBudget(UUID.randomUUID(),"r");assertEquals("PASS",b.claimOrbitContact("target",1));assertEquals("ROOT_ORBIT_CONTACT_ICD",b.claimOrbitContact("target",1.749));assertEquals("PASS",b.claimOrbitContact("target",1.75));assertEquals("ROOT_ORBIT_CONTACT_ICD",b.claimOrbitContact("target",1));assertEquals("INVALID_ORBIT_CONTACT",b.claimOrbitContact("target",Double.NaN));}
    @Test void rootContactVictimMemoryIsBounded(){var b=new RootEffectBudget(UUID.randomUUID(),"r");for(int i=0;i<256;i++)assertEquals("PASS",b.claimOrbitContact("t"+i,0));assertEquals("ROOT_ORBIT_TARGET_BUDGET",b.claimOrbitContact("extra",1));assertEquals("PASS",b.claimOrbitContact("t0",1));}
    @Test void cacheKeysDistinguishNormalConvertedAndVolleyProfiles(){var normal=f.effective("fire_bolt");var one=f.effective("fire_bolt","orbit");var three=f.effective("fire_bolt","orbit","volley");assertNull(normal.connection());assertEquals(1,one.connection().details().bladeCount());assertEquals(3,three.connection().details().bladeCount());assertSame(one,f.effective("fire_bolt","orbit"));}
    @Test void aftermathCanUseTheConvertedPersistentComponent(){var h=h("fire_bolt","aftermath");cover(h);cast(h);to(h,4);assertEquals(1,h.runtime.size());to(h,5.6);assertEquals(0,h.runtime.size());assertEquals(1,h.resourceWrites);assertTrue(h.hitContexts.stream().anyMatch(x->x.secondaryKind().equals("aftermath")));}
    @Test void cancelAndLargeSimulationGapCleanConvertedFields(){var h=h("fire_bolt","volley");cast(h);h.advance(2);assertEquals(0,h.runtime.size());assertEquals(0,h.capacity.size());var other=h("fire_bolt");cast(other);other.runtime.cancel(other.owner,false);assertEquals(0,other.runtime.size());}
    @Test void sameNativeAmmunitionRequirementSurvivesConversion(){var h=h("quick_shot");cast(h);assertEquals(h.profile.projectile().ammoItemId(),c(h).profile().projectile().ammoItemId());assertEquals(h.profile.projectile().ammoQuantity(),c(h).profile().projectile().ammoQuantity());assertEquals(h.profile.allowedMainHandKinds(),c(h).profile().allowedMainHandKinds());}
}
