package com.inigmasgames.hytalerpg;
import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.area.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11AftermathTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    Stage11CascadeTest.H h(String...mods){return new Stage11CascadeTest.H("poison_cloud",mods);}
    void areaTo(Stage11CascadeTest.H h,double end){while(h.now<end-1e-8)h.step(Math.min(end,h.now+.25));}
    @Test void eligiblePersistentProfilesAndExcludedDeliveries(){for(String id:List.of("poison_cloud","vortex","earthquake","blizzard","wall_of_fire","root_snare","ball_lightning","orbiting_shadow_blades"))assertTrue(f.accepts(id,"aftermath"),id);for(String id:List.of("snipe","meteor","frost_nova","fire_bolt","bone_cage","managuard","void_beam","battle_cry"))assertFalse(f.accepts(id,"aftermath"),id);}
    @Test void noChildUntilNormalExpiry(){var h=h("aftermath");h.start();areaTo(h,7.75);assertEquals(1,h.areas.size());assertEquals(1,h.context.effects().spawned());h.step(8);assertEquals(1,h.areas.size());assertEquals(2,h.context.effects().spawned());assertTrue(h.shown.getLast().secondaryKind().equals("aftermath"));}
    @Test void childGeometryDurationAndMagnitudeResolveOnce(){var h=h("aftermath","potency","expanded_radius");h.start();areaTo(h,8);var child=h.shown.getLast();assertEquals(3.2,child.profile().area().lifetimeSeconds(),1e-9);assertEquals(3,child.profile().area().radius());assertEquals(3*1.25,h.shapes.getLast().radius());assertEquals(1.15*.9*.5,child.snapshot().modifiers().factor(),1e-9);assertEquals(8,h.context.profile().area().lifetimeSeconds());assertEquals(5,h.context.profile().area().radius());assertSame(h.context.effects(),child.effects());assertSame(h.context.leechBudget(),child.leechBudget());}
    @Test void noPartialFinalPulseOrAdditionalResourcePayment(){var h=h("aftermath");h.targets=List.of(Stage06AreaRuntimeTest.target("a",0,0));h.start();areaTo(h,11.2);assertEquals(44,h.hits.size());assertEquals(12,h.hits.stream().filter(c->c.secondaryKind().equals("aftermath")).count());assertEquals(0,h.areas.size());assertEquals(0,h.budget.size());assertEquals(1,h.writes);assertEquals(76,h.mana);assertEquals(0,h.areas.retainedRootCount());}
    @Test void forcedCancelCreatesNoChild(){var h=h("aftermath");h.start();h.step(.25);h.areas.cancel(h.actor);areaTo(h,12);assertEquals(1,h.context.effects().spawned());assertEquals(0,h.areas.size());}
    @Test void SimulationGapIsNotNaturalExpiry(){var h=h("aftermath");h.start();h.step(9);assertEquals(0,h.areas.size());assertEquals(1,h.context.effects().spawned());assertTrue(h.reasons.contains("SIMULATION_GAP_EXCEEDS_ONE_SECOND"));}
    @Test void secondaryExpiryCannotProduceAnotherAftermath(){var h=h("aftermath");h.start();areaTo(h,25);assertEquals(2,h.context.effects().spawned());assertEquals(1,h.context.effects().triggered());assertEquals(0,h.areas.size());}
    @Test void childCannotInvokeCascadeEchoOrAnotherAftermath(){var h=h("aftermath","cascade","echo");h.start();var c=h.context.aftermathCopy();assertThrows(IllegalStateException.class,c::aftermathCopy);assertThrows(IllegalStateException.class,c::echoCopy);assertThrows(IllegalStateException.class,()->c.cascadeCopy(1));assertEquals(h.context.rootCastId(),c.rootCastId());assertEquals(h.context.request().correlationId(),c.request().correlationId());}
    @Test void terrainRevalidationCanRejectChildAfterParentExpiry(){var h=h("aftermath");h.start();areaTo(h,7.75);h.ground=false;h.step(8);assertEquals(0,h.areas.size());assertTrue(h.reasons.contains("AFTERMATH_CHILD_REJECTED"));assertEquals(76,h.mana);}
    @Test void expiredParentReleasesItsLeaseBeforeReplacementAtFullCapacity(){var h=h("aftermath");for(int i=0;i<7;i++)h.budget.reserve(h.actor,"external"+i);h.start();areaTo(h,8);assertEquals(8,h.budget.size());assertEquals(1,h.areas.size());assertEquals("aftermath",h.shown.getLast().secondaryKind());}
    @Test void consumedTriggeredBudgetRejectsAftermathButNotPaidParent(){var h=h("aftermath");h.preSpentSecondaries=16;h.start();areaTo(h,8);assertEquals(0,h.areas.size());assertEquals(16,h.context.effects().triggered());assertTrue(h.reasons.contains("AFTERMATH_CHILD_REJECTED"));}
    @Test void cascadeChildrenDoNotCreateTheirOwnAftermath(){var h=h("aftermath","cascade");h.start();areaTo(h,8);assertEquals(1,h.areas.size());assertEquals(4,h.context.effects().spawned());assertEquals(3,h.context.effects().triggered());areaTo(h,12);assertEquals(0,h.areas.size());}
    @Test void nonCollidingWallRetainsHeightAndShrinksHorizontalDimensions(){var p=f.profiles.require("wall_of_fire");var c=AftermathProfiles.resolve(p);assertEquals(p.area().length()*.6,c.area().length(),1e-9);assertEquals(p.area().width()*.6,c.area().width(),1e-9);assertEquals(p.area().height(),c.area().height());assertEquals(p.area().intervalSeconds(),c.area().intervalSeconds());}
    @Test void trapTriggersDoNotCreateExpiryChild(){var h=new Stage11CascadeTest.H("root_snare","aftermath");h.targets=List.of(Stage06AreaRuntimeTest.target("a",0,0));h.start();areaTo(h,1);assertEquals(0,h.areas.size());assertEquals(1,h.context.effects().spawned());assertTrue(h.reasons.contains("TRAP_TRIGGERED"));}
    @Test void untriggeredTrapExpiryLeavesOneSmallerFiniteTrap(){var h=new Stage11CascadeTest.H("root_snare","aftermath");h.start();areaTo(h,15);assertEquals(1,h.areas.size());assertEquals(6,h.shown.getLast().profile().area().lifetimeSeconds());assertEquals(1.5,h.shapes.getLast().radius());areaTo(h,21);assertEquals(0,h.areas.size());}
    @Test void derivedBlizzardRetainsIntervalAndTruncatesImpactSchedule(){var p=AftermathProfiles.resolve(f.profiles.require("blizzard"));assertEquals(3,p.area().impactCount());assertEquals(.25,p.area().intervalSeconds());assertEquals(1.2,p.area().impactRadius());assertTrue(p.area().firstImpactSeconds()+(p.area().impactCount()-1)*p.area().intervalSeconds()<p.area().lifetimeSeconds());}
    @Test void lingeredParentUsesFortyPercentOfItsResolvedLifetime(){var h=h("aftermath","lingering");h.start();areaTo(h,11.2);assertEquals(11.2*.4,h.shown.getLast().profile().area().lifetimeSeconds(),1e-9);assertEquals(1,h.writes);}
    @Test void mobileAftermathRemainsFiniteAndTracksCurrentOwner(){var h=h("aftermath","mobile_domain");h.start();areaTo(h,7.75);h.anchor=new Vec3(10,0,0);h.step(8);assertEquals(h.anchor,h.shapes.getLast().origin());h.anchor=new Vec3(12,0,0);h.step(8.25);assertEquals(h.anchor,h.shapes.getLast().origin());areaTo(h,11.2);assertEquals(0,h.areas.size());}
    Stage08ConnectionTest.Harness orb(String skill){var h=new Stage08ConnectionTest.Harness(skill,"aftermath");assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());return h;}
    void connectionTo(Stage08ConnectionTest.Harness h,double end){double now=h.clock.get()/1e9;while(now<end-1e-8){now=Math.min(end,now+.05);h.advance(now);}}
    @Test void orbAftermathStaysAtFinalPointWithoutNewFlight(){var h=orb("ball_lightning");connectionTo(h,5);assertEquals(1,h.runtime.size(),"one aftermath field");assertEquals(18,h.shapes.getLast().start().z(),1e-8);assertEquals(1.8*.6,h.shapes.getLast().radius(),1e-9);connectionTo(h,6.9);assertEquals(18,h.shapes.getLast().start().z(),1e-8);connectionTo(h,7);assertEquals(0,h.runtime.size());assertEquals(1,h.resourceWrites);assertEquals(1,h.tracer.records.stream().filter(r->r.eventType().name().equals("SKILL_COMMITTED")).count());assertFalse(h.kernel.cooldowns().canActivate(h.owner,"ball_lightning"));}
    @Test void orbChildTicksRetainIntervalAndHalfDamageSnapshot(){var h=orb("ball_lightning");h.targets.add(Stage08ConnectionTest.target("a",0,1.35,18));connectionTo(h,7);var children=h.hitContexts.stream().filter(c->c.secondaryKind().equals("aftermath")).toList();assertEquals(2,children.size());assertEquals(.5,children.getFirst().snapshot().modifiers().factor());assertEquals(.75,children.getFirst().profile().connection().intervalSeconds());assertEquals(2,children.getFirst().profile().connection().lifetimeSeconds());}
    @Test void orbitChildRetainsBladeCountAngularSpeedAndContactIcd(){var h=orb("orbiting_shadow_blades");connectionTo(h,10);assertEquals(1,h.runtime.size());var c=h.contexts.getFirst().aftermathCopy();assertEquals(2.8*.6,c.profile().connection().range(),1e-9);assertEquals(.3*.6,c.profile().connection().radius(),1e-9);assertEquals(4,c.profile().connection().details().bladeCount());assertEquals(120,c.profile().connection().details().degreesPerSecond());assertEquals(.75,c.profile().connection().details().contactCooldown());assertEquals(4,c.profile().connection().lifetimeSeconds());connectionTo(h,14);assertEquals(0,h.runtime.size());assertEquals(0,h.capacity.size());}
    @Test void invalidWorldOrOwnerStopsConnectionWithoutAftermath(){var h=orb("ball_lightning");h.validation="OWNER_WORLD_CHANGED";connectionTo(h,.25);assertEquals(0,h.runtime.size());assertEquals(1,h.contexts.getFirst().effects().spawned());}
    @Test void connectionOwnerCancelIsNotNaturalExpiry(){var h=orb("ball_lightning");h.runtime.cancel(h.owner,false);connectionTo(h,7);assertEquals(0,h.runtime.size());assertEquals(1,h.contexts.getFirst().effects().spawned());}
    @Test void everyEligibleCanonicalProfileProducesValidatedFiniteChild(){for(var p:f.profiles.all().values())if(ProfileComponentPolicy.aftermath(p)){var child=AftermathProfiles.resolve(p);assertEquals(p.skillId(),child.skillId());assertTrue(child.area()!=null?child.area().lifetimeSeconds()>0:child.connection().lifetimeSeconds()>0,p.skillId());}}
    @Test void repeatChildrenShareStatusAllowanceAndCannotResetTheRootClock(){var h=h("aftermath","cascade");h.start();var child=h.context.aftermathCopy();assertSame(h.context.effects(),child.effects());h.context.effects().statusApplied("target/POISON",8);assertFalse(child.effects().statusReady("target/POISON",8.25,1));assertTrue(child.effects().statusReady("target/POISON",9,1));}
}
