package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import com.inigmasgames.hytalerpg.execution.support.*;
import com.inigmasgames.hytalerpg.combat.status.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11HitProcTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    static class H extends Stage11ResourcePassivesTest.H {
        H(String skill,String... passives){super(skill);weapon=skill.equals("quick_slash")?"LONGSWORD":skill.equals("quick_shot")?"BOW":"STAFF";
            for(int i=0;i<passives.length;i++)link(passives[i],PassiveSlot.values()[i]);
            var result=cast();if(result.status()==SkillExecutionResult.Status.PENDING)result=service.completeWindup(actor,this);assertFalse(contexts.isEmpty(),result.toString());}
        public SkillExecutionResult executeArea(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeConnection(SkillExecutionContext c){return dispatch(c);}
    }
    static class B {
        UUID victim=UUID.randomUUID();String contact="c",element="PHYSICAL";boolean direct=true,canProc=true,hostile=true,protectedTarget,boss,player,frozen,cancelled;
        double before=100,after=80,min=0,amount=20,coefficient=1;
        HitProcRuntime.Hit hit(){return new HitProcRuntime.Hit(victim,contact,element,direct,canProc,hostile,protectedTarget,boss,player,frozen,cancelled,before,after,min,amount,coefficient);}
    }
    static class P implements HitProcRuntime.Port {
        List<String> traces=new ArrayList<>();List<SkillExecutionContext> children=new ArrayList<>();int bleeds,fears,shatters;double dps,duration,radius,amount;boolean fail;
        public String bleed(SkillExecutionContext c,HitProcRuntime.Hit h,double d,double s){bleeds++;children.add(c);dps=d;duration=s;if(fail)throw new IllegalStateException("fixture native rejection");return "BLEED_APPLIED";}
        public String fear(SkillExecutionContext c,HitProcRuntime.Hit h,double s){fears++;children.add(c);duration=s;if(fail)throw new IllegalStateException("fixture native rejection");return "TERROR_APPLIED";}
        public String shatter(SkillExecutionContext c,HitProcRuntime.Hit h,double r,double a){shatters++;children.add(c);radius=r;amount=a;return "SHATTER_RESOLVED";}
        public void trace(SkillExecutionContext c,String kind,String verdict,double value){traces.add(verdict);}
    }
    void observe(H h,B b,P p){new HitProcRuntime(()->0).observed(h.last(),b.hit(),0,p);}
    @Test void hemorrhageHasPhysicalDirectGate(){assertTrue(f.accepts("quick_slash","hemorrhage"));assertTrue(f.accepts("quick_shot","hemorrhage"));assertFalse(f.accepts("fire_bolt","hemorrhage"));assertFalse(f.accepts("minor_heal","hemorrhage"));}
    @Test void terrorRequiresRealDirectComponent(){assertTrue(f.accepts("snipe","terror"));assertTrue(f.accepts("fire_bolt","terror"));assertFalse(f.accepts("minor_heal","terror"));assertFalse(f.accepts("poison_cloud","terror"));assertFalse(f.accepts("wolf_summon","terror"));}
    @Test void convertedOrbHasADirectContactComponent(){var h=new H("ball_lightning","orbit","terror");assertEquals(com.inigmasgames.hytalerpg.execution.connection.ConnectionProfile.Kind.ORBIT,h.last().profile().connection().kind());}
    @Test void shatterRequiresColdKillCapability(){assertTrue(f.accepts("frost_nova","shatter"));assertTrue(f.accepts("frost_bolt","shatter"));assertFalse(f.accepts("minor_heal","shatter"));assertFalse(f.accepts("quick_slash","shatter"));}
    @Test void bleedTwelvePercentOfResolvedHitNotBasePower(){var h=new H("quick_slash","hemorrhage");var b=new B();b.amount=123;var p=new P();observe(h,b,p);assertEquals(14.76,p.dps,1e-9);assertEquals(4,p.duration);assertEquals(1,p.bleeds);}
    @Test void noExtraResourceOrCooldownForProc(){var h=new H("quick_slash","hemorrhage","terror");var before=new EnumMap<>(h.current);int saves=h.cooldownSaves;var p=new P();observe(h,new B(),p);assertEquals(2,p.children.size());assertEquals(before,h.current);assertEquals(saves,h.cooldownSaves);assertEquals(1,h.contexts.size());}
    @Test void childPreservesRootActorCorrelationAndLedgers(){var h=new H("quick_slash","hemorrhage");var p=new P();observe(h,new B(),p);var c=p.children.getFirst();assertEquals(h.last().rootCastId(),c.rootCastId());assertEquals(h.last().request(),c.request());assertNotEquals(h.last().skillInstanceId(),c.skillInstanceId());assertSame(h.last().effects(),c.effects());assertSame(h.last().leechBudget(),c.leechBudget());assertTrue(c.derivedRelease());}
    @Test void procCannotRecursivelyProcessItsChild(){var h=new H("quick_slash","hemorrhage");var p=new P();observe(h,new B(),p);var c=p.children.getFirst();new HitProcRuntime(()->0).observed(c,new B().hit(),0,p);assertEquals(1,p.bleeds);assertThrows(IllegalStateException.class,()->c.hitProcCopy("terror",2));}
    @Test void cancelledDamageCannotProc(){var h=new H("quick_slash","hemorrhage","terror");var b=new B();b.cancelled=true;var p=new P();observe(h,b,p);assertTrue(p.children.isEmpty());}
    @Test void zeroHealthLossCannotProcFromShieldOnlyHit(){var h=new H("quick_slash","hemorrhage","terror");var b=new B();b.after=b.before;var p=new P();observe(h,b,p);assertTrue(p.children.isEmpty());}
    @Test void periodicCannotRollBleedOrFear(){var h=new H("quick_slash","hemorrhage","terror");var b=new B();b.direct=false;var p=new P();observe(h,b,p);assertTrue(p.children.isEmpty());assertTrue(p.traces.isEmpty());}
    @Test void noProcMetadataSuppressesDirectHitRoll(){var h=new H("quick_slash","hemorrhage","terror");var b=new B();b.canProc=false;var p=new P();observe(h,b,p);assertTrue(p.children.isEmpty());}
    @Test void hostileProtectedAndPlayerPolicies(){for(int i=0;i<3;i++){var h=new H("quick_slash","hemorrhage","terror");var b=new B();if(i==0)b.hostile=false;if(i==1)b.protectedTarget=true;if(i==2)b.player=true;var p=new P();observe(h,b,p);assertTrue(p.children.isEmpty());}}
    @Test void bossMayBleedButCannotReceiveTerror(){var h=new H("quick_slash","hemorrhage","terror");var b=new B();b.boss=true;var p=new P();observe(h,b,p);assertEquals(1,p.bleeds);assertEquals(0,p.fears);}
    @Test void chanceIsWeightedAndUsesStrictBoundary(){var h=new H("quick_slash","hemorrhage");var b=new B();b.coefficient=.5;var p=new P();new HitProcRuntime(()->.125).observed(h.last(),b.hit(),0,p);assertEquals(0,p.bleeds);assertTrue(p.traces.contains("PROC_ROLL_MISS"));}
    @Test void terrorChanceIsFifteenPercent(){var h=new H("quick_slash","terror");var p=new P();new HitProcRuntime(()->.15).observed(h.last(),new B().hit(),0,p);assertEquals(0,p.fears);}
    @Test void invalidRollIsTypedAndDoesNotCreateEffect(){var h=new H("quick_slash","hemorrhage");var p=new P();new HitProcRuntime(()->Double.NaN).observed(h.last(),new B().hit(),0,p);assertTrue(p.traces.contains("INVALID_PROC_ROLL"));assertTrue(p.children.isEmpty());}
    @Test void malformedReceiptCannotRoll(){var h=new H("quick_slash","hemorrhage");var b=new B();b.amount=Double.NaN;var p=new P();observe(h,b,p);assertTrue(p.traces.contains("INVALID_NATIVE_RECEIPT"));assertTrue(p.children.isEmpty());}
    @Test void duplicateNativeReceiptCannotReroll(){var h=new H("quick_slash","hemorrhage");var b=new B();var p=new P();var r=new HitProcRuntime(()->0);r.observed(h.last(),b.hit(),0,p);r.observed(h.last(),b.hit(),0,p);assertEquals(1,p.bleeds);assertTrue(p.traces.contains("DUPLICATE_PROC_CONTACT"));}
    @Test void rootContactMemoryCannotGrowBeyond256(){var root=new RootEffectBudget(UUID.randomUUID(),"r");for(int i=0;i<256;i++)assertEquals("PASS",root.claimProcContact("c"+i));assertEquals("ROOT_PROC_CONTACT_BUDGET",root.claimProcContact("more"));assertEquals("DUPLICATE_PROC_CONTACT",root.claimProcContact("c1"));}
    @Test void triggerBudgetCapsEffectsAt16(){var h=new H("quick_slash","hemorrhage");var p=new P();var r=new HitProcRuntime(()->0);for(int i=0;i<20;i++)r.observed(h.last(),new B().hit(),0,p);assertEquals(16,p.bleeds);assertEquals(16,h.last().effects().triggered());assertTrue(p.traces.contains("ROOT_TRIGGERED_SECONDARY_BUDGET"));}
    @Test void nativeFailureDoesNotRefundOrReopenProc(){var h=new H("quick_slash","hemorrhage");var before=new EnumMap<>(h.current);var p=new P();p.fail=true;var b=new B();var r=new HitProcRuntime(()->0);r.observed(h.last(),b.hit(),0,p);r.observed(h.last(),b.hit(),0,p);assertEquals(1,p.bleeds);assertEquals(before,h.current);assertTrue(p.traces.stream().anyMatch(t->t.contains("PAID_ROOT_RETAINED")));}
    @Test void terrorOnePointFiveSecondsAndEightSecondVictimIcd(){var h=new H("quick_slash","terror");var p=new P();var b=new B();var r=new HitProcRuntime(()->0);r.observed(h.last(),b.hit(),0,p);assertEquals(1.5,p.duration);b.contact="next";r.observed(h.last(),b.hit(),7.99,p);assertEquals(1,p.fears);b.contact="third";r.observed(h.last(),b.hit(),8,p);assertEquals(2,p.fears);}
    @Test void terrorVictimIcdIsPerCaster(){var first=new H("quick_slash","terror");var second=new H("quick_slash","terror");var r=new HitProcRuntime(()->0);var b=new B();var p=new P();r.observed(first.last(),b.hit(),0,p);r.observed(second.last(),b.hit(),0,p);assertEquals(2,p.fears);}
    @Test void terrorTeardownClearsItsBoundedOwnerState(){var h=new H("quick_slash","terror");var r=new HitProcRuntime(()->0);r.observed(h.last(),new B().hit(),0,new P());assertEquals(1,r.size());r.cancel(h.actor);assertEquals(0,r.size());}
    @Test void failedNativeFearKeepsIcdForUncertainResult(){var h=new H("quick_slash","terror");var p=new P();p.fail=true;var b=new B();var r=new HitProcRuntime(()->0);r.observed(h.last(),b.hit(),0,p);b.contact="next";r.observed(h.last(),b.hit(),1,p);assertEquals(1,p.fears);assertTrue(p.traces.contains("TERROR_TARGET_ICD"));}
    @Test void killingFrozenColdHitShattersHalfPremitigation(){var h=new H("frost_bolt","shatter");var b=new B();b.element="COLD";b.after=0;b.frozen=true;b.amount=200;var p=new P();observe(h,b,p);assertEquals(1,p.shatters);assertEquals(3,p.radius);assertEquals(100,p.amount);}
    @Test void slowSubstituteIsNotFrozen(){var h=new H("frost_bolt","shatter");var b=new B();b.element="COLD";b.after=0;var p=new P();observe(h,b,p);assertEquals(0,p.shatters);}
    @Test void survivingFrozenTargetDoesNotShatter(){var h=new H("frost_bolt","shatter");var b=new B();b.element="COLD";b.frozen=true;var p=new P();observe(h,b,p);assertEquals(0,p.shatters);}
    @Test void shatterDeduplicatesVictimEvenWithDifferentContact(){var h=new H("frost_bolt","shatter");var b=new B();b.element="COLD";b.after=0;b.frozen=true;var p=new P();var r=new HitProcRuntime(()->0);r.observed(h.last(),b.hit(),0,p);b.contact="duplicate-death";r.observed(h.last(),b.hit(),0,p);assertEquals(1,p.shatters);assertTrue(p.traces.contains("DUPLICATE_EFFECT"));}
    @Test void primaryColdPulseKillMayShatterWithoutHitProcs(){var h=new H("frost_bolt","shatter");var b=new B();b.direct=false;b.canProc=false;b.element="COLD";b.after=0;b.frozen=true;var p=new P();observe(h,b,p);assertEquals(1,p.shatters);}
    @Test void shatterExplosionCannotShatterAgain(){var h=new H("frost_bolt","shatter");var b=new B();b.element="COLD";b.after=0;b.frozen=true;var p=new P();var r=new HitProcRuntime(()->0);r.observed(h.last(),b.hit(),0,p);r.observed(p.children.getFirst(),b.hit(),0,p);assertEquals(1,p.shatters);}
    @Test void volleyAndNativeOrbitWeightSimultaneousProcChance(){var shot=new H("quick_shot","hemorrhage","volley");assertEquals(1d/3,HitProcRuntime.coefficient(shot.last()));var orbit=new H("fire_bolt","terror","orbit","volley");assertEquals(1d/3,HitProcRuntime.coefficient(orbit.last()));}
    @Test void fearReusesFiniteSupportDamageBreakGrace(){var h=new H("quick_slash","terror");var p=new P();observe(h,new B(),p);UUID victim=UUID.randomUUID(),world=UUID.randomUUID();var child=HitProcProfiles.fear(p.children.getFirst(),victim,world,Vec3.ZERO,Vec3.FORWARD,1.5);var effects=new FiniteSupportEffects();effects.apply(child,List.of(victim),1.5,0);assertFalse(effects.directDamage(world,victim,.24,true,true));assertFalse(effects.directDamage(world,victim,.3,false,true));assertTrue(effects.directDamage(world,victim,.25,true,true));assertTrue(effects.control(world,victim,SupportProfile.Kind.FEAR,.25).isEmpty());assertEquals(h.last().profile().skillId(),child.profile().skillId());assertNull(h.last().profile().support());}
    @Test void terrorUsesExistingEliteAndBossStatusPolicy(){var status=com.inigmasgames.hytalerpg.combat.RpgCombatKernel.createProduction().statuses();assertEquals(.75,status.apply(UUID.randomUUID(),RpgStatusType.FEAR,new ControlProfile(false,false,false,true),1.5).remainingSeconds(),1e-9);assertEquals(StatusService.Outcome.REJECTED,status.apply(UUID.randomUUID(),RpgStatusType.FEAR,new ControlProfile(false,true,false),1.5).outcome());}
    static class D implements PeriodicStatusRuntime.Port<String,String>{double total;List<String> contexts=new ArrayList<>();public boolean tick(PeriodicStatusRuntime.Source s,String c,String t,int i,double coefficient,double seconds){total+=coefficient;contexts.add(c);return true;}public void changed(PeriodicStatusRuntime.Source s,String t,PeriodicStatusRuntime.View v){}}
    @Test void bleedUsesExistingFourSecondTimerWithResolvedDps(){var runtime=new PeriodicStatusRuntime<String,String>();var owner=UUID.randomUUID();var source=new PeriodicStatusRuntime.Source(owner,"quick_slash",UUID.randomUUID(),PeriodicStatusRuntime.Kind.BLEED);var p=new D();runtime.apply(source,"resolved-12-dps","target",12,12,4,1,1,0,p);for(int i=1;i<=4;i++)runtime.tick(owner,i,p);assertEquals(48,p.total);assertEquals(0,runtime.size());assertEquals(4,p.contexts.size());}
    @Test void weakerBleedRefreshKeepsStrongestWithoutStacking(){var runtime=new PeriodicStatusRuntime<String,String>();var owner=UUID.randomUUID();var source=new PeriodicStatusRuntime.Source(owner,"quick_slash",UUID.randomUUID(),PeriodicStatusRuntime.Kind.BLEED);var p=new D();runtime.apply(source,"strong","target",12,12,4,3,3,0,p);runtime.apply(source,"weak","target",2,2,4,3,3,.5,p);assertEquals(1,runtime.sourceView(source,.5).orElseThrow().stacks());assertEquals(12,runtime.sourceView(source,.5).orElseThrow().coefficientPerSecond());for(double t=1;t<=4;t++)runtime.tick(owner,t,p);runtime.tick(owner,4.5,p);assertEquals(54,p.total,1e-9);assertEquals(Set.of("strong"),new HashSet<>(p.contexts));}
    @Test void bleedVisualProjectionIsNotAnotherDamageTimer(){var status=com.inigmasgames.hytalerpg.combat.RpgCombatKernel.createProduction().statuses();var id=UUID.randomUUID();status.projectPeriodic(id,RpgStatusType.BLEED,1,4);assertEquals(1,status.inspect(id).active().get(RpgStatusType.BLEED).stacks());status.projectPeriodic(id,RpgStatusType.BLEED,0,0);assertFalse(status.inspect(id).active().containsKey(RpgStatusType.BLEED));}
}
