package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.area.AreaGeometry.Bounds;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import com.inigmasgames.hytalerpg.execution.projectile.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11ConditionalRepeatTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    static class H extends Stage11ResourcePassivesTest.H{
        CommittedTarget kill;boolean valid=true,failTarget;int targetQueries;
        H(String skill,String... passives){super(skill);weapon=skill.equals("quick_slash")?"LONGSWORD":"STAFF";
            for(int i=0;i<passives.length;i++)link(passives[i],PassiveSlot.values()[i]);
            var result=cast();if(result.status()==SkillExecutionResult.Status.PENDING)result=service.completeWindup(actor,this);assertEquals(SkillExecutionResult.Status.COMMITTED,result.status(),result.toString());
            kill=new CommittedTarget(actor,Vec3.ZERO,new Vec3(0,0,3),Vec3.FORWARD,UUID.randomUUID());}
        public SkillExecutionResult executeArea(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeConnection(SkillExecutionContext c){return dispatch(c);}
        public Validation validateRelease(SkillExecutionContext c){return valid?Validation.pass():Validation.reject("FIXTURE_TARGET_INVALID");}
        public CommittedTarget conditionalKillTarget(SkillExecutionContext c,ConditionalRepeatRuntime.Hit h){targetQueries++;if(failTarget)throw new IllegalStateException("fixture target failure");return kill;}
        String observe(B b){return service.observedConditionalRepeat(contexts.getFirst(),b.hit(),this);}
        void tick(double at){time=at;service.tickScheduled(actor,this);}
    }
    static class B{
        UUID victim=UUID.randomUUID();boolean root=true,direct=true,canProc=true,crit=true,hostile=true,protectedTarget,cancelled;double before=100,after=80,min;
        ConditionalRepeatRuntime.Hit hit(){return new ConditionalRepeatRuntime.Hit(victim,Vec3.ZERO,root,direct,canProc,crit,hostile,protectedTarget,cancelled,before,after,min);}
        B lethal(){after=0;return this;}
    }
    @Test void criticalRequiresDirectRepeatableComponent(){assertTrue(f.accepts("snipe","critical_trigger"));assertTrue(f.accepts("fire_bolt","critical_trigger"));assertFalse(f.accepts("chilling_aura","critical_trigger"));assertFalse(f.accepts("poison_cloud","critical_trigger"));assertFalse(f.accepts("quickstep","critical_trigger"));assertFalse(f.accepts("wolf_summon","critical_trigger"));}
    @Test void killExcludesConsumersAndSupport(){assertTrue(f.accepts("fireball","kill_trigger"));assertFalse(f.accepts("corpse_burst","kill_trigger"));assertFalse(f.accepts("wolf_summon","kill_trigger"));assertFalse(f.accepts("minor_heal","kill_trigger"));assertFalse(f.accepts("quickstep","kill_trigger"));}
    @Test void exclusiveRepeatControllersRollback(){for(String other:List.of("echo","barrage","retaliation","kill_trigger")){var h=new H("fire_bolt","critical_trigger");assertTrue(h.b.service().equipPassive(h.actor,PassiveSlot.PASSIVE02,new PassiveId(other)).success());var before=h.b.service().getPresentationView(h.actor).state().linkEdges();assertFalse(h.b.service().link(h.actor,LinkNodeId.PASSIVE02,LinkNodeId.SKILL01).success(),other);assertEquals(before,h.b.service().getPresentationView(h.actor).state().linkEdges());}}
    @Test void criticalWaitsExactlyPointTwoThenRunsOnce(){var h=new H("fire_bolt","critical_trigger");assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.observe(new B()));assertEquals(1,h.service.pendingReleaseCount());h.tick(.199);assertEquals(1,h.contexts.size());h.tick(.20);assertEquals(2,h.contexts.size());h.tick(2);assertEquals(2,h.contexts.size());assertEquals(0,h.service.pendingReleaseCount());}
    @Test void criticalChildHasHalfMagnitudeAndSameIdentityChain(){var h=new H("fire_bolt","critical_trigger","potency");var root=h.last();h.observe(new B());h.tick(.2);var child=h.last();assertEquals(root.snapshot().modifiers().factor()*.5,child.snapshot().modifiers().factor(),1e-9);assertEquals(root.rootCastId(),child.rootCastId());assertEquals(root.request(),child.request());assertEquals(root.target(),child.target());assertNotEquals(root.skillInstanceId(),child.skillInstanceId());assertSame(root.effects(),child.effects());assertSame(root.leechBudget(),child.leechBudget());assertTrue(child.derivedRelease());assertTrue(child.conditionalRepeat());}
    @Test void noAdditionalManaStaminaHealthOrCooldownSave(){var h=new H("fire_bolt","critical_trigger");var resources=new EnumMap<>(h.current);int saves=h.cooldownSaves;h.observe(new B());h.tick(.2);assertEquals(resources,h.current);assertEquals(saves,h.cooldownSaves);assertEquals(0,h.healthWrites);}
    @Test void derivedCriticalCannotRepeat(){var h=new H("fire_bolt","critical_trigger");h.observe(new B());h.tick(.2);assertEquals("NOT_ROOT_REPEAT_SOURCE",h.service.observedConditionalRepeat(h.last(),new B().hit(),h));h.tick(4);assertEquals(2,h.contexts.size());}
    @Test void noCriticalRetargetQuery(){var h=new H("fire_bolt","critical_trigger");h.observe(new B());assertEquals(0,h.targetQueries);}
    @Test void criticalCannotUseANewSolution(){var h=new H("fire_bolt","critical_trigger");assertThrows(IllegalStateException.class,()->h.last().conditionalCopy(h.kill));}
    @Test void cancelledHitDoesNotSchedule(){var h=new H("fire_bolt","critical_trigger");var b=new B();b.cancelled=true;assertEquals("NO_HOSTILE_NATIVE_HEALTH_LOSS",h.observe(b));assertEquals(0,h.service.pendingReleaseCount());}
    @Test void shieldOnlyCriticalDoesNotSchedule(){var h=new H("fire_bolt","critical_trigger");var b=new B();b.after=100;assertEquals("NO_HOSTILE_NATIVE_HEALTH_LOSS",h.observe(b));}
    @Test void nonCriticalDoesNotSchedule(){var h=new H("fire_bolt","critical_trigger");var b=new B();b.crit=false;assertEquals("CONDITION_NOT_MET",h.observe(b));}
    @Test void periodicCannotCriticalTrigger(){var h=new H("fire_bolt","critical_trigger");var b=new B();b.direct=false;assertEquals("CONDITION_NOT_MET",h.observe(b));}
    @Test void noProcCannotCriticalTrigger(){var h=new H("fire_bolt","critical_trigger");var b=new B();b.canProc=false;assertEquals("CONDITION_NOT_MET",h.observe(b));}
    @Test void childCarrierCannotScheduleRootRepeat(){var h=new H("fire_bolt","critical_trigger");var b=new B();b.root=false;assertEquals("NOT_ROOT_REPEAT_SOURCE",h.observe(b));}
    @Test void friendlyAndProtectedHitsCannotRepeat(){for(int i=0;i<2;i++){var h=new H("fire_bolt","critical_trigger");var b=new B();if(i==0)b.hostile=false;else b.protectedTarget=true;assertEquals("NO_HOSTILE_NATIVE_HEALTH_LOSS",h.observe(b));}}
    @Test void alreadyDeadTargetCannotSchedule(){var h=new H("fire_bolt","kill_trigger");var b=new B().lethal();b.before=0;assertEquals("NO_HOSTILE_NATIVE_HEALTH_LOSS",h.observe(b));}
    @Test void originalTargetInvalidCancelsWithoutRefund(){var h=new H("fire_bolt","critical_trigger");var before=new EnumMap<>(h.current);h.observe(new B());h.valid=false;h.tick(.2);assertEquals(1,h.contexts.size());assertEquals(0,h.service.pendingReleaseCount());assertEquals(before,h.current);}
    @Test void ownerUnusableCancelsQueuedChild(){var h=new H("fire_bolt","critical_trigger");h.observe(new B());h.alive=false;h.tick(.2);assertEquals(1,h.contexts.size());assertEquals(0,h.service.pendingReleaseCount());}
    @Test void loadoutChangeCancelsAndOldProjectileCannotRearm(){var h=new H("fire_bolt","critical_trigger");h.observe(new B());assertTrue(h.b.service().unequipSkill(h.actor,SkillSlot.SKILL01).success());assertEquals(0,h.service.pendingReleaseCount());assertEquals("COMMITTED_LOADOUT_CHANGED",h.observe(new B()));h.tick(.2);assertEquals(1,h.contexts.size());}
    @Test void nativeReleaseFailureCannotReplayOrRefund(){var h=new H("fire_bolt","critical_trigger");h.observe(new B());h.failDispatch=true;var before=new EnumMap<>(h.current);h.tick(.2);h.tick(4);assertEquals(2,h.contexts.size());assertEquals(0,h.service.pendingReleaseCount());assertEquals(before,h.current);}
    @Test void killSchedulesOneAtNewTargetWithoutCritical(){var h=new H("fire_bolt","kill_trigger");var b=new B().lethal();b.crit=false;assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.observe(b));assertEquals(1,h.contexts.size());h.tick(0);assertEquals(2,h.contexts.size());assertEquals(h.kill,h.last().target());assertEquals(.5,h.last().snapshot().modifiers().factor(),1e-9);}
    @Test void killRequiresAuthoritativeLethalLoss(){var h=new H("fire_bolt","kill_trigger");assertEquals("CONDITION_NOT_MET",h.observe(new B()));assertEquals(0,h.targetQueries);}
    @Test void rootPeriodicKillMayScheduleButNeverCritical(){var h=new H("fire_bolt","kill_trigger");var b=new B().lethal();b.direct=false;b.canProc=false;b.crit=false;assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.observe(b));}
    @Test void noValidKillTargetSpawnsNothing(){var h=new H("fire_bolt","kill_trigger");h.kill=null;assertEquals("NO_VALID_REPEAT_TARGET",h.observe(new B().lethal()));h.tick(1);assertEquals(1,h.contexts.size());assertEquals("ROOT_REPEAT_ALREADY_CLAIMED",h.observe(new B().lethal()));}
    @Test void killTargetQueryFailureIsContained(){var h=new H("fire_bolt","kill_trigger");h.failTarget=true;assertTrue(h.observe(new B().lethal()).startsWith("CONDITIONAL_REPEAT_OBSERVER_FAILED"));assertEquals(0,h.service.pendingReleaseCount());}
    @Test void invalidKilledTargetSolutionWorldRejected(){var h=new H("fire_bolt","kill_trigger");h.kill=new CommittedTarget(UUID.randomUUID(),Vec3.ZERO,Vec3.FORWARD,Vec3.FORWARD,UUID.randomUUID());assertTrue(h.observe(new B().lethal()).startsWith("CONDITIONAL_REPEAT_OBSERVER_FAILED"));}
    @Test void duplicateRootCannotRepeatAfterIcdExpires(){var h=new H("fire_bolt","critical_trigger");h.observe(new B());h.tick(3);assertEquals("ROOT_REPEAT_ALREADY_CLAIMED",h.observe(new B()));}
    @Test void criticalIcdIsOnePointFiveSecondsAcrossRoots(){var h=new H("quick_slash","critical_trigger");var first=h.last();h.observe(new B());h.tick(.2);h.service.terminate(h.contexts.getFirst(),"FIXTURE_PAIR_COMPLETE");h.ready();assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());var next=h.last();assertEquals("CONDITIONAL_REPEAT_ICD",h.service.observedConditionalRepeat(next,new B().hit(),h));h.time=1.5;assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.service.observedConditionalRepeat(next,new B().hit(),h));}
    @Test void killIcdIsOneSecondAcrossRoots(){var h=new H("quick_slash","kill_trigger");h.observe(new B().lethal());h.tick(0);h.service.terminate(h.contexts.getFirst(),"FIXTURE_PAIR_COMPLETE");h.ready();assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());var next=h.last();assertEquals("CONDITIONAL_REPEAT_ICD",h.service.observedConditionalRepeat(next,new B().lethal().hit(),h));h.time=1;assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.service.observedConditionalRepeat(next,new B().lethal().hit(),h));}
    @Test void explicitCancellationInvalidatesClaimedRelease(){var h=new H("fire_bolt","critical_trigger");var q=new SkillReleaseScheduler();var child=h.last().conditionalCopy(h.last().target());assertEquals("PASS",q.conditional(child,.2));var claim=q.due(h.actor,.2).getFirst();q.cancel(h.actor);assertFalse(q.isCurrent(claim));}
    @Test void queueCapsAndDuplicateChildAreTyped(){var h=new H("fire_bolt","critical_trigger");var q=new SkillReleaseScheduler();for(int i=0;i<6;i++){if(i>0){h.ready();h.cast();}var c=h.last().conditionalCopy(h.last().target());assertEquals("PASS",q.conditional(c,.2));assertEquals("DUPLICATE_RELEASE_RESERVATION",q.conditional(c,.2));}h.ready();h.cast();assertEquals("OWNER_RELEASE_BUDGET",q.conditional(h.last().conditionalCopy(h.last().target()),.2));}
    @Test void rootSecondaryLimitAlsoAppliesToRepeat(){var h=new H("fire_bolt","critical_trigger");for(int i=0;i<16;i++)assertEquals("PASS",h.last().effects().claim("fixture-"+i,2,true));assertEquals("ROOT_TRIGGERED_SECONDARY_BUDGET",h.observe(new B()));}
    @Test void volleyClaimsAllThreeDerivedLaunches(){var h=new H("fire_bolt","critical_trigger","volley");assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.observe(new B()));assertEquals(3,h.last().effects().triggered());}
    @Test void skillDelayIsNotAppliedAgainToCriticalRepeat(){var h=new HDelayed();h.time=2;h.service.tickScheduled(h.actor,h);assertEquals(1,h.contexts.size());assertEquals("CONDITIONAL_REPEAT_SCHEDULED",h.service.observedConditionalRepeat(h.last(),new B().hit(),h));h.time=2.2;h.service.tickScheduled(h.actor,h);assertEquals(2,h.contexts.size());}
    static class HDelayed extends Stage11ResourcePassivesTest.H{HDelayed(){super("fire_bolt");weapon="STAFF";link("critical_trigger",PassiveSlot.PASSIVE01);link("skill_delay",PassiveSlot.PASSIVE02);assertEquals(SkillExecutionResult.Status.COMMITTED,cast().status());}}
    ConditionalKillTargeting.Target target(UUID world,UUID id,double x,boolean legal){var point=new Vec3(x,0,0);return new ConditionalKillTargeting.Target(id,new Bounds(point,point),new CommittedTarget(world,Vec3.ZERO,point,Vec3.FORWARD,id),true,true,false,true,legal);}
    @Test void killSelectsNearestWithinTwelveAndCasterReach(){UUID world=UUID.randomUUID(),dead=UUID.randomUUID();var nearest=target(world,UUID.randomUUID(),2,true);assertEquals(nearest.solution(),ConditionalKillTargeting.nearest(dead,Vec3.ZERO,List.of(target(world,UUID.randomUUID(),1,false),nearest,target(world,UUID.randomUUID(),5,true),target(world,UUID.randomUUID(),13,true)),false));}
    @Test void killTargetTiesAreDeterministic(){UUID world=UUID.randomUUID();var first=target(world,new UUID(0,1),2,true);var second=target(world,new UUID(0,2),-2,true);assertEquals(first.solution(),ConditionalKillTargeting.nearest(UUID.randomUUID(),Vec3.ZERO,List.of(second,first),false));}
    @Test void killRejectsDeadVictimAndInvalidRelations(){UUID world=UUID.randomUUID(),dead=UUID.randomUUID();var t=target(world,UUID.randomUUID(),2,true);var invalid=new ConditionalKillTargeting.Target(t.id(),t.bounds(),t.solution(),true,false,false,true,true);assertNull(ConditionalKillTargeting.nearest(dead,Vec3.ZERO,List.of(target(world,dead,1,true),invalid),false));}
    @Test void killQueryOverflowFailsClosed(){assertThrows(IllegalStateException.class,()->ConditionalKillTargeting.nearest(UUID.randomUUID(),Vec3.ZERO,List.of(),true));}
    @Test void killUsesFullThreeDimensionalBounds(){UUID world=UUID.randomUUID(),id=UUID.randomUUID();var t=target(world,id,0,true);var high=new ConditionalKillTargeting.Target(id,new Bounds(new Vec3(0,13,0),new Vec3(1,14,1)),t.solution(),true,true,false,true,true);assertNull(ConditionalKillTargeting.nearest(UUID.randomUUID(),Vec3.ZERO,List.of(high),false));}
    @Test void malformedHealthReceiptRejected(){var b=new B();b.after=Double.NaN;assertThrows(IllegalArgumentException.class,b::hit);}
    List<ProjectileInstance> batch(SkillExecutionContext c){return ProjectileExecutionPlan.launchBatch(c,c.request().actorId(),Vec3.ZERO,Vec3.FORWARD,"fixture",10,0).stream().map(ProjectileInstance::new).toList();}
    @Test void delayedProjectileRepeatRetainsRegistryAfterLastCarrierGone(){var h=new H("fire_bolt","critical_trigger");var root=h.last();var registry=new ProjectileLifecycleRegistry();var original=batch(root);registry.registerAll(original,root.effects().projectileLifetime());registry.remove(original.getFirst());assertEquals(0,registry.rootCount());var child=root.conditionalCopy(root.target());registry.registerConditionalAll(batch(child),root.effects().projectileLifetime());assertEquals(2,registry.spent(h.actor,root.rootCastId()));assertEquals(1,registry.triggered(h.actor,root.rootCastId()));}
    @Test void conditionalProjectileCannotResetSixteenSecondaryLimit(){var h=new H("fire_bolt","critical_trigger");var root=h.last();var registry=new ProjectileLifecycleRegistry();var original=batch(root);registry.registerAll(original,root.effects().projectileLifetime());for(int i=0;i<16;i++)assertEquals("PASS",registry.reserveSecondary(original.getFirst(),"f"+i));registry.remove(original.getFirst());assertThrows(IllegalStateException.class,()->registry.registerConditionalAll(batch(root.conditionalCopy(root.target())),root.effects().projectileLifetime()));assertEquals(0,registry.size());}
    @Test void continuationStatusKillCannotBecomeARootKill(){var h=new H("fire_bolt","kill_trigger");var root=h.last();var child=root.projectileStatusChild("fork-child");assertEquals("NOT_ROOT_REPEAT_SOURCE",h.service.observedConditionalRepeat(child,new B().lethal().hit(),h));assertSame(root.effects(),child.effects());assertEquals(root.rootCastId(),child.rootCastId());assertEquals(root.snapshot().modifiers(),child.snapshot().modifiers());assertNotEquals(root.skillInstanceId(),child.skillInstanceId());}
    @Test void derivedStatusCopyKeepsExistingChildIdentity(){var h=new H("fire_bolt","critical_trigger");var child=h.last().conditionalCopy(h.last().target());assertSame(child,child.projectileStatusChild("child-carrier"));}
    @Test void shrapnelCannotScheduleKillRepeat(){var h=new H("fire_bolt","kill_trigger");var b=new B().lethal();b.canProc=false;b.root=false;assertEquals("NOT_ROOT_REPEAT_SOURCE",h.observe(b));}
    @Test void conditionalDuplicateCannotReplayAfterAllCarriersEnd(){var h=new H("fire_bolt","critical_trigger");var root=h.last();var registry=new ProjectileLifecycleRegistry();var original=batch(root);registry.registerAll(original,root.effects().projectileLifetime());var child=batch(root.conditionalCopy(root.target()));registry.registerConditionalAll(child,root.effects().projectileLifetime());registry.remove(original.getFirst());registry.remove(child.getFirst());assertThrows(IllegalStateException.class,()->registry.registerConditionalAll(child,root.effects().projectileLifetime()));assertEquals(0,registry.size());}
    @Test void foreignProjectileLifetimeRejected(){var h=new H("fire_bolt","critical_trigger");var registry=new ProjectileLifecycleRegistry();registry.registerAll(batch(h.last()),h.last().effects().projectileLifetime());var other=new H("fire_bolt","critical_trigger");assertThrows(IllegalStateException.class,()->registry.registerConditionalAll(batch(other.last().conditionalCopy(other.last().target())),h.last().effects().projectileLifetime()));}
    @Test void originalProjectileLaunchCannotRestartAfterCleanup(){var h=new H("fire_bolt","critical_trigger");var registry=new ProjectileLifecycleRegistry();var original=batch(h.last());registry.registerAll(original,h.last().effects().projectileLifetime());original.forEach(registry::remove);assertThrows(IllegalStateException.class,()->registry.registerAll(original,h.last().effects().projectileLifetime()));}
    @Test void fortyEightProjectileEffectsRemainSpentAfterCleanup(){
        var h=new H("fire_bolt","critical_trigger");var root=h.last();var registry=new ProjectileLifecycleRegistry();var originals=batch(root);registry.registerAll(originals,root.effects().projectileLifetime());var p=originals.getFirst().plan();
        for(int i=0;i<47;i++){var child=new ProjectileInstance(new ProjectileExecutionPlan(p.rootCastId(),p.skillInstanceId(),"fixture-child-"+i,p.ownerId(),p.skillId(),p.compiledPlanHash(),p.snapshot(),1,Map.of("IS_LAUNCH",0),0,0,0,p.configId(),p.origin(),p.velocity(),p.radius(),p.maxDistance(),p.maxLifetimeSeconds()));registry.registerAll(List.of(child));registry.remove(child);}
        assertEquals(48,registry.spent(h.actor,root.rootCastId()));registry.remove(originals.getFirst());assertThrows(IllegalStateException.class,()->registry.registerConditionalAll(batch(root.conditionalCopy(root.target())),root.effects().projectileLifetime()));assertEquals(0,registry.size());
    }
    @Test void removingConditionalQueueDoesNotRemoveAnEchoReservation(){var h=new H("fire_bolt","critical_trigger");var q=new SkillReleaseScheduler();var child=h.last().conditionalCopy(h.last().target());q.conditional(child,.2);assertEquals("PASS",q.reserve("echo",h.actor,SkillSlot.SKILL02,new CompiledSkillPlan.ExecutionModifiers(1,0,.45,.7,false)));assertEquals(List.of(child),q.cancelConditional(h.actor));assertEquals(1,q.size());}
    @Test void missingNativeProjectileRootCannotBeInvented(){var h=new H("fire_bolt","critical_trigger");assertThrows(IllegalStateException.class,()->new ProjectileLifecycleRegistry().registerConditionalAll(batch(h.last().conditionalCopy(h.last().target())),h.last().effects().projectileLifetime()));}
    @Test void volleyConditionalRestoresExactlyThreePromises(){var h=new H("fire_bolt","critical_trigger","volley");var root=h.last();var registry=new ProjectileLifecycleRegistry();var original=batch(root);registry.registerAll(original,root.effects().projectileLifetime());original.forEach(registry::remove);var child=batch(root.conditionalCopy(root.target()));registry.registerConditionalAll(child,root.effects().projectileLifetime());assertEquals(3,registry.size());assertEquals(6,registry.spent(h.actor,root.rootCastId()));assertEquals(3,registry.triggered(h.actor,root.rootCastId()));}
}
