package com.inigmasgames.hytalerpg;
import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.support.*;
import com.inigmasgames.hytalerpg.combat.resource.ResourceType;
import com.inigmasgames.hytalerpg.combat.hytale.HytaleDamageMetadata;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11RetaliationTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    static class H extends Stage11ResourcePassivesTest.H{
        boolean targetValid=true;double hpMax=100;int losses;
        H(String skill,String... extra){super(skill);weapon=Set.of("quick_slash","heavy_swing").contains(skill)?"LONGSWORD":"STAFF";link("retaliation",PassiveSlot.PASSIVE01);for(int i=0;i<extra.length;i++)link(extra[i],PassiveSlot.values()[i+1]);}
        public double maximum(ResourceType type){return type==ResourceType.HEALTH?hpMax:super.maximum(type);}
        public Validation familyPrerequisites(Stage04SkillProfile p,CompiledSkillPlan plan){return targetValid?Validation.pass():Validation.reject("FIXTURE_TARGET_MISSING");}
        public SkillExecutionResult executeArea(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeConnection(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeSupport(SkillExecutionContext c){return dispatch(c);}
        public SkillExecutionResult executeSummon(SkillExecutionContext c){return dispatch(c);}
        String loss(double n){return service.observeRetaliation(actor,"native-fixture-"+(++losses),hpMax,hpMax-n,hpMax,true,false);}
        SkillExecutionResult tick(){return service.tickRetaliation(actor,this);}
        double total(){return service.retaliationAccumulated(actor,SkillSlot.SKILL01);}
    }
    static class L{
        final UUID actor=UUID.randomUUID();final RetaliationLedger l=new RetaliationLedger();final Map<SkillSlot,String> plans=Map.of(SkillSlot.SKILL01,"plan-a");
        String loss(String id,double value,double now){return l.observe(actor,plans,id,100,100-value,100,true,false,now);}
        Optional<RetaliationLedger.Ticket> claim(double at){return l.claim(actor,plans,100,at);}
        double total(double at){return l.accumulated(actor,SkillSlot.SKILL01,at);}
    }
    @Test void compatibilityUsesDiscreteNonConsumerBoundary(){assertTrue(f.accepts("frost_nova","retaliation"));assertTrue(f.accepts("fire_bolt","retaliation"));assertFalse(f.accepts("corpse_burst","retaliation"));assertFalse(f.accepts("consume_minion","retaliation"));assertFalse(f.accepts("quickstep","retaliation"));assertFalse(f.accepts("chilling_aura","retaliation"));assertFalse(f.accepts("revive_fallen","retaliation"));}
    @Test void manualActivationIsDisabledBeforeAnyPayment(){var h=new H("quick_slash");assertEquals("RETALIATION_MANUAL_DISABLED",h.cast().code());assertEquals(100,h.current(ResourceType.STAMINA));assertEquals(0,h.cooldownSaves);assertTrue(h.contexts.isEmpty());}
    @Test void TriggeredOriginWithoutNativeReceiptCannotSpoofRetaliation(){var h=new H("quick_slash");assertEquals("RETALIATION_RECEIPT_REQUIRED",h.cast(SkillSlot.SKILL01,SkillExecutionRequest.Origin.TRIGGERED).code());assertEquals(0,h.cooldownSaves);}
    @Test void fourteenPercentDoesNotCast(){var h=new H("quick_slash");h.loss(14);assertNull(h.tick());assertTrue(h.contexts.isEmpty());assertEquals(14,h.total());}
    @Test void fifteenPercentQueuesButDoesNotExecuteInsideObservation(){var h=new H("quick_slash");assertEquals("RETALIATION_LOSS_RECORDED",h.loss(15));assertTrue(h.contexts.isEmpty());assertEquals(SkillExecutionResult.Status.COMMITTED,h.tick().status());assertEquals(1,h.contexts.size());}
    @Test void normalStaminaCostCooldownAndSeventyPercentMagnitude(){var h=new H("quick_slash","potency");h.loss(15);h.tick();assertEquals(95,h.current(ResourceType.STAMINA));assertEquals(1,h.cooldownSaves);assertEquals(.7*1.15,h.last().snapshot().modifiers().factor(),1e-9);assertEquals(SkillExecutionRequest.Origin.TRIGGERED,h.last().request().origin());assertEquals(0,h.total());}
    @Test void magicalRetaliationPaysManaNormally(){var h=new H("fire_bolt");h.loss(15);h.tick();assertEquals(100-h.last().profile().resourceCost(),h.current(ResourceType.MANA));assertEquals(100,h.current(ResourceType.STAMINA));assertEquals(1,h.cooldownSaves);}
    @Test void lossObservationNeverWritesNativeResources(){var h=new H("quick_slash");var before=new EnumMap<>(h.current);h.loss(30);assertEquals(before,h.current);assertEquals(0,h.healthWrites);}
    @Test void failedResourceCheckKeepsOneThresholdAndRetriesAfterOneSecond(){var h=new H("quick_slash");h.current.put(ResourceType.STAMINA,0d);h.loss(40);assertEquals("INSUFFICIENT_RESOURCE",h.tick().code());assertEquals(15,h.total());h.current.put(ResourceType.STAMINA,100d);h.time=.999;assertNull(h.tick());h.time=1;assertEquals(SkillExecutionResult.Status.COMMITTED,h.tick().status());assertEquals(0,h.total());}
    @Test void targetFailureDoesNotConsumeResourcesOrAccumulator(){var h=new H("quick_slash");h.targetValid=false;h.loss(15);assertEquals("FIXTURE_TARGET_MISSING",h.tick().code());assertEquals(15,h.total());assertEquals(100,h.current(ResourceType.STAMINA));h.time=1;h.targetValid=true;assertEquals(SkillExecutionResult.Status.COMMITTED,h.tick().status());}
    @Test void equipmentValidationRemainsAuthoritative(){var h=new H("quick_slash");h.weapon="STAFF";h.loss(15);assertEquals("INVALID_MAIN_HAND",h.tick().code());assertEquals(0,h.cooldownSaves);assertEquals(15,h.total());}
    @Test void normalCooldownPreventsAnotherRoot(){var h=new H("quick_slash");h.loss(15);h.tick();h.loss(15);h.time=1;assertEquals("COOLDOWN_ACTIVE",h.tick().code());assertEquals(1,h.contexts.size());assertEquals(15,h.total());}
    @Test void duplicateReceiptCannotCreateThreshold(){var h=new H("quick_slash");assertEquals("RETALIATION_LOSS_RECORDED",h.service.observeRetaliation(h.actor,"one",100,90,100,true,false));assertEquals("DUPLICATE_RETALIATION_RECEIPT",h.service.observeRetaliation(h.actor,"one",100,90,100,true,false));assertEquals(10,h.total());assertNull(h.tick());}
    @Test void rollingWindowExpiresExactTenSeconds(){var l=new L();l.loss("first",10,0);l.loss("second",5,9);assertEquals(15,l.total(9.999));assertEquals(5,l.total(10));assertTrue(l.claim(10).isEmpty());}
    @Test void excessIncomingDamageDoesNotBankMultipleCasts(){var l=new L();l.loss("one",90,0);assertEquals(15,l.total(0));var t=l.claim(0).orElseThrow();l.l.complete(l.actor,t.correlation(),true,0);assertEquals(0,l.total(0));assertTrue(l.claim(1).isEmpty());}
    @Test void newestActualLossSurvivesOldSampleExpiry(){var l=new L();l.loss("old",10,0);l.loss("new",10,9);assertEquals(15,l.total(9));assertEquals(10,l.total(10));}
    @Test void failedAttemptsCannotRefreshDamageEvidenceForever(){var l=new L();l.loss("one",15,0);for(int i=0;i<10;i++){var t=l.claim(i).orElseThrow();l.l.complete(l.actor,t.correlation(),false,i);}assertTrue(l.claim(10).isEmpty());assertEquals(0,l.total(10));}
    @Test void onePendingCastAcrossAllLinkedSlots(){var l=new L();var plans=Map.of(SkillSlot.SKILL01,"a",SkillSlot.SKILL02,"b",SkillSlot.SKILL03,"c");l.l.observe(l.actor,plans,"one",100,85,100,true,false,0);var t=l.l.claim(l.actor,plans,100,0).orElseThrow();assertTrue(l.l.pending(l.actor));assertTrue(l.l.claim(l.actor,plans,100,2).isEmpty());l.l.complete(l.actor,t.correlation(),true,2);assertEquals(SkillSlot.SKILL02,l.l.claim(l.actor,plans,100,2).orElseThrow().slot());}
    @Test void oneAttemptPerSecondAppliesAcrossSlots(){var l=new L();var plans=Map.of(SkillSlot.SKILL01,"a",SkillSlot.SKILL02,"b");l.l.observe(l.actor,plans,"one",100,85,100,true,false,0);var t=l.l.claim(l.actor,plans,100,0).orElseThrow();l.l.complete(l.actor,t.correlation(),true,0);assertTrue(l.l.claim(l.actor,plans,100,.999).isEmpty());assertEquals(SkillSlot.SKILL02,l.l.claim(l.actor,plans,100,1).orElseThrow().slot());}
    @Test void loadoutChangeDoesNotResetAttemptThrottle(){var l=new L();l.loss("one",15,0);var t=l.claim(0).orElseThrow();l.l.complete(l.actor,t.correlation(),true,0);l.l.clearPlans(l.actor);l.loss("new",15,.1);assertTrue(l.claim(.1).isEmpty());assertTrue(l.claim(1).isPresent());}
    @Test void loadoutChangeCannotReplaySameDamageReceipt(){var l=new L();l.loss("same",15,0);l.l.clearPlans(l.actor);assertEquals("DUPLICATE_RETALIATION_RECEIPT",l.loss("same",15,.1));assertTrue(l.claim(.1).isEmpty());}
    @Test void planIdentityChangeDiscardsOldCredit(){var l=new L();l.loss("one",15,0);assertTrue(l.l.claim(l.actor,Map.of(SkillSlot.SKILL01,"changed"),100,0).isEmpty());assertEquals(0,l.total(0));}
    @Test void windupHoldsPermitAndConsumesOnlyAtCommit(){var h=new H("heavy_swing");h.loss(15);assertEquals(SkillExecutionResult.Status.PENDING,h.tick().status());assertEquals(100,h.current(ResourceType.STAMINA));h.time=2;assertNull(h.tick());assertEquals(SkillExecutionResult.Status.COMMITTED,h.service.completeWindup(h.actor,h).status());assertEquals(0,h.total());assertEquals(1,h.cooldownSaves);}
    @Test void interruptedWindupRetainsOneThresholdWithoutPaying(){var h=new H("heavy_swing");h.loss(15);h.tick();h.service.cancel(h.actor,"NATIVE_DAMAGE_INTERRUPT");assertEquals(100,h.current(ResourceType.STAMINA));assertEquals(15,h.total());h.time=1;assertEquals(SkillExecutionResult.Status.PENDING,h.tick().status());}
    @Test void windupCommitRechecksTargetAndRetainsCreditOnFailure(){var h=new H("heavy_swing");h.loss(15);h.tick();h.targetValid=false;assertEquals("FIXTURE_TARGET_MISSING",h.service.completeWindup(h.actor,h).code());assertEquals(15,h.total());assertEquals(0,h.cooldownSaves);}
    @Test void changedLoadoutDuringWindupCannotReusePermit(){var h=new H("heavy_swing");h.loss(15);h.tick();assertTrue(h.b.service().unequipSkill(h.actor,SkillSlot.SKILL01).success());assertEquals("EMPTY_SLOT",h.service.completeWindup(h.actor,h).code());assertEquals(0,h.total());}
    @Test void lateNativeDispatchFailureDoesNotRefundPossibleHit(){var h=new H("quick_slash");h.failDispatch=true;h.loss(15);assertEquals(SkillExecutionResult.Status.TERMINATED,h.tick().status());assertEquals(95,h.current(ResourceType.STAMINA));assertEquals(1,h.cooldownSaves);assertEquals(0,h.total());h.time=1;assertNull(h.tick());}
    @Test void cooldownPersistenceFailureRefundsPreDispatchAndKeepsThreshold(){var h=new H("quick_slash");h.failCooldown=true;h.loss(15);assertTrue(h.tick().code().startsWith("COMMIT_FAILED"));assertTrue(h.contexts.isEmpty());assertEquals(100,h.current(ResourceType.STAMINA));assertEquals(15,h.total());}
    @Test void SkillDelayHasOneNormalPaymentAndNoSecondRetaliationPayment(){var h=new H("fire_bolt","skill_delay");h.loss(15);assertEquals("RELEASE_PENDING",h.tick().code());assertTrue(h.contexts.isEmpty());assertEquals(0,h.total());double mana=h.current(ResourceType.MANA);h.time=2;h.service.tickScheduled(h.actor,h);assertEquals(1,h.contexts.size());assertEquals(mana,h.current(ResourceType.MANA));assertEquals(.7*1.35,h.last().snapshot().modifiers().factor(),1e-9);}
    @Test void AttunementDoesNotBuildFromAutomaticRoot(){var h=new H("quick_slash","attunement");h.loss(15);h.tick();assertEquals(0,h.service.attunementStacks(h.actor,SkillSlot.SKILL01));}
    @Test void hostileHealthLossIsRequiredNotEnvironmentalOrHealing(){var h=new H("quick_slash");assertEquals("NO_ELIGIBLE_HOSTILE_LOSS",h.service.observeRetaliation(h.actor,"environment",100,80,100,false,false));assertEquals("NO_ELIGIBLE_HOSTILE_LOSS",h.service.observeRetaliation(h.actor,"heal",80,100,100,true,false));assertEquals("NO_ELIGIBLE_HOSTILE_LOSS",h.service.observeRetaliation(h.actor,"shield",100,100,100,true,false));assertEquals(0,h.total());}
    @Test void reflectedOrRecursiveLossCannotAdvanceAccumulator(){var h=new H("quick_slash");assertEquals("NO_ELIGIBLE_HOSTILE_LOSS",h.service.observeRetaliation(h.actor,"recursive",100,80,100,true,true));assertEquals(0,h.total());}
    @Test void nativeProvenanceExcludesReflectedRedirectedTriggeredButNotOrdinary(){for(var origin:HytaleDamageMetadata.Origin.values()){var m=new HytaleDamageMetadata(UUID.randomUUID(),"root","skill","corr",10,100,"effect",false,origin);assertEquals(Set.of(HytaleDamageMetadata.Origin.REFLECTED,HytaleDamageMetadata.Origin.REDIRECTED,HytaleDamageMetadata.Origin.TRIGGERED).contains(origin),m.noRetaliation());}}
    @Test void increasedMaxHealthRaisesThresholdAtAttempt(){var h=new H("quick_slash");h.loss(15);h.hpMax=200;assertNull(h.tick());h.loss(15);assertEquals(SkillExecutionResult.Status.COMMITTED,h.tick().status());}
    @Test void reducedMaximumUsesCurrentAuthoritativeThreshold(){var h=new H("quick_slash");h.hpMax=200;h.loss(15);assertNull(h.tick());h.hpMax=100;assertEquals(SkillExecutionResult.Status.COMMITTED,h.tick().status());}
    @Test void ownerCleanupDropsOldLossAndPendingPermit(){var h=new H("heavy_swing");h.loss(15);h.tick();h.service.forgetPassiveState(h.actor);assertEquals(0,h.total());assertEquals("RETALIATION_RECEIPT_REQUIRED",h.service.completeWindup(h.actor,h).code());}
    @Test void authorizationBindsActorSlotPlanAndCorrelation(){var l=new L();l.loss("one",15,0);var t=l.claim(0).orElseThrow();assertTrue(l.l.authorized(l.actor,t.slot(),t.planHash(),t.correlation()));assertFalse(l.l.authorized(UUID.randomUUID(),t.slot(),t.planHash(),t.correlation()));assertFalse(l.l.authorized(l.actor,SkillSlot.SKILL02,t.planHash(),t.correlation()));assertFalse(l.l.authorized(l.actor,t.slot(),"wrong",t.correlation()));assertFalse(l.l.authorized(l.actor,t.slot(),t.planHash(),"wrong"));}
    @Test void unrelatedCompletionCannotReleaseThePermit(){var l=new L();l.loss("one",15,0);var t=l.claim(0).orElseThrow();l.l.complete(l.actor,"other",true,1);assertTrue(l.l.pending(l.actor));l.l.complete(l.actor,t.correlation(),true,1);assertFalse(l.l.pending(l.actor));}
    @Test void historySampleCapacityFailsClosed(){var l=new L();for(int i=0;i<128;i++)assertEquals("RETALIATION_LOSS_RECORDED",l.loss("hit"+i,.01,0));assertEquals("RETALIATION_SAMPLE_CAPACITY",l.loss("extra",15,0));assertEquals(1.28,l.total(0),1e-9);assertTrue(l.claim(0).isEmpty());}
    @Test void receiptHistoryCapacityIsBounded(){var l=new L();for(int i=0;i<256;i++)l.loss("hit"+i,.01,0);assertEquals("RETALIATION_EVENT_CAPACITY",l.loss("extra",15,0));}
    @Test void inactiveOwnersExpireAndCapacityIsBounded(){var ledger=new RetaliationLedger();var plans=Map.of(SkillSlot.SKILL01,"p");for(int i=0;i<512;i++)assertEquals("RETALIATION_LOSS_RECORDED",ledger.observe(UUID.randomUUID(),plans,"one",100,99,100,true,false,0));assertEquals("RETALIATION_OWNER_CAPACITY",ledger.observe(UUID.randomUUID(),plans,"one",100,99,100,true,false,0));assertEquals("RETALIATION_LOSS_RECORDED",ledger.observe(UUID.randomUUID(),plans,"one",100,99,100,true,false,10));assertEquals(1,ledger.size());}
    @Test void malformedNativeNumbersFailClosed(){var l=new L();assertEquals("INVALID_RETALIATION_RECEIPT",l.l.observe(l.actor,l.plans,"x",100,Double.NaN,100,true,false,0));assertEquals("INVALID_RETALIATION_RECEIPT",l.l.observe(l.actor,l.plans,"y",100,90,0,true,false,0));assertThrows(IllegalArgumentException.class,()->l.claim(Double.NaN));}
    @Test void actorsHaveIndependentLossWindows(){var l=new L();l.loss("one",15,0);assertTrue(l.l.claim(UUID.randomUUID(),l.plans,100,0).isEmpty());assertTrue(l.claim(0).isPresent());}
    @Test void ordinaryUnlinkedSkillIsStillManual(){var h=new Stage11ResourcePassivesTest.H("quick_slash");assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());assertEquals(1,h.last().snapshot().modifiers().factor());}
    @Test void blockedSlotCannotStarveAnotherReadyRetaliation(){var l=new L();var plans=Map.of(SkillSlot.SKILL01,"a",SkillSlot.SKILL02,"b");l.l.observe(l.actor,plans,"one",100,85,100,true,false,0);var first=l.l.claim(l.actor,plans,100,0).orElseThrow();l.l.complete(l.actor,first.correlation(),false,0);assertEquals(SkillSlot.SKILL02,l.l.claim(l.actor,plans,100,1).orElseThrow().slot());}
    @Test void paidSkillDelayPreventsAnotherQueuedRetaliation(){var h=new H("fire_bolt","skill_delay");h.loss(15);h.tick();h.loss(15);h.time=1;assertNull(h.tick());assertEquals(1,h.service.pendingReleaseCount());assertEquals(1,h.cooldownSaves);}
    @Test void weakeningUsesSeventyPercentOfReductionNotRemainingMultiplier(){var h=new H("weakening_hex");h.weapon="WAND";h.loss(15);var r=h.tick();if(r.status()==SkillExecutionResult.Status.PENDING)h.service.completeWindup(h.actor,h);assertFalse(h.contexts.isEmpty(),r.toString());var c=h.last();var effects=new FiniteSupportEffects();effects.apply(c,List.of(h.actor),c.profile().support().durationSeconds(),0);var e=effects.forTarget(c.target().worldId(),h.actor,0).getFirst();assertEquals(1-(1-c.profile().support().coefficient())*.7,e.magnitude(),1e-9);}
    @Test void healingUsesSeventyPercentOnce(){var h=new H("minor_heal");h.loss(15);var r=h.tick();if(r.status()==SkillExecutionResult.Status.PENDING)h.service.completeWindup(h.actor,h);var c=h.last();double baseline=new com.inigmasgames.hytalerpg.combat.healing.HealingCalculationService().direct(20,c.profile().support().coefficient(),c.snapshot().derivedStats().healingMultiplier(),1,0);assertEquals(baseline*.7,SupportMagnitude.healing(c,1,50,100),1e-9);}
    @Test void skillWithNoRetaliationHistoryDoesNotPollNativeResources(){var h=new Stage11ResourcePassivesTest.H("quick_slash"){@Override public double maximum(ResourceType type){throw new AssertionError("idle native resources should not be read");}};assertNull(h.service.tickRetaliation(h.actor,h));}
    @Test void finiteSupportPercentagesAreReducedWithoutRescalingDuration(){var h=new H("battle_cry");h.loss(15);var result=h.tick();if(result.status()==SkillExecutionResult.Status.PENDING)h.service.completeWindup(h.actor,h);var c=h.last();var effects=new FiniteSupportEffects();effects.apply(c,List.of(h.actor),c.profile().support().durationSeconds(),0);var e=effects.forTarget(c.target().worldId(),h.actor,0).getFirst();assertEquals(c.profile().support().coefficient()*.7,e.magnitude(),1e-9);assertEquals(c.profile().support().durationSeconds(),e.ends());}
}
