package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.strike.*;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import com.inigmasgames.hytalerpg.combat.resource.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11StrikeSecondaryTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    static StrikeGeometryService.Candidate<String> target(String id,double x,double y,double z){return new StrikeGeometryService.Candidate<>(id,id,new Vec3(x,y,z),true,false,false);}
    static class P implements StrikeSecondaryRuntime.Port<String>{
        List<StrikeGeometryService.Candidate<String>> candidates=new ArrayList<>();Set<String> blocked=new HashSet<>();List<Delivery> delivered=new ArrayList<>();boolean fail;
        record Delivery(SkillExecutionContext child,String target,Double resolved){}
        public List<StrikeGeometryService.Candidate<String>> candidates(Vec3 point,double radius){return candidates;}
        public boolean lineOfSight(Vec3 p,StrikeGeometryService.Candidate<String> t){return !blocked.contains(t.stableId());}
        public void damage(SkillExecutionContext c,StrikeGeometryService.Candidate<String> t,Double resolved){delivered.add(new Delivery(c,t.stableId(),resolved));if(fail)throw new IllegalStateException("fixture native write uncertain");}
    }
    Stage11ResourcePassivesTest.H h(String...passives){var h=new Stage11ResourcePassivesTest.H("quick_slash");for(int i=0;i<passives.length;i++)h.link(passives[i],PassiveSlot.values()[i]);assertEquals(SkillExecutionResult.Status.COMMITTED,h.cast().status());return h;}
    List<StrikeSecondaryRuntime.Hit<String>> primary(){return List.of(new StrikeSecondaryRuntime.Hit<>(target("primary",0,0,1),100,7,false));}
    int run(SkillExecutionContext c,List<StrikeSecondaryRuntime.Hit<String>> hits,P p){return new StrikeSecondaryRuntime().afterPrimary(c,0,Vec3.ZERO,Vec3.FORWARD,hits,p);}
    @Test void cleavingPositiveAndRadialWrongFamilyNegativeGates(){assertTrue(f.accepts("shield_bash","cleaving_edge"));assertTrue(f.accepts("quick_slash","cleaving_edge"));assertFalse(f.accepts("ground_slam","cleaving_edge"));assertFalse(f.accepts("fire_bolt","cleaving_edge"));assertFalse(f.accepts("riposte","cleaving_edge"));}
    @Test void phantomPositiveAndTwoNegativeGates(){assertTrue(f.accepts("shield_bash","phantom_reach"));assertFalse(f.accepts("fireball","phantom_reach"));assertFalse(f.accepts("ground_slam","phantom_reach"));assertFalse(f.accepts("pounce","phantom_reach"));}
    @Test void compiledModifiersStayTypedWithoutProjectileConversion(){var p=f.plan("quick_slash","cleaving_edge","phantom_reach");assertTrue(p.strikes().cleavingEdge());assertTrue(p.strikes().phantomReach());assertEquals("STRIKE",p.finalFamily());assertFalse(p.finalTags().contains("PROJECTILE"));assertEquals(f.profiles.require("quick_slash"),f.resolver.resolve(f.profiles.require("quick_slash"),p));}
    @Test void cleaveKeepsPrimarySnapshotAndExcludesPrimaryFromSixtyPercentChildren(){var h=h("cleaving_edge");var p=new P();p.candidates=List.of(target("primary",0,0,1),target("other",.5,0,2));assertEquals(1,run(h.last(),primary(),p));assertEquals("other",p.delivered.getFirst().target);assertNull(p.delivered.getFirst().resolved);assertEquals(.6,p.delivered.getFirst().child.snapshot().modifiers().factor(),1e-9);assertEquals(1,h.last().snapshot().modifiers().factor(),1e-9);}
    @Test void cleaveIsExactlyEightyDegreeThreeMetreFrontalGeometry(){var h=h("cleaving_edge");var p=new P();double a=Math.toRadians(40);p.candidates=List.of(target("edge",Math.sin(a)*3,0,Math.cos(a)*3),target("outsideAngle",2,0,1),target("outsideRange",0,0,3.01),target("behind",0,0,-1),target("tooHigh",0,2.51,1));run(h.last(),primary(),p);assertEquals(List.of("edge"),p.delivered.stream().map(P.Delivery::target).toList());}
    @Test void cleaveCapsFourSortedStableSecondaryTargets(){var h=h("cleaving_edge");var p=new P();for(int i=9;i>=0;i--)p.candidates.add(target("enemy"+i,0,0,2));run(h.last(),primary(),p);assertEquals(List.of("enemy0","enemy1","enemy2","enemy3"),p.delivered.stream().map(P.Delivery::target).toList());assertEquals(4,h.last().effects().triggered());}
    @Test void allOriginalArcTargetsExcludedNotOnlyFirst(){var h=h("cleaving_edge");var p=new P();var first=target("first",0,0,1);var second=target("second",0,0,2);p.candidates=List.of(first,second,target("third",.1,0,2));run(h.last(),List.of(new StrikeSecondaryRuntime.Hit<>(first,50,50,false),new StrikeSecondaryRuntime.Hit<>(second,70,70,false)),p);assertEquals(List.of("third"),p.delivered.stream().map(P.Delivery::target).toList());}
    @Test void protectedUndamageableBlockedAndDuplicateCandidatesExcluded(){var h=h("cleaving_edge");var p=new P();var good=target("good",0,0,2);p.candidates=List.of(good,good,target("blocked",0,0,2),new StrikeGeometryService.Candidate<>("protected","protected",new Vec3(0,0,2),true,true,false),new StrikeGeometryService.Candidate<>("dead","dead",new Vec3(0,0,2),false,false,false));p.blocked.add("blocked");run(h.last(),primary(),p);assertEquals(List.of("good"),p.delivered.stream().map(P.Delivery::target).toList());}
    @Test void queryOverflowFailsClosedBeforeAnyDamage(){var h=h("cleaving_edge","phantom_reach");var p=new P();for(int i=0;i<257;i++)p.candidates.add(target("enemy"+i,0,0,2));assertEquals(0,run(h.last(),primary(),p));assertTrue(p.delivered.isEmpty());}
    @Test void cleaveCanStillResolveItsOwnArcWhenPrimaryMissesAtRelease(){var h=h("cleaving_edge");var p=new P();p.candidates=List.of(target("other",0,0,2.9));assertEquals(1,run(h.last(),List.of(),p));}
    @Test void cleaveControllerOnlyRunsOnceAndDoesNotRepeatOnAuthoredHits(){var h=h("cleaving_edge");var p=new P();p.candidates=List.of(target("other",0,0,2));assertEquals(1,run(h.last(),primary(),p));assertEquals(0,run(h.last(),primary(),p));assertEquals(0,new StrikeSecondaryRuntime().afterPrimary(h.last(),1,Vec3.ZERO,Vec3.FORWARD,primary(),p));assertEquals(1,p.delivered.size());}
    @Test void phantomCopiesResolvedPremitigationNotPostMitigationOrOffenseAgain(){var h=h("phantom_reach","potency");var p=new P();p.candidates=List.of(target("other",0,0,2));run(h.last(),primary(),p);assertEquals(60,p.delivered.getFirst().resolved);assertEquals(.69,p.delivered.getFirst().child.snapshot().modifiers().factor(),1e-9);assertEquals(1,p.delivered.size());}
    @Test void phantomUsesImpactCentredDistanceRatherThanCasterDistance(){var h=h("phantom_reach");var p=new P();var impact=target("primary",0,0,10);p.candidates=List.of(target("nearCaster",0,0,2),target("nearImpact",0,0,12.9),target("tooFar",0,0,13.01));run(h.last(),List.of(new StrikeSecondaryRuntime.Hit<>(impact,100,1,false)),p);assertEquals("nearImpact",p.delivered.getFirst().target);}
    @Test void phantomNearestTieUsesStableIdentityAndLos(){var h=h("phantom_reach");var p=new P();p.candidates=List.of(target("z",1,0,1),target("a",-1,0,1),target("blocked",0,0,1.1));p.blocked.add("blocked");run(h.last(),primary(),p);assertEquals("a",p.delivered.getFirst().target);}
    @Test void phantomExcludesPrimaryAndAllOriginalMultiTargetHits(){var h=h("phantom_reach");var p=new P();p.candidates=List.of(target("primary",0,0,1),target("alsoPrimary",0,0,1.2),target("new",0,0,2));var hits=new ArrayList<>(primary());hits.add(new StrikeSecondaryRuntime.Hit<>(p.candidates.get(1),100,5,false));run(h.last(),hits,p);assertEquals("new",p.delivered.getFirst().target);}
    @Test void phantomDoesNotFireForCancelledZeroLossOrInvalidHit(){for(var hit:List.of(new StrikeSecondaryRuntime.Hit<>(target("p",0,0,1),100,10,true),new StrikeSecondaryRuntime.Hit<>(target("p",0,0,1),100,0,false),new StrikeSecondaryRuntime.Hit<>(target("p",0,0,1),Double.NaN,10,false))){var h=h("phantom_reach");var p=new P();p.candidates=List.of(target("other",0,0,2));assertEquals(0,run(h.last(),List.of(hit),p));}}
    @Test void phantomOnlyInitialPrimaryNotLaterAuthoredHit(){var h=h("phantom_reach");var p=new P();p.candidates=List.of(target("other",0,0,2));assertEquals(0,new StrikeSecondaryRuntime().afterPrimary(h.last(),1,Vec3.ZERO,Vec3.FORWARD,primary(),p));}
    @Test void repeatedChildDoesNotProcEitherPassive(){var h=h("multistrike","cleaving_edge","phantom_reach");var p=new P();p.candidates=List.of(target("other",0,0,2));assertEquals(0,run(h.last().multistrikeCopy(1),primary(),p));assertEquals(0,run(h.last().multistrikeCopy(2),primary(),p));assertEquals(0,h.last().effects().triggered());}
    @Test void secondaryPreservesRootCorrelationAndCannotProcOrRepeat(){var h=h("cleaving_edge","phantom_reach","multistrike");var p=new P();p.candidates=List.of(target("other",0,0,2));run(h.last(),primary(),p);for(var d:p.delivered){var c=d.child;assertEquals(h.last().rootCastId(),c.rootCastId());assertEquals(h.last().request().correlationId(),c.request().correlationId());assertNotEquals(h.last().skillInstanceId(),c.skillInstanceId());assertEquals(c.skillInstanceId(),c.snapshot().skillInstanceId());assertTrue(c.derivedRelease());assertThrows(IllegalStateException.class,()->c.secondaryCopy("cleaving_edge",1,.6));assertThrows(IllegalStateException.class,()->c.multistrikeCopy(1));assertThrows(IllegalStateException.class,c::echoCopy);assertEquals(0,run(c,primary(),new P()));}}
    @Test void bothPassivesUseDistinctEffectsAndOneSharedRootBudget(){var h=h("cleaving_edge","phantom_reach","leeching");var p=new P();p.candidates=List.of(target("other",0,0,2));assertEquals(2,run(h.last(),primary(),p));assertEquals(3,h.last().effects().spawned());assertEquals(2,h.last().effects().triggered());assertNotEquals(p.delivered.get(0).child.skillInstanceId(),p.delivered.get(1).child.skillInstanceId());for(var d:p.delivered){assertSame(h.last().effects(),d.child.effects());assertSame(h.last().leechBudget(),d.child.leechBudget());assertSame(h.last().effects(),d.child.withSnapshot(d.child.snapshot()).effects());}}
    @Test void noAdditionalResourceCostOrCooldownOrCommit(){var h=h("cleaving_edge","phantom_reach");var p=new P();p.candidates=List.of(target("other",0,0,2));run(h.last(),primary(),p);assertEquals(95,h.current(ResourceType.STAMINA));assertEquals(1,h.cooldownSaves);assertEquals(1,h.contexts.size());}
    @Test void uncertainNativeWriteDoesNotRefundBudgetOrReplayController(){var h=h("cleaving_edge");var p=new P();p.candidates=List.of(target("other",0,0,2));p.fail=true;assertThrows(IllegalStateException.class,()->run(h.last(),primary(),p));assertEquals(1,h.last().effects().triggered());assertEquals(0,run(h.last(),primary(),p));assertEquals(1,p.delivered.size());}
    @Test void rootTriggeredBudgetSharedAcrossBothPassives(){var h=h("cleaving_edge","phantom_reach");for(int i=0;i<16;i++)assertEquals("PASS",h.last().effects().claim("other"+i,1,true));var p=new P();p.candidates=List.of(target("victim",0,0,2));run(h.last(),primary(),p);assertTrue(p.delivered.isEmpty());assertEquals(16,h.last().effects().triggered());}
    @Test void fortyEightTotalEffectsAndGenerationThreeBounds(){var b=new RootEffectBudget(UUID.randomUUID(),"root");for(int i=0;i<47;i++)assertEquals("PASS",b.claim("effect"+i,3,false));assertEquals(48,b.spawned());assertEquals("ROOT_SPAWN_EFFECT_BUDGET",b.claim("extra",1,true));assertEquals("MAX_GENERATION",b.claim("deep",4,false));assertEquals("DUPLICATE_EFFECT",b.claim("effect0",1,false));}
    @Test void duplicateEffectDoesNotConsumeAdditionalBudget(){var b=new RootEffectBudget(UUID.randomUUID(),"root");assertEquals("PASS",b.claim("once",1,true));assertEquals("DUPLICATE_EFFECT",b.claim("once",1,true));assertEquals(1,b.triggered());assertEquals(2,b.spawned());assertEquals("INVALID_EFFECT_ID",b.claim(" ",1,true));}
    @Test void controllersBoundedAndDifferentRootBudgetsIndependent(){var actor=UUID.randomUUID();var a=new RootEffectBudget(actor,"a");var b=new RootEffectBudget(actor,"b");for(int i=0;i<16;i++)assertTrue(a.once("controller"+i));assertFalse(a.once("extra"));assertFalse(a.once("controller0"));assertTrue(b.once("controller0"));assertTrue(a.owns(actor,"a"));assertFalse(a.owns(actor,"b"));}
    @Test void childCreationCannotFabricateUnknownUnlinkedOrUnboundedEffect(){var h=h("cleaving_edge");assertThrows(IllegalStateException.class,()->h.last().secondaryCopy("phantom_reach",1,.6));assertThrows(IllegalStateException.class,()->h.last().secondaryCopy("cleaving_edge",17,.6));assertThrows(IllegalStateException.class,()->h.last().secondaryCopy("cleaving_edge",1,Double.NaN));assertThrows(IllegalStateException.class,()->h.last().secondaryCopy("invented",1,.6));}
    @Test void phantomAtExactlyThreeMetresAllowedAndVerticalDistanceCounts(){var h=h("phantom_reach");var p=new P();p.candidates=List.of(target("edge",0,0,4),target("high",0,3.001,1));run(h.last(),primary(),p);assertEquals("edge",p.delivered.getFirst().target);}
    @Test void cleaveReachAndConcentrationChangeMatchingPresentationGeometry(){var h=h("cleaving_edge","long_reach","concentration");var p=new P(){public void presentCleave(Vec3 o,Vec3 d,double range,double angle){assertEquals(3.75,range);assertEquals(56,angle);}};double a=Math.toRadians(30);p.candidates=List.of(target("extended",0,0,3.7),target("tooWide",Math.sin(a)*2,0,Math.cos(a)*2));run(h.last(),primary(),p);assertEquals(List.of("extended"),p.delivered.stream().map(P.Delivery::target).toList());assertEquals(.6*1.3,p.delivered.getFirst().child.snapshot().modifiers().factor(),1e-9);}
    @Test void presentationAdapterFailureCannotEraseOrRepeatGameplay(){var h=h("cleaving_edge","phantom_reach");var p=new P(){public void presentCleave(Vec3 o,Vec3 d,double r,double a){throw new IllegalStateException("fixture art unavailable");}public void presentPhantom(Vec3 a,Vec3 b){throw new IllegalStateException("fixture art unavailable");}};p.candidates=List.of(target("other",0,0,2));assertEquals(2,run(h.last(),primary(),p));assertEquals(0,run(h.last(),primary(),p));assertEquals(2,p.delivered.size());}
}
