package com.inigmasgames.hytalerpg;

import com.inigmasgames.hytalerpg.domain.*;
import com.inigmasgames.hytalerpg.execution.*;
import com.inigmasgames.hytalerpg.execution.ProliferationRuntime.*;
import com.inigmasgames.hytalerpg.execution.area.AreaGeometry;
import com.inigmasgames.hytalerpg.execution.math.Vec3;
import com.inigmasgames.hytalerpg.combat.status.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Stage11ProliferationTest {
    final Stage11FoundationTest f=new Stage11FoundationTest();
    SkillExecutionContext c(String skill,String... ids){var base=new Stage11HitProcTest.H("fire_bolt").last();return new SkillExecutionContext(base.request(),base.rootCastId(),base.skillInstanceId(),f.effective(skill,ids),f.plan(skill,ids),base.snapshot(),base.equipment(),base.target(),false);}
    Payload payload(SkillExecutionContext c,Kind kind){return new Payload(c,kind,kind==Kind.POISON?3:kind==Kind.CHILL?4:1,kind==Kind.POISON?3:kind==Kind.CHILL?4:1,.1,10,4);}
    Target target(int id,double x){return target(id,new Vec3(x,0,0));}
    Target target(int id,Vec3 at){return new Target(new UUID(0,id),new AreaGeometry.Bounds(at,at.add(new Vec3(.1,.1,.1))),true,true,false,true);}
    static class P implements Port {
        List<Target> targets=new ArrayList<>();List<Payload> applied=new ArrayList<>();List<UUID> recipients=new ArrayList<>();List<String> traces=new ArrayList<>();int queries;boolean overflow,throwQuery,throwApply;
        public Query query(SkillExecutionContext c,Vec3 point,double radius,int budget){queries++;assertEquals(4,radius);assertEquals(256,budget);if(throwQuery)throw new IllegalStateException("fixture");return new Query(targets,overflow);}
        public String apply(Payload payload,Target target){if(throwApply)throw new IllegalStateException("fixture");applied.add(payload);recipients.add(target.id());return "APPLIED";}
        public void trace(SkillExecutionContext c,String verdict,UUID target){traces.add(verdict);}
    }
    @Test void positiveAndNegativeSourceStatusGates(){for(String skill:List.of("fire_bolt","poison_cloud","frost_bolt","chilling_aura"))assertTrue(f.accepts(skill,"proliferation"),skill);for(String skill:List.of("minor_heal","vortex","quick_slash"))assertFalse(f.accepts(skill,"proliferation"),skill);}
    @Test void burnScalesMagnitudeAndRemainingDurationExactlyOnce(){var c=c("fire_bolt","proliferation","combustion");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);var copied=p.applied.getFirst();assertEquals(.07,copied.coefficient(),1e-9);assertEquals(7,copied.strength());assertEquals(2.8,copied.remaining(),1e-9);assertEquals(c.snapshot().modifiers(),copied.context().snapshot().modifiers());}
    @Test void poisonRetainsPackageStackCountAndCap(){var c=c("poison_cloud","proliferation");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.POISON)),p);assertEquals(3,p.applied.getFirst().stacks());assertEquals(3,p.applied.getFirst().sourceCap());assertEquals(.07,p.applied.getFirst().coefficient(),1e-9);}
    @Test void concentratedPoisonDoesNotReapplyVirulenceOrRestoreCap(){var c=c("poison_cloud","proliferation","concentrated_venom","virulence");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(new Payload(c,Kind.POISON,1,1,.175,17.5,8)),p);assertEquals(1,p.applied.getFirst().stacks());assertEquals(1,p.applied.getFirst().sourceCap());assertEquals(.1225,p.applied.getFirst().coefficient(),1e-9);}
    @Test void chillFloorsScaledStacksToMinimumOne(){for(int count=1;count<=4;count++){var c=c("frost_bolt","proliferation");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(new Payload(c,Kind.CHILL,count,4,1,count,4)),p);assertEquals(Math.max(1,(int)(count*.7)),p.applied.getFirst().stacks());}}
    @Test void noFrozenPayloadTypeExists(){assertEquals(Set.of(Kind.BURN,Kind.POISON,Kind.CHILL),Set.of(Kind.values()));assertThrows(IllegalArgumentException.class,()->Kind.valueOf("FROZEN"));}
    @Test void threeNearestEnemiesChosenDeterministically(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.addAll(List.of(target(4,4),target(2,2),target(3,3),target(1,1)));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertEquals(List.of(new UUID(0,1),new UUID(0,2),new UUID(0,3)),p.recipients);}
    @Test void stableIdsBreakDistanceTiesAndDeduplicate(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.addAll(List.of(target(2,1),target(1,1),target(1,1)));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertEquals(List.of(new UUID(0,1),new UUID(0,2)),p.recipients);}
    @Test void fullThreeDimensionalDistanceNotHorizontalOnly(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,new Vec3(0,3,0)));p.targets.add(target(2,new Vec3(0,4.1,0)));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertEquals(List.of(new UUID(0,1)),p.recipients);}
    @Test void boundsCanTouchRangeWhileEntityCentreIsOutside(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(new Target(new UUID(0,1),new AreaGeometry.Bounds(new Vec3(3.9,0,0),new Vec3(8,2,1)),true,true,false,true));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertEquals(1,p.applied.size());}
    @Test void deadFriendlyProtectedAndBlockedTargetsAreRejected(){var c=c("fire_bolt","proliferation");var p=new P();var bounds=target(1,1).bounds();p.targets.add(new Target(new UUID(0,1),bounds,false,true,false,true));p.targets.add(new Target(new UUID(0,2),bounds,true,false,false,true));p.targets.add(new Target(new UUID(0,3),bounds,true,true,true,true));p.targets.add(new Target(new UUID(0,4),bounds,true,true,false,false));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertTrue(p.applied.isEmpty());}
    @Test void deadSourceCannotBeItsOwnRecipient(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(new UUID(0,1),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertTrue(p.applied.isEmpty());}
    @Test void sameSkillTransfersAtMostOnePackageOfEachKind(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN),new Payload(c,Kind.BURN,1,1,.3,30,2),payload(c,Kind.POISON),payload(c,Kind.CHILL)),p);assertEquals(3,p.applied.size());assertEquals(1,p.queries);assertEquals(.21,p.applied.stream().filter(x->x.kind()==Kind.BURN).findFirst().orElseThrow().coefficient(),1e-9);}
    @Test void allThreeStatusKindsUseSameNearestThreeRecipients(){var c=c("fire_bolt","proliferation");var p=new P();for(int i=1;i<=4;i++)p.targets.add(target(i,i));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN),payload(c,Kind.POISON),payload(c,Kind.CHILL)),p);assertEquals(9,p.applied.size());assertEquals(3,new HashSet<>(p.recipients).size());assertEquals(9,c.effects().triggered());}
    @Test void childRetainsRootCorrelationAndSharedBudget(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);var child=p.applied.getFirst().context();assertEquals(c.rootCastId(),child.rootCastId());assertEquals(c.request(),child.request());assertNotEquals(c.skillInstanceId(),child.skillInstanceId());assertSame(c.effects(),child.effects());assertSame(c.leechBudget(),child.leechBudget());}
    @Test void spreadChildCannotProliferateOnLaterDeath(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));var runtime=new ProliferationRuntime();runtime.death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);runtime.death(UUID.randomUUID(),Vec3.ZERO,List.of(p.applied.getFirst()),p);assertEquals(1,p.applied.size());}
    @Test void unlinkedOrDerivedStatusIsNotASource(){var plain=c("fire_bolt");var linked=c("fire_bolt","proliferation","echo");var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(plain,Kind.BURN),payload(linked.echoCopy(),Kind.BURN)),p);assertTrue(p.applied.isEmpty());}
    @Test void duplicateDeathCannotSpreadAgain(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));var runtime=new ProliferationRuntime();var id=UUID.randomUUID();runtime.death(id,Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);runtime.death(id,Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertEquals(1,p.applied.size());assertTrue(p.traces.contains("DUPLICATE_PROC_CONTACT"));}
    @Test void nativeQueryAndApplyFailuresRemainTyped(){for(boolean query:List.of(true,false)){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));p.throwQuery=query;p.throwApply=!query;new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertTrue(p.applied.isEmpty());assertTrue(p.traces.stream().anyMatch(x->x.contains("REJECTED")));}}
    @Test void candidateOverflowNeverPartiallySelects(){var c=c("fire_bolt","proliferation");var p=new P();p.targets.add(target(1,1));p.overflow=true;new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertTrue(p.applied.isEmpty());assertTrue(p.traces.contains("PROLIFERATION_CANDIDATE_BUDGET"));}
    @Test void sourceBudgetStopsUnboundedDeathWork(){var c=c("fire_bolt","proliferation");var p=new P();new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,Collections.nCopies(33,payload(c,Kind.BURN)),p);assertEquals(0,p.queries);assertTrue(p.traces.contains("PROLIFERATION_DEATH_SOURCE_BUDGET"));}
    @Test void finiteRootSharesExistingSecondaryLimit(){var c=c("fire_bolt","proliferation");for(int i=0;i<16;i++)assertEquals("PASS",c.effects().claim("prior"+i,2,true));var p=new P();p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.BURN)),p);assertTrue(p.applied.isEmpty());assertTrue(p.traces.contains("ROOT_TRIGGERED_SECONDARY_BUDGET"));}
    @Test void auraUsesEpochAdmissionWithoutLifetimeBudget(){var c=c("chilling_aura","proliferation");var p=new P(){@Override public String claimSecondary(SkillExecutionContext ignored,String token){return "PASS";}};p.targets.add(target(1,1));var runtime=new ProliferationRuntime(()->0);for(int i=0;i<80;i++)runtime.death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.CHILL)),p);assertEquals(80,p.applied.size());assertEquals(0,c.effects().triggered());assertEquals(80,p.applied.stream().map(x->x.context().skillInstanceId()).distinct().count());}
    @Test void auraEpochRejectionIsTypedAndCannotBypassSharedLimit(){var c=c("chilling_aura","proliferation");var p=new P(){@Override public String claimSecondary(SkillExecutionContext ignored,String token){return "AURA_EPOCH_SECONDARY_LIMIT_OR_INACTIVE";}};p.targets.add(target(1,1));new ProliferationRuntime().death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.CHILL)),p);assertTrue(p.applied.isEmpty());assertTrue(p.traces.contains("AURA_EPOCH_SECONDARY_LIMIT_OR_INACTIVE"));}
    @Test void auraDeathDedupeWindowIsBoundedAndExpires(){var c=c("chilling_aura","proliferation");double[] time={0};var runtime=new ProliferationRuntime(()->time[0]);var p=new P(){@Override public String claimSecondary(SkillExecutionContext ignored,String token){return "PASS";}};p.targets.add(target(1,1));for(int i=0;i<257;i++)runtime.death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.CHILL)),p);assertEquals(256,p.applied.size());assertTrue(p.traces.contains("AURA_STATUS_DEATH_WINDOW_BUDGET"));time[0]=120;runtime.death(UUID.randomUUID(),Vec3.ZERO,List.of(payload(c,Kind.CHILL)),p);assertEquals(257,p.applied.size());runtime.cancel(c.request().actorId());}
    @Test void chillRecordsOwnContributionNotAnotherCasterStacks(){var registry=new ChillSourceRegistry();SkillExecutionContext a=c("frost_bolt","proliferation"),b=c("frost_bolt","proliferation");var victim=UUID.randomUUID();registry.observed(a,victim,null,new StatusService.StatusView(1,5),0);registry.observed(b,victim,new StatusService.StatusView(1,4),new StatusService.StatusView(3,5),1);var sources=registry.takeForDeath(victim,new StatusService.StatusView(3,4),2);assertEquals(List.of(1,2),sources.stream().map(ChillSourceRegistry.Source::stacks).sorted().toList());assertEquals(Set.of(a.request().actorId(),b.request().actorId()),sources.stream().map(x->x.context().request().actorId()).collect(java.util.stream.Collectors.toSet()));}
    @Test void chillThresholdConsumesAllSourceProvenance(){var registry=new ChillSourceRegistry();var c=c("frost_bolt","proliferation");var id=UUID.randomUUID();registry.observed(c,id,null,new StatusService.StatusView(4,5),0);registry.observed(c,id,new StatusService.StatusView(4,4),null,1);assertEquals(0,registry.size());assertTrue(registry.takeForDeath(id,null,1).isEmpty());}
    @Test void chillExpiryCannotLeaveTransferableStacks(){var registry=new ChillSourceRegistry();var c=c("frost_bolt","proliferation");var id=UUID.randomUUID();registry.observed(c,id,null,new StatusService.StatusView(1,1),0);assertTrue(registry.takeForDeath(id,new StatusService.StatusView(2,1),2).isEmpty());}
    @Test void chillSpreadCannotRegisterRecursiveSource(){var registry=new ChillSourceRegistry();var c=c("frost_bolt","proliferation").proliferationCopy("child");registry.observed(c,UUID.randomUUID(),null,new StatusService.StatusView(2,3),0);assertEquals(0,registry.size());}
    @Test void chillSourceBudgetDoesNotRemoveAppliedNativeChill(){var registry=new ChillSourceRegistry();var c=c("frost_bolt","proliferation");for(int i=0;i<256;i++)registry.observed(c,UUID.randomUUID(),null,new StatusService.StatusView(1,5),0);assertEquals("CHILL_PROVENANCE_BUDGET",registry.observed(c,UUID.randomUUID(),null,new StatusService.StatusView(1,5),0));assertEquals(256,registry.size());registry.cancel(c.request().actorId());assertEquals(0,registry.size());}
    @Test void periodicDeathClaimsStrongestRemainingSnapshotOnce(){var runtime=new PeriodicStatusRuntime<String,String>();UUID owner=UUID.randomUUID(),victim=UUID.randomUUID();var source=new PeriodicStatusRuntime.Source(owner,"fire_bolt",victim,PeriodicStatusRuntime.Kind.BURN);var p=new Stage11HitProcTest.D();runtime.apply(source,"strong","target",.3,30,4,1,1,0,p);runtime.apply(source,"weak","target",.1,10,4,1,1,.5,p);var exported=runtime.takeForDeath(victim,1);assertEquals(1,exported.size());assertEquals("strong",exported.getFirst().context());assertEquals(3.5,exported.getFirst().remaining());assertEquals(.3,exported.getFirst().coefficient());assertTrue(runtime.takeForDeath(victim,1).isEmpty());runtime.tick(owner,2,p);assertEquals(0,runtime.size());assertEquals(0,p.total);}
    @Test void expiredPeriodicPackagesDoNotProliferate(){var runtime=new PeriodicStatusRuntime<String,String>();UUID owner=UUID.randomUUID(),victim=UUID.randomUUID();var source=new PeriodicStatusRuntime.Source(owner,"fire_bolt",victim,PeriodicStatusRuntime.Kind.BURN);runtime.apply(source,"c","target",.1,10,1,1,1,0,new Stage11HitProcTest.D());assertTrue(runtime.takeForDeath(victim,2).isEmpty());assertEquals(0,runtime.size());}
    @Test void transferredChillUsesReducedDurationAndNoDeepFreezeBonus(){var kernel=com.inigmasgames.hytalerpg.combat.RpgCombatKernel.createProduction();var id=UUID.randomUUID();var result=kernel.statuses().applyChill(UUID.randomUUID(),"root",id,ControlProfile.NORMAL,2,false,2.8);assertEquals(2,result.results().size());assertEquals(2,result.results().getLast().stacks());assertEquals(2.8,result.results().getLast().remainingSeconds());}
    @Test void transferMayReachNormalThresholdButDoesNotCopyFrozen(){var kernel=com.inigmasgames.hytalerpg.combat.RpgCombatKernel.createProduction();UUID id=UUID.randomUUID(),owner=UUID.randomUUID();kernel.statuses().applyChill(owner,"first",id,ControlProfile.NORMAL,4,false);var result=kernel.statuses().applyChill(owner,"transfer",id,ControlProfile.NORMAL,2,false,2.8);assertEquals(StatusService.Outcome.THRESHOLD,result.results().getFirst().outcome());assertEquals(RpgStatusType.FROZEN,result.results().getFirst().type());assertEquals(1,result.results().size());}
}
