package com.inigmasgames.canvasui.api;

public enum CanvasEventType {
    CANVAS_OPENED, CANVAS_CLOSED, VIEWPORT_CHANGED,
    NODE_CREATED, NODE_REMOVED, NODE_SELECTED, NODE_MOVED,
    DRAG_STARTED, DRAG_ENDED,
    CONNECTION_PREVIEW_STARTED, CONNECTION_CREATED, CONNECTION_REJECTED, CONNECTION_REMOVED,
    CANVAS_CHANGED
}
