package com.inigmasgames.persistentnpcs.epistemic;

public enum Answerability {
    KNOWN, PARTIALLY_KNOWN, INFERRED, SUBJECTIVE, UNKNOWN, CONFLICTED, AMBIGUOUS,
    NEEDS_CURRENT_PERCEPTION,
    NEEDS_CLARIFICATION, NEEDS_ACTION, WITHHELD, UNRESOLVED, UNIMPLEMENTED
}
