package com.inigmasgames.persistentnpcs.epistemic;

public enum ClaimSupportStatus {
    SUPPORTED, SUPPORTED_AS_INFERENCE, SUBJECTIVE_ALLOWED, HYPOTHETICAL_ALLOWED,
    PARTIALLY_SUPPORTED, UNSUPPORTED, CONTRADICTED, DISCLOSURE_BLOCKED,
    UNPARSEABLE_OBJECTIVE_CLAIM
}
