package com.inigmasgames.persistentnpcs.epistemic;

public enum DialogueAct {
    GREETING, SOCIAL_CHECKIN, FACT_QUERY, IDENTITY_QUERY, RECALL_QUERY,
    PERCEPTION_QUERY, SELF_STATE_QUERY, OPINION_QUERY, PREFERENCE_QUERY,
    EMOTION_QUERY, CLARIFICATION_REQUEST, CORRECTION, CHALLENGE,
    SELF_DISCLOSURE, INFORMATION_STATEMENT, ACTION_REQUEST, SOCIAL_INVITATION,
    PROMISE_OR_COMMITMENT, HYPOTHETICAL, FAREWELL, UNRESOLVED
}
