package com.inigmasgames.persistentnpcs.epistemic;

public enum EpistemicQueryKind {
    IDENTITY_RECALL, EPISODIC_RECALL, CURRENT_PERCEPTION, NPC_SELF_STATE,
    RELATIONSHIP_FACT, SUBJECTIVE_PREFERENCE, ACTION_REQUEST, CLARIFICATION,
    CORRECTION, OBJECTIVE_PROPERTY, GENERAL_SOCIAL, UNRESOLVED
}
