package com.inigmasgames.persistentnpcs.epistemic;

public enum EvidenceSourceKind {
    AUTHORED_CANON, DIRECT_OBSERVATION, CURRENT_WORLD_STATE, SELF_STATE,
    ACTION_CAPABILITY, ACTION_RESULT, CONVERSATION_WORKSPACE, RELATIONSHIP_STATE,
    PERSISTENT_FACT,
    PLAYER_TESTIMONY, NPC_TESTIMONY, DOCUMENTED_WORLD_LORE, EPISODIC_MEMORY,
    DERIVED_REFLECTION, PROCEDURAL_OUTCOME
}
