package com.inigmasgames.persistentnpcs.training.curation;

import java.util.Set;

/** Stable D4/D5 reason vocabulary used by reports, reviews, and manifests. */
public final class FilterReasonCodes {
    private FilterReasonCodes() { }
    public static final Set<String> VOCABULARY = Set.of(
            "UPSTREAM_ORBIS_BOUNDARY_FAILURE", "PRODUCTION_PARITY_FAILURE",
            "CONTRACT_INVALID", "ORACLE_FAIL_REQUIRED_PROPOSITION",
            "ORACLE_FAIL_UNSUPPORTED_CLAIM", "ORACLE_FAIL_ACTION_TRUTH",
            "ORACLE_FAIL_SOURCE_ATTRIBUTION", "OVER_ABSTENTION", "FALSE_CERTAINTY",
            "WRONG_UNCERTAINTY_MODE", "MISSING_CLARIFICATION_SLOT",
            "DISCLOSURE_VIOLATION",
            "CLAIM_FIREWALL_REJECTED", "PRIVACY_RAW_AUDIO",
            "PRIVACY_SECRET_OR_CREDENTIAL", "PRIVACY_PRIVATE_PATH",
            "PRIVACY_STABLE_PLAYER_ID", "HIDDEN_REASONING_PRESENT",
            "PII_OR_SECRET_RISK", "PROFILE_MEMORIZATION_RISK",
            "LOW_INFORMATION_OR_STOCK_RESPONSE", "NEEDS_HUMAN_REVIEW",
            "NEEDS_REVIEW_REAL_PLAYER_CONSENT", "TEACHER_TERMS_INELIGIBLE",
            "TEACHER_POLICY_MISMATCH", "STYLE_POLICY_VIOLATION",
            "SOURCE_ARTIFACT_DEFECT", "PROMPT_INJECTION_TREATED_AS_DATA",
            "EXACT_DUPLICATE", "FUZZY_DUPLICATE", "SEMANTIC_FAMILY_DUPLICATE",
            "HOLDOUT_CONTAMINATION", "BENCHMARK_CONTAMINATION",
            "EXACT_DUPLICATE_MERGED", "FUZZY_DUPLICATE_MERGED",
            "AMBIGUOUS_FUZZY_COLLISION", "SEMANTIC_FAMILY_LEAKAGE",
            "PROFILE_HOLDOUT_VIOLATION", "PROTECTED_EXACT_CONTAMINATION",
            "PROTECTED_NORMALIZED_CONTAMINATION", "PROTECTED_ENTITY_CONTAMINATION",
            "PROTECTED_FAMILY_CONTAMINATION", "PROTECTED_ANCESTRY_CONTAMINATION",
            "PROTECTED_FUZZY_CONTAMINATION", "UNREVIEWED_ROW",
            "REJECTED_ROW", "CONNECTED_OR_CANARY_IN_TRAIN", "LICENSE_POLICY_BLOCK",
            "DATASET_POLICY_BLOCK", "FREEZE_GATE_FAILED", "COVERAGE_GAP");
}
