package com.inigmasgames.hytalerpg.diagnostics;

public enum RpgTraceEventType {
    EQUIP_SKILL_REQUEST, EQUIP_SKILL_COMMITTED,
    EQUIP_PASSIVE_REQUEST, EQUIP_PASSIVE_COMMITTED,
    UNEQUIP_SKILL_REQUEST, UNEQUIP_SKILL_COMMITTED,
    UNEQUIP_PASSIVE_REQUEST, UNEQUIP_PASSIVE_COMMITTED,
    LINK_REQUEST, LINK_ACCEPTED, LINK_REJECTED,
    UNLINK, COMPILE_BEGIN, COMPILE_STAGE, COMPILE_SUCCESS, COMPILE_FAILURE,
    LOAD, SAVE, MIGRATION,
    CAST_REQUEST, CAST_COMMITTED, SPAWN, HIT, PAYLOAD, SPLIT, PIERCE, FORK, CHAIN,
    RICOCHET, RETURN, STATUS_APPLIED, TRIGGER_FIRED, TERMINATE
}
