package com.inigmasgames.persistentnpcs.orbis;

public enum CancellationReason {
    USER_BARGE_IN,
    WORLD_UNLOAD,
    PROVIDER_TIMEOUT,
    RESOURCE_STARVED,
    INVALID_DECISION,
    ACTION_REJECTED,
    ADMIN_CANCEL,
    SERVER_SHUTDOWN,
    PLAYER_DISCONNECT,
    CONVERSATION_RANGE_LOST,
    PLAYER_INTERRUPT,
    NPC_DESPAWN,
    SUPERSEDED,
    OPERATOR_CANCEL,
    CAPTURE_OVERFLOW,
    STT_UNAVAILABLE,
    STT_FAILED,
    EMPTY_TRANSCRIPT,
    AUDIENCE_FAILED,
    NO_AUDIENCE,
    PROVIDER_FAILURE,
    PLUGIN_SHUTDOWN
}
